### ISSUE TITLE
Add documentation for options (byref, fmode, recurse, etc)

### ISSUE THREAD

**Issue by TD22057** [uqfoundation/dill#122]
It would be really helpful if there was some documentation for all of the options to dump().  Please add a couple of lines to explain the options to the function doc strings.  Ideally, the users guide would then expand on that to include more examples of when you might want to use each flag.

**Comment by matsjoyce** [comment]
It would be cool to use sphinx for this, because then we can make web accessible / readthedocs / pdf documentation as well.

**Comment by mmckerns** [comment]
Yes, I agree, the settings should be documented better -- at least in the module level documentation, and at most in every method in which they are used.

I did at one time (2010 and earlier) keep `epydoc` pages for `dill` and my other codes, so a lot of the work to make the module docs `reST` compliant is already done.  `sphinx` was not yet in wide usage at the time, so I went with `epydoc`. See: http://docs.danse.us/pathos/current/dill-module.html.

I'm usually pretty good about having good in-code documentation that is exposed to the user through `help`… so the lack of `dill.settings` doc is a bit of an oversight.  I've never been very good about writing additional tutorial docs, so anything in that vein I could use a bit of help on.  There's probably a lot of good examples that could be pulled from stackoverflow, however.

I'm open to `sphinx` docs.  It's probably the right thing to do… but definitely the `dill.settings` stuff should be documented better as a first step.

**Comment by robert-simione** [comment]
Found this ticket, just wanted to add that documentation on common flags would have saved over a day of digging if the behavior of dill.settings['recurse'] was documented somewhere. I only found out that I needed this setting for the behavior I expected from dill after stumbling into this question https://github.com/uqfoundation/dill/issues/188

**Comment by spenceryee** [comment]
Any update on this? I've been digging around and I'm still not entirely sure what `recurse` does.

**Comment by mmckerns** [comment]
No, the module-level docs still need to be written.  In short, `byref`, `recurse` are serialization variants.  If `byref = True`, then `dill` behaves a lot more like `pickle` as certain objects (like modules) are pickled by reference as opposed to attempting to pickle the object itself.  If `recurse = True`, then `dill` behaves a lot more like `cloudpickle` in that objects referred to in the global dictionary are recursively traced and pickled, instead of the default behavior of attempting to store the entire global dictionary.

**Comment by mmckerns** [comment]
Closing due to #388
