### ISSUE TITLE
dotdict incompatibility

### ISSUE THREAD

**Issue by pyrytakala** [uqfoundation/dill#127]
Running the following

import dill
from dotdict import dotdict

c = {}
c[1] = "a"
d = dotdict(c)

dill.loads(dill.dumps(c))
dill.loads(dill.dumps(d))

I am getting:
  File "test.py", line 9, in <module>
    dill.loads(dill.dumps(d))
  File ".../lib/python2.7/site-packages/dill/dill.py", line 209, in loads
    return load(file)
  File ".../lib/python2.7/site-packages/dill/dill.py", line 199, in load
    obj = pik.load()
  File ".../lib/python2.7/pickle.py", line 858, in load
    dispatch\[key\](self)
  File ".../lib/python2.7/pickle.py", line 1215, in load_build
    setstate = getattr(inst, "\__setstate\__", None)
KeyError: '\__setstate\__'

**Comment by pyrytakala** [comment]
This appears related http://stackoverflow.com/questions/10364332/how-to-pickle-python-object-derived-from-dict , I was able to define my own dotdict as:

class dotdict(dict):
    def \__getattr\__(self, attr):
        if attr.startswith('\__'):
            raise AttributeError
        return self.get(attr)
    \__setattr\__= dict.\__setitem\__
    \__delattr\__= dict.\__delitem\__

Now it becomes possible to dill it

**Comment by mmckerns** [comment]
This is probably a better question for the `dotdict` author.  If you can, however, find a more generalized object pattern that fails (other than specifically a  `dotdict` instance), then maybe there is a feature request here.

Could you try pickling the offending object again, but with "dill.detect.trace(True)"?  Then repost the traceback.

You might also want to look at adjusting one of the `dill.settings`, although that's probably better determined after seeing the enhanced traceback.

**Comment by pyrytakala** [comment]
Yes, I agree, given that by modifying the dotdict this can be circumvented, this is more an issue with dotdict
