### ISSUE TITLE
Cannot import from source without building

### ISSUE THREAD

**Issue by asmodehn** [uqfoundation/dill#136]
I cannot import the python source directly without building :
"""First run 'python setup.py build' to build dill."""

I was curious if there any specific reason to enforce this ?

**Comment by mmckerns** [comment]
It's primarily because `setup.py` does some work to generate code and the like before the install.  There's also some `import` code inside of `dill` that has expectations on how things are ordered… and working from source (i.e. the  `import` path is now different) might not work as expected.  At this point, it's speculation that it would have issues, however.

Do you have a compelling reason that it **should** work?

**Comment by asmodehn** [comment]
Basically I would like to use it in a ROS package that I am developing at
the moment ( I need to serialize complex python objects for multiprocess
code )

ROS is based on ubuntu packages, and since there is no ubuntu package for
it I would have to either use it from source and/or build with catkin ( ROS
build toolchain ).
Both usecases somehow assume that a python package should be usable from
source and don't really support fancy setup.py

I m currently trying to find a hack/workaround to build it with catkin in
my fork, but without success so far...

Being able to use dill from source would just make things much easier :-)
But I have no idea what changes are needed on dill to get that working and
if it is suitable or not.

However I can say that I think the import should not be a problem, most
python package I work with work both from install space or from source.
The main problem for me now is the generated code ( that ends up in wrong
place etc. ) But I m still in the middle of my experimentation with dill...

Anyway I ll keep trying to hack around the setup.py for a few days in case
i can get it to work with catkin...
Otherwise, and if I cannot use it directly from source, I'll probably have
to find another solution to my serialization problem...

**Comment by mmckerns** [comment]
The `setup.py`in `dill` is not terribly "fancy". All you should have to do is remove the line at the beginning of `setup.py` that raises the error, and it should be usable from source.  If you do so, I can't guarantee that it will have 100% functionality, however.  Feel free to experiment, and if you find anything worthwhile, please submit a pull request.  If you fins you can't use `dill`, there's always `cloudpickle`, which is similar.

**Comment by asmodehn** [comment]
I tried a few things to build it for ROS with catkin, unsuccessfully, catkin's support of python packages is very limited.
I had a quick look at cloudpickle ( thanks for the pointer ), but I ll stick with dill for now I think...
So I m gonna have a go at modifying dill to run from source when I get some time, it should be doable without too much trouble. I'll send some PR when I get something working.

**Comment by mmckerns** [comment]
@asmodehn: Ok, great.  I don't think there will be too much to edit to run from source.  There's just not been a use case that it's been needed for before.

**Comment by asmodehn** [comment]
I ran the tests and had a few errors, but not much time to investigate right now.
Sorry, but I ll leave that aside for now, I was able to use tblib to just transfer the traceback for developer use, which is enough for my main usecase right now. I ll keep dill in mind if I need to serialize more though.
