### ISSUE TITLE
How a user/developer should run the tests?

### ISSUE THREAD

**Issue by asmodehn** [uqfoundation/dill#138]
The setup.py/README/info.py documents how to build and install.
It would also be useful to document how to run the tests, especially since python has a lot of different ways to implement and run tests.

**Comment by matsjoyce** [comment]
```bash
for i in tests/*.py; do python $i; done
```

works.

**Comment by mmckerns** [comment]
The plan is to add the ability to run the tests from the module itself, so some of these (https://docs.python.org/devguide/runtests.html) types of calls also work.  However, for now, I also run the tests as @matsjoyce suggests above.
