### ISSUE TITLE
dumping lambdas can give 2 different results

### ISSUE THREAD

**Issue by simonzack** [uqfoundation/dill#141]
This is a strange issue I've encountered while using dill.

If the following code is put in a python file, the first run and all other runs will produce output which differ by 1 byte:

    dill.dumps(lambda: None)

This bug affects it's use to hash lambda arguments to function calls as it can be different between runs: https://github.com/joblib/joblib/pull/240

I've tracked this down to dill's `save_code` which calls `marshal.dumps` which produces the anolomous byte, but am not sure about the cause of this difference. I'm on python 3.5 windows 7 x64. Perhaps something other than marshal can be used, or it's output can be parsed to kill this difference?

**Comment by simonzack** [comment]
Another related thing is that lambda saves the file path, line and row number it's defined. This conflicts with it's use as an argument hash as well.

**Comment by simonzack** [comment]
This can be done the way of cloudpickle:

https://github.com/cloudpipe/cloudpickle/blob/master/cloudpickle/cloudpickle.py#L142

**Comment by mmckerns** [comment]
Changing the registered function for `CodeType` to not use `marshal` doesn't seem to cause any issues for any known cases.  So, even though this is a rare case, it seems that it's an improvement: 9d2998072e4634945740a2df38812ed3f7f0f3a3.

Does this fix your issue? (you didn't post code I can run, aside from what you described above)

**Comment by simonzack** [comment]
Since it works in cloudpickle I'm guessing that fixes it, thanks!

**Comment by simonzack** [comment]
Hmm I just tried:

    dill.dumps(lambda: None)

and it's giving:

    _pickle.PicklingError: Can't pickle <class 'code'>: it's not found as builtins.code

**Comment by simonzack** [comment]
My bad, used the wrong version.
