### ISSUE TITLE
dill import side-effects inconsistent under Python 2 and Python 3

### ISSUE THREAD

**Issue by lesteve** [uqfoundation/dill#148]
Reading https://github.com/uqfoundation/dill/issues/53 and https://github.com/uqfoundation/dill/issues/146, it seems like importing dill has side-effects on the pickle module. My understanding is that this side-effect can be reverted by using `dill.extend(False)`.

First one question: since there is a way to revert the dill import side-effect, why isn't it reverted by default? I would argue that such a side-effect makes for a slightly surprising behaviour. In my particular case, it took me some time to figure out why pickle was suddenly able to pickle lambda functions.

Then the bug report: the dill import side-effect seems to happen in Python 2 but not Python 3.

``` python

import pickle

def pickle_lambda(info):
    try:
        pickle.dumps(lambda: 2)
        print('Succeeded in pickling lambda ' + info)
    except Exception:
        print('Failed to pickle lambda ' + info)

pickle_lambda('before dill import')
import dill
pickle_lambda('after dill import')
```

Python 2 output (I tried 2.6 and 2.7):

```
Failed to pickle lambda before dill import
Succeeded in pickling lambda after dill import
```

Python 3 output (I tried 3.4. and 3.5):

```
Failed to pickle lambda before dill import
Failed to pickle lambda after dill import
```

**Comment by matsjoyce** [comment]
I think its because by default in python 2, pickle used python classes that dill can affect. In python 3, pickle does not use the python classes, instead it uses a C backend, so normal pickling is not affected by dill. The dill-affected python part is only used if the C cannot be imported.

**Comment by lesteve** [comment]
OK thanks for your answer.

Out of interest, what about the question I was asking earlier:

> since there is a way to revert the dill import side-effect, why isn't it reverted by default?

**Comment by matsjoyce** [comment]
You'll have to ask @mmckerns for that, he's in charge.

**Comment by mmckerns** [comment]
The reason the `pickle` overloading happens by default is: (1) historical, this is the design choice I made before I had a `revert` capacity, and (2) functional, to use `dill` in a parallel library, you have to replace `pickle` with `dill`… this is not often possible, but bootstrapping in the `dill` registry to `pickle` can enable libraries you don't want to fork to now work, and (3) it's "easier" than importing `dill` then having to remember to "bootstrap" `pickle`.

So, again, why overload `pickle` by default?  Eh… mostly for historical reasons. 

@matsjoyce is also correct, Trying to pickle a `lambda` with `pickle` after an `import dill` will yield a `_pickle.PicklingError`… and `_pickle` is the C version of `pickle`.  `dill` only overloads the python version of `pickle`.

**Comment by lesteve** [comment]
> So, again, why overload pickle by default? Eh… mostly for historical reasons.

Would you consider changing the default behaviour to require users to explicitly call `dill.extend(True)` if they want the pickle registry to be modified?

> @matsjoyce is also correct, Trying to pickle a lambda with pickle after an import dill will yield a _pickle.PicklingError… and _pickle is the C version of pickle. dill only overloads the python version of pickle.

Just curious, that means that there is no way to "bootstrap" `pickle` in Python 3, right ? I am thinking in the context of your bullet point (2) above, where you have a third party library that you don't want to change.

**Comment by mmckerns** [comment]
@lesteve: Yes.  Admittedly, It's been considered several times, but that side has lost to date.  As to point (2), I expect that it could be done for python3.x, it just has not been in full.  I actually haven't tested the extent of how much this "bootstrapping" works or doesn't in python3.x.  You could possibly test it in a fairly simple way by slightly modifying `test_objects.py`, and seeing which objects `pickle` is able to serialize with and without the `import dill`.  Even in python3.x, `pickle` does give a mechanism for adding new types to the `dispatch_registry` (as provided in `copyreg`).  I remember that I had to use the current mechanism in `dill` (instead of `copyreg`) because `pickle` explicitly forbade (or at least used to) the pickling of certain types and/or I needed to *replace* certain types. If that's no longer the case, then one could, in theory, simply use copyreg to register all the `dill` types.  I don't know, it's worth exploration, and it's been a while since I have explored down that path.

**Comment by mmckerns** [comment]
Just to note, in case it wasn't clear from the above… `dill` bootstrapping (i.e. `extend` on import) does work in python3.x -- however, it only affects `pickle._dump`, `pickle._dumps`, and similarly for loading.  In 3.x, these functions replace `dump`, `dumps`, etc if `_pickle` (the C version) doesn't work for some reason.  The functions `dump` and friends come from `pickle._Pickler`, which **is extended** by `dill` in python3.x.  What is currently not done, is copying the dispatch table from the `_Pickler` into the `Pickler`… which would be the equivalent of copying the dispatch table from `pickle` to `cPickle` in python2.x.

**Comment by mmckerns** [comment]
The historical 2.x behavior of overloading pickle upon import of `dill` no longer is relevant, as 2.7 is no longer supported.  I'm closing this.
