### ISSUE TITLE
Dill fails on classes with __slots__

### ISSUE THREAD

**Issue by disconnect3d** [uqfoundation/dill#152]
By default dill fails to serialize objects/classes that contains `__slots__` (more about slots [here](https://github.com/yasoob/intermediatePython/blob/master/__slots__magic.rst)):
```python
class A(object):
    __slots__ = ['a']

import dill
dill.dumps(A)
```

with `RuntimeError: maximum recursion depth exceeded` - as far as I understand, it somehow tries to pickle `a` and think that it requires `A` and so tries to pickle it once again and so on.

`pickle` for example can do it.

The problem can be solved by passing `byref=True` to `dumps`, however I believe this shouldn't make any difference in such case.

If that can't be fixed anyhow, there should be at least an error similar to the one from `pickle` when trying to `pickle.dumps(A())`:
```TypeError: a class that defines __slots__ without defining __getstate__ cannot be pickled```

I've used dill 0.2.4 and Python 2.7.10.

**Comment by matsjoyce** [comment]
I've found a way around the recursion. Can you try #153?

**Comment by mmckerns** [comment]
also added test in 6149c3f52266d68a4aa75474b7da217b336dcfa6

**Comment by disconnect3d** [comment]
Yeah that works fine now, thanks.

You might think of extending the test with actually checking if the slots variable can be used after unpickling:

```python
# test slots
class X(object):
    __slots__ = ['x']
    def __init__(self, x):
        self.x = x

value = 123
x = X(value)

assert dill.pickles(X)
assert dill.pickles(x)
assert dill.pickles(X.x)
assert dill.loads(dill.dumps(x)).x == value
```

**Comment by mmckerns** [comment]
@disconnect3d: sure.  I'll do that.
