### ISSUE TITLE
dump/load missing kwds/args for python3.x pickle compatibility

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/dill#156]
Add additional keywords/arguments for `dump`/`load` in python3 (i.e. `*, fix_imports=True, encoding='ASCII', errors='strict'`).

**Comment by cc786537662** [comment]
hello @mmckerns 

for now(2017-10-6  , dill version 0.2.8.dev0）:
there is still no 'encoding' args  in  dump/load with  python3.6，did i miss something? or that's just what it is.

thank  you for your excellent job man.

**Comment by matsjoyce** [comment]
@cc786537662 No, the signature [as of right now is](https://github.com/uqfoundation/dill/blob/master/dill/dill.py#L229):
```py3
def dump(obj, file, protocol=None, byref=None, fmode=None, recurse=None):
```
