### ISSUE TITLE
dump fails with TypeError

### ISSUE THREAD

**Issue by tttthomasssss** [uqfoundation/dill#165]
I am calling `dill.dump(obj, file)`, where `obj` is a very large python `dict` of `dicts` and `file` is an open file handle, and receive the following crashlog (I am using `python 3.4.3` and `dill 0.2.5`):

```
File "/lustre/scratch/inf/thk22/code/apt-research/src/ukwac_preprocessing/preprocess.py", line 254, in cache_filter_concatenation
    vector_utils.save_vector_cache(ukwac_vectors, vector_out_file=filtered_vector_file)
  File "/lustre/scratch/inf/thk22/code/apt-toolkit/apt_toolkit/utils/vector_utils.py", line 232, in save_vector_cache
    dill.dump(vectors, data_file)
  File "/mnt/nfs2/inf/thk22/.virtualenvs/nlp/lib/python3.4/site-packages/dill/dill.py", line 238, in dump
    pik.dump(obj)
  File "/cm/shared/apps/python/3.4.3/lib/python3.4/pickle.py", line 412, in dump
    self.save(obj)
  File "/cm/shared/apps/python/3.4.3/lib/python3.4/pickle.py", line 479, in save
    f(self, obj) # Call unbound method with explicit self
  File "/mnt/nfs2/inf/thk22/.virtualenvs/nlp/lib/python3.4/site-packages/dill/dill.py", line 837, in save_module_dict
    and obj is getattr(_import_module(obj['__name__'],True), '__dict__', None):
  File "/mnt/nfs2/inf/thk22/.virtualenvs/nlp/lib/python3.4/site-packages/dill/dill.py", line 729, in _import_module
    return __import__(import_name)
TypeError: __import__() argument 1 must be str, not dict
```

I traced down this error a little bit and the problematic line is: ` elif '__name__' in obj and obj != _main_module.__dict__ and obj is getattr(_import_module(obj['__name__'],True), '__dict__', None):` (line 822-823 in dill.py, line numbers are different in the crashlog because i've added a bunch of log statements throughout the file for debugging), the actual crash happens in the fn `_import_module()`. However the problem is that `__name__` happens to be a key in my `dict` and thus the wrong branch is executed in `save_module_dict()` with `_import_module()` not receiving the `str` it expects (but a `dict`). I can't really change the name of the key or remove it (at least not at that processing stage) as the `dict` contains word counts over a large NLP corpus.

I am well aware that this issue is probably an absolute border case, however I would be grateful for some suggestions as to how I can workaround the problem in my local `dill` copy without breaking any of the functionality.

**Comment by matsjoyce** [comment]
Change the line to:
```py
elif '__name__' in obj and obj != _main_module.__dict__ and isinstance(obj['__name__'], str) and obj is getattr(_import_module(obj['__name__'],True), '__dict__', None):
```
@mmckerns I'm not sure how useful adding this to dill is, given that its quite an edge case and it makes the code more complicated (`__name__` is a builtin name on some objects, so shouldn't be used).

**Comment by tttthomasssss** [comment]
That sounds simple enough, thanks very much! I know its an absolute edge case, it didn't happen on the other 5 corpora I'm using, so a local fix will certainly be good enough.

**Comment by matsjoyce** [comment]
I'd probably blame the "bug" on whatever library you're using, as `__name__` tends to be a name, not a data-storing attribute.

**Comment by mmckerns** [comment]
@matsjoyce: total corner case, and probably should never be done… so `dill` shouldn't need to handle it.  However, adding the fix is probably innocuous. Hence: 5e664956587ff4debfa84a15a9d6a868eee3a1ac.  Thanks.
