### ISSUE TITLE
dill_bugs breaks in pypy on save_wrapper_descriptor

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/dill#175]
As reported by @peque:

```
$ pypy tests/dill_bugs.py 
True: <type 'str'>, __main__
True: <type 'function'>, <function _method at 0x0000000002534ea8>
Traceback (most recent call last):
  File "tests/dill_bugs.py", line 42, in <module>
    print ("%s: %s, %s" % (dill.pickles(i), type(i), i))
  File "/media/src/dill/dill/dill.py", line 1304, in pickles
    pik = copy(obj, **kwds)
  File "/media/src/dill/dill/dill.py", line 206, in copy
    return loads(dumps(obj, *args, **kwds))
  File "/media/src/dill/dill/dill.py", line 256, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "/media/src/dill/dill/dill.py", line 249, in dump
    pik.dump(obj)
  File "/usr/lib64/pypy-4.0.1/lib-python/2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib64/pypy-4.0.1/lib-python/2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/media/src/dill/dill/dill.py", line 1008, in save_wrapper_descriptor
    pickler.save_reduce(_getattr, (obj.__objclass__, obj.__name__,
AttributeError: generic property has no __objclass__
```

**Comment by Peque** [comment]
Are there any updates on this matter? :blush:

**Comment by Peque** [comment]
Hi Mike, is there any update on this matter? :innocent:

**Comment by mmckerns** [comment]
@Peque: if there were, I'd update this ticket.  I believe this is all that is needed for you to have the compatibility you want, but I have not had time to resolve this issue with the `wrapper_descriptor` just yet.

**Comment by Peque** [comment]
@mmckerns I understand. Thanks a lot for taking the time to reply anyway! :blush:

**Comment by mmckerns** [comment]
I have opened a ticket on `pypy` at: https://bitbucket.org/pypy/pypy/issues/2464/getset_descriptor-cannot-access

**Comment by mmckerns** [comment]
There's now a patch for this in `pypy`.  After some testing against the latest `pypy`, I think this should be able to be closed.

**Comment by mmckerns** [comment]
While it seems the current patch fixes the issue for some cases, it doesn't work in all cases.  Also, there's an error in the pickling that is produced when the descriptors are a `weakref`.  I'm punting the discussion to the `pypy` ticket until it's better suited to come back here.

**Comment by mmckerns** [comment]
While testing with the latest `pypy` (with the patch applied), I've found some other issues for `pypy` compatibility and fixed them in de597c53c98a0c0663ef924de56ba8b1c379d8cf.  Looks like now only the remaining issue is that descriptors for built-ins in `pypy` don't have an `__objclass__` attribute - -and that would require a change to `pypy`.  Otherwise, I don't seem any further issues.

**Comment by mmckerns** [comment]
Another iteration with `pypy`. With, 5aa2636026aa99e1e8b2e56e8ad3f9ab3c0187c1, looks like only the descriptor for `__doc__` is missing the `__objclass__` attribute.  When this is patched in `pypy`, then I think this ticket can close.

**Comment by Peque** [comment]
Great news. I am subscribed to the Bitbucket's issue, following your discussion. :+1:

**Comment by mmckerns** [comment]
I'm closing this, as it is fixed in the `pypy` nightly builds… and should roll into latest release soon enough.

**Comment by irmen** [comment]
By the way it looks like the recent dill release fixed the problems I was having with Pyro4 where it didn't work on pypy. Somehow I didn't even have to install the latest pypy nightly with the fixes on their end.

**Comment by mmckerns** [comment]
@irmen: I had some iterations with the `pypy` developers.  `pypy` and `dill` both made some tweaks that have hopefully "solved the problem".  I expect you may encounter a case that fails until the `pypy` release it out -- but maybe you won't, and that will be even better.
