### ISSUE TITLE
Can `dill` pickle a function and its dependencies?

### ISSUE THREAD

**Issue by davidbrochart** [uqfoundation/dill#176]
I have a first program `test1.py` which pickles a function and its dependency into a file:
```python
import dill

def bar(x):
    return x + 1

def foo(x):
    return bar(x)

with open('foo.pkl', 'wb') as f:
    dill.dump(foo, f)

with open('foo.pkl', 'rb') as f:
    _foo = dill.load(f)

print(_foo(1))
```
Everything works fine and I get the correct result (2). But then if I load the pickled function from a separate program `test2.py`:
```python
import dill

with open('foo.pkl', 'rb') as f:
    _foo = dill.load(f)

print(_foo(1))
```
I get the following error:
```
Traceback (most recent call last):
  File "test2.py", line 6, in <module>
    print(_foo(1))
  File "test1.py", line 7, in foo
    return bar(x)
NameError: name 'bar' is not defined
```
Am I missing something?

**Comment by mmckerns** [comment]
By default, `dill` does not chase down dependencies.  However, if you do want that behavior, you can make `dill` do it by adding the line `dill.settings['recurse'] = True` in `test1.py` after the import.  That will cause `dill` to also pickle the dependencies of `foo` (i.e. `bar`).
