### ISSUE TITLE
Downgrade logging level from info to debug

### ISSUE THREAD

**Issue by rs2** [uqfoundation/dill#187]
Pickling an object with the logging level of root logger set to info results in lots of unreadable text of the following form:

```
T1: <class 'classmethod'>
D2: <dict object at 0x00000000>
T1: <class 'OSError'>
D2: <dict object at 0x00000000>
```

Please consider downgrading the level of logging to `debug` in e.g. https://github.com/uqfoundation/dill/blob/master/dill/dill.py#L814

**Comment by mmckerns** [comment]
I totally realize what I have implemented is a bit odd, and unexpected verbosity may occur if logging level is set to `info`... but to me, it's the correct behavior.  Those messages are not debug messages, they are "info" from the `dill.detect.trace` method.  (as I noted in your PR).

**Comment by mmckerns** [comment]
I'm going to close this... but feel free to continue the discussion in the PR you've submitted.

**Comment by matsjoyce** [comment]
I'm not sure how this is an issue anyway, as the `__init__` module sets the level of the dill logger to waning. @rs2 How are you setting your logging up, because unless you set dill's logger to info yourself, there shouldn't be a clash?
