### ISSUE TITLE
`bin/unpickle.py` shadows modules

### ISSUE THREAD

**Issue by alexhsamuel** [uqfoundation/dill#189]
If dill is installed (with pip, conda, or plain `setup.py install`) into a Python environment, the `bin/unpickle.py` can shadow a Python module. This doesn't occur interactively, but does occur if I run another script from the `bin` directory, as Python adds the scripts dirname (in this case, the environment's `bin`) to the front of `sys.path`.

For example, suppose I do,

```
$ conda create -n test python=2.7 pytest dill
$ source activate test
$ mkdir myproject
$ cat > myproject/unpickle.py
data = "Hello, world!"
$ export PYTHONPATH=$(pwd)/myproject
$ python -c 'from unpickle import data'
```

So far so good. But if I'm running Python via some script in `bin`, for example `bin/py.test`,

```
$ mkdir myproject/tests
$ cat > myproject/tests/test_unpickle.py
from unpickle import data  # same import as interactive session
$ py.test myproject/tests/test_unpickle.py 
============================= test session starts ==============================
platform darwin -- Python 2.7.12, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
rootdir: /Users/alex/tmp/dill, inifile: 
collected 0 items / 1 errors 

==================================== ERRORS ====================================
______________ ERROR collecting myproject/tests/test_unpickle.py _______________
ImportError while importing test module '/Users/alex/tmp/dill/myproject/tests/test_unpickle.py'.
Original error message:
'cannot import name data'
Make sure your test modules/packages have valid Python names.
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.17 seconds ============================
```

This fails because under `.../bin/py.test`, the `bin` directory is in my path and dill's `unpickle.py` gets imported instead of mine.

In general, seems like a bad idea to install anything with a `.py` extension into `bin`, for this reason. Would it be possible to rename `unpickle.py` to just `unpickle`, or maybe `dill-unpickle`? Likewise for `get_objgraph.py`, though this seems less likely to collide with someone else's module.

**Comment by mmckerns** [comment]
done in 584a89b0de2fec6266b1ddcc4f9d0defe6769a20

**Comment by mmckerns** [comment]
Arg... Windows.  I think just deleting the file extension will cause problems on windows.  I will have to check it when I have a windows test install, so for now I'm reverting.  Although I will change `unpickle` to `dill_unpickle` so collisions are less likely.  See c53f9a023f98c898a7a11a7dfc9a4fb8cd628f8e.

**Comment by alexhsamuel** [comment]
In any case, thank you for dealing with this...!
