### ISSUE TITLE
Problem with scons

### ISSUE THREAD

**Issue by arquer** [uqfoundation/dill#193]
Hello, I am not sure if this is a problem with dill or with scons.

The case is that when I import SCons packages and after I import dill python crashes with:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/p/common/python/2.7.8/lib/python2.7/site-packages/dill-0.2.5-py2.7.egg/dill/__init__.py", line 26, in <module>
    from .dill import dump, dumps, load, loads, dump_session, load_session, \
  File "/p/common/python/2.7.8/lib/python2.7/site-packages/dill-0.2.5-py2.7.egg/dill/dill.py", line 371, in <module>
    class Pickler(StockPickler):
  File "/p/common/python/2.7.8/lib/python2.7/site-packages/dill-0.2.5-py2.7.egg/dill/dill.py", line 373, in Pickler
    dispatch = MetaCatchingDict(StockPickler.dispatch.copy())
AttributeError: 'builtin_function_or_method' object has no attribute 'dispatch'
```

However if I import dill, and then Import scons packages, everything seems to work fine...

To replicate run:
```
from SCons.Builder import Builder
from SCons.Builder import is_a_Builder
from SCons.Defaults import Copy
from SCons.Script import AddOption, GetOption, Main, Help
from SCons.Variables import *
from datetime import timedelta
```

and then:

`import dill`

Reverse the order and nothing should break.

I am running:
 Python: 2.7.8
 Scons: 2.5
 Dill: 0.2.5

**Comment by matsjoyce** [comment]
See https://github.com/azatoth/scons/blob/73f996e59902d03ec432cc662252aac5fb72f1f8/src/engine/SCons/compat/__init__.py#L167-L173
Basically SCons renames pickle to point to cPickle, while dill need the original pickle. I think the only solutions are import dill first or complain at SCons.

**Comment by mmckerns** [comment]
Yes, `SCons` points `pickle` to `cPickle`, it will hamper the functionality of `dill`...

 I can think of a workaround that could be used within `dill`... basically, to populate the pickle registry of `cPickle` with  all objects in the registry of `pickle`.  But, I don't think `dill` should do that... although doing so might also be a potential solution for #148.

@arquer: As (I think) solving #148 should handle this issue, is there a reason to keep this issue open?

**Comment by mmckerns** [comment]
Please reopen this issue if you feel it should be handled otherwise than as suggested above.
