### ISSUE TITLE
Cross-Python-Version Serialisation?

### ISSUE THREAD

**Issue by cathalgarvey** [uqfoundation/dill#194]
Hi folks,

I've used Dill happily a few times, so thank you for providing this great tool. However, the question has arisen at work; can Dill serialise and deserialise across python versions? Pickle explicitly can't/doesn't, so inter-version compatibility can be an issue. If dill can solve this, it'd be a huge help to us.

In particular, we're only looking at Python versions 3.3+ - we'd like to know if we can design something in 3.5, and then run it in 3.3, or 3.6. Obviously, with the caveat that the source code should run equally well; packages installed, environment configured correctly, etcetera.

I tried looking through the docs, figuring that when compared to Pickle, this would be an advertised feature or a shared warning, but I didn't find anything

Thank you!

**Comment by matsjoyce** [comment]
I think it comes under shared warning, as dill does serialise bytecode, so if anything, dill is more sensitive to versions than pickle. However, depending on what your doing and how similar the versions are, it might work. YMMV.

**Comment by cathalgarvey** [comment]
OK, that gives me the answer I need. Thanks for the really quick answer!

**Comment by mmckerns** [comment]
One comment I'd make is that `dill` selects a default pickle protocol that is the same across all python versions, while python's `pickle` module selects different default protocols for different versions of python.  So, `dill` has a better chance of working, by default, but is no more capable or less capable than `pickle` for pickling across versions of python.
