### ISSUE TITLE
Python 3.5 thinks there are resource-leaks in dill

### ISSUE THREAD

**Issue by ankostis** [uqfoundation/dill#210]
Whenever I import dill I get this annoying warning message:

- dill-version: 0.2.5

  ```
  py.warnings:D:\Apps\WinPython-64bit-3.5.3.0Qt5\python-3.5.3.amd64\lib\site-packages\dill\dill.py:168: ResourceWarning: unclosed file <_io.BufferedReader name='nul'>
    BufferedReaderType = type(open(os.devnull, 'rb', buffering=-1))
  ```

- dill-version: 0.2.6

  ```
  py.warnings:D:\Apps\WinPython-64bit-3.5.3.0Qt5\python-3.5.3.amd64\lib\site-packages\dill\dill.py:167: ResourceWarning: unclosed file <_io.BufferedRandom name='nul'>
    BufferedRandomType = type(open(os.devnull, 'r+b', buffering=-1))
  ```

**Comment by mmckerns** [comment]
You are just doing a `import dill`, correct?  I'm not seeing these warning (with the latest `dill` and latest `3.5.x`) -- on a macOS.  I see you are using windows... so I'll have to check if that makes any difference for me.

**Comment by matsjoyce** [comment]
It's just that we open `/dev/null`, and then discard the file handle without closing it first. Should be easy to fix.

**Comment by ankostis** [comment]
If eventually is more difficult to solve, 
there is what you want on `subprocess.DEVNULL` for python 3.3+ , so somthing like this would not cause any warnings:

    import subprocess as sb

    BufferedReaderType = type(getattr(sb, 'DEVNULL', open(os.devnull, 'rb', buffering=-1)))

**Comment by mmckerns** [comment]
Just tested this on windows after applying #220.  Looks like there is no longer a warning.

**Comment by ankostis** [comment]
Is it possible to have a new release now that this has been solved?

**Comment by mmckerns** [comment]
I'm planning for a release by the end of June.

**Comment by ankostis** [comment]
The in-flight changes seem to worth a new release.
Besides, with `twine`, the release-procedure boils down simply to this:

    python setup.py sditst bdist_wheel       ## Build sources and whl into ./dist/ dir
    twine upload -si <gpg-user> dist/*       ## Release built wheel

**Comment by mmckerns** [comment]
Yes, I know `twine`.  `dill` uses a similar automated release process.
