### ISSUE TITLE
Can't pickle loggers on python 3

### ISSUE THREAD

**Issue by jlorince** [uqfoundation/dill#212]
I recently upgraded from python 2 to 3, and have been having issues with some code I wrote (using pathos multiprocessing). As far as I can tell, the root of the problem has to do with pickling a logger.

Here's a minimal example copied from a [SO question](http://stackoverflow.com/a/29423145/1515212)  that should work and illustrates the problem:

```
>>> class foo:
...    def __init__(self):
...        self.logger = logging.getLogger("package.foo")
... 
>>> import dill
>>> import logging
>>> 
>>> f = foo()
>>> _f = dill.dumps(f)  
>>> f_ = dill.loads(_f)
>>> f_.logger
<logging.Logger object at 0x110b1d250>
```
If I run this code verbatim on my system I  get `TypeError: can't pickle _thread.RLock objects`.

I have dill version 0.2.6.

Any ideas?

**Comment by mmckerns** [comment]
`RLock` types were not supported.  They are, as of 8978ec67781c498c717be55e9ad41a04e2b377a3.

**Comment by jlorince** [comment]
This resolves the issue on Ubuntu, but when attempting it on Window I receive and `UnsupportedOperation: underlying stream is not seekable` error. Is this expected behavrio?

**Comment by mmckerns** [comment]
... I've not seen that before.  Exactly what code produces that error?

**Comment by jlorince** [comment]
Ah that wasn't clear. That's copy-pasting the exact same code I included in the original issue above.

**Comment by jlorince** [comment]
Update: This is bizarre, but I can confirm that the issues only arises when I paste that code into an interactive session. When I run as as script, it works with no issues. this is on Windows Server 2008 running python 3.6 and the latest dev version of dill.

**Comment by mmckerns** [comment]
...and which python version are you seeing the error?  I just tried it on Windows with the latest `dill` and python `2.7.10`, and I don't get any error.

**Comment by jlorince** [comment]
Interestingly, if activate my python 2.7.13 environment, it still works as a script but fails in the interactive shell, but with a different error: `PicklingError: Can't pickle <class 'IPython.terminal.interactiveshell.LenientStrStreamWrapper'>: it's not found as IPython.terminal.interactiveshell.LenientStrStreamWrapper`

BUT, I should have clarified that this is in an IPython shell. I just thought to test in the regular interactive shell, and that works fine. I guess this is an IPython-specifc problem...

**Comment by mmckerns** [comment]
I just tried an interactive session on windows with `3.5.2` and the latest `dill`, and it works.  I did not try an `IPython` shell in either case.

**Comment by jlorince** [comment]
Same here...problem seems isolated to Ipython interactive sessions. Weird.

**Comment by mmckerns** [comment]
uh... new ticket?
