### ISSUE TITLE
Class attributes added at initialization of an instance are not serialized

### ISSUE THREAD

**Issue by edwardreed81** [uqfoundation/dill#215]
This comes from a stackoverflow question: http://stackoverflow.com/questions/42752716/how-to-write-all-class-variables-to-disk-with-dill

If one were to change a class attribute during initialization of an instance of that class, dill does not serialize this class attribute. 

> That to me screams bad coding practice... however, a serializer shouldn't be judgmental, and should handle it.

I tried doing this through something like

    class Basic(object):
        x = 10
        def __init__(self, initial=False):
            super(Basic, self).__init__()
            self.y = 4
            Basic.z = 5

as well as using a metaclass with a custom \_\_call\_\_ to set the class attribute. Both do not serialize properly.

**Comment by matsjoyce** [comment]
See #47. We were discussing this problem, but is kind of got abandoned. @mmckerns do we want to have another go at this?

**Comment by mmckerns** [comment]
@matsjoyce: I think actually, the better reference is issue #42. Yeah, I have a small collection of tickets that we should sort out, and this is one of them (#42 and associated tickets).  Let's try to sort it.

@edwardreed81: I appreciate the ticket, and it is totally a valid issue… however I am closing this ticket as a duplicate of #42.  We likely will, however, use the above code as a test case for #42 as well as some motivation to unstick an old issue.  Can you detail here an example of the custom `__call__` method?
