### ISSUE TITLE
_pickle.PicklingError: Can't pickle <class '__main__.Iris'>: attribute lookup Iris on __main__ failed

### ISSUE THREAD

**Issue by anchenxdy** [uqfoundation/dill#216]
I have a problem when I try to generate a instance from the class in the RDD.map() function.  The version of python is 3.5.2+ and the spark's is 2.1.0.

### Error message:
```python
>>>data = sc.parallelize(irisdata).map(lambda x: x.split(",")).map(lambda x: Iris(x)).toDF()
2017-03-23 21:09:33,794 ERROR executor.Executor: Exception in task 0.0 in stage 32.0 (TID 48)
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 174, in main
    process()
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 169, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 272, in dump_stream
    bytes = self.serializer.dumps(vs)
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 427, in dumps
    return pickle.dumps(obj, protocol)
_pickle.PicklingError: Can't pickle <class '__main__.Iris'>: attribute lookup Iris on __main__ failed

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`
```
### Code:
```python
from pyspark.ml.linalg import Vector,Vectors
class Iris(object):
    def __init__(self, x):
        self.features = Vectors.dense(float(x[0]), float(x[1]), float(x[2]), float(x[3]))
        self.label = x[4]
irisdata = ['5.1,3.5,1.4,0.2,Iris-setosa', \
            '4.9,3.0,1.4,0.2,Iris-setosa', \
            '4.7,3.2,1.3,0.2,Iris-setosa', \
            '4.6,3.1,1.5,0.2,Iris-setosa', \
            '5.0,3.6,1.4,0.2,Iris-setosa']
data = sc.parallelize(irisdata).map(lambda x: x.split(",")).map(lambda x: Iris(x)).toDF()
```
### Some testing:

1. Defining a function to replace the lambda:..., but the same problem show again.
```python
def f1(x):
    y = Iris(x)
    return y
data = sc.parallelize(irisdata).map(lambda x: x.split(",")).map(f1).toDF()
```
2. Without RDD, just use the python's map function, it is ok.
```python
x = sc.parallelize(irisdata).map(lambda x: x.split(",")).collect()
for item in list(map(f1,x)):
    print(item.features, item.label)
```

**Comment by mmckerns** [comment]
I don't think this is a `dill` issue, as I don't think your code is using `dill`.  So, as far as I know, `pyspark` uses `pickle` or `cloudpickle` and not `dill`.  However, if you do want to use `dill` with `pyspark`, there is `pysparkling` (https://pypi.python.org/pypi/pysparkling)... and using it may clear up your serialization issue.  What I suggest is that you open a ticket with `pyspark` or try `pysparkling` and if it fails, open a ticket there -- and CC me or refer to this issue so I can follow the thread.  I'm going to close this... so if I'm incorrect and you are using `dill`, please feel free to reopen it.

**Comment by anchenxdy** [comment]
@mmckerns Thanks for your reply. As you say, my code isn't using dill, so it isn't exactly a dill issue. I define the class in other file and import it, then it work. Thanks again.

**Comment by mmckerns** [comment]
@anchenxdy: Doing exactly that typically makes pickling much easier.  It's a good practice.

**Comment by Yeeef** [comment]
> I have a problem when I try to generate a instance from the class in the RDD.map() function. The version of python is 3.5.2+ and the spark's is 2.1.0.
> 
> ### Error message:
> ```python
> >>>data = sc.parallelize(irisdata).map(lambda x: x.split(",")).map(lambda x: Iris(x)).toDF()
> 2017-03-23 21:09:33,794 ERROR executor.Executor: Exception in task 0.0 in stage 32.0 (TID 48)
> org.apache.spark.api.python.PythonException: Traceback (most recent call last):
>   File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 174, in main
>     process()
>   File "/usr/local/spark/python/lib/pyspark.zip/pyspark/worker.py", line 169, in process
>     serializer.dump_stream(func(split_index, iterator), outfile)
>   File "/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 272, in dump_stream
>     bytes = self.serializer.dumps(vs)
>   File "/usr/local/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 427, in dumps
>     return pickle.dumps(obj, protocol)
> _pickle.PicklingError: Can't pickle <class '__main__.Iris'>: attribute lookup Iris on __main__ failed
> 
> 	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
> 	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
> 	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
> 	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
> 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
> 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
> 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:99)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)`
> ```
> 
> ### Code:
> ```python
> from pyspark.ml.linalg import Vector,Vectors
> class Iris(object):
>     def __init__(self, x):
>         self.features = Vectors.dense(float(x[0]), float(x[1]), float(x[2]), float(x[3]))
>         self.label = x[4]
> irisdata = ['5.1,3.5,1.4,0.2,Iris-setosa', \
>             '4.9,3.0,1.4,0.2,Iris-setosa', \
>             '4.7,3.2,1.3,0.2,Iris-setosa', \
>             '4.6,3.1,1.5,0.2,Iris-setosa', \
>             '5.0,3.6,1.4,0.2,Iris-setosa']
> data = sc.parallelize(irisdata).map(lambda x: x.split(",")).map(lambda x: Iris(x)).toDF()
> ```
> 
> ### Some testing:
> 1. Defining a function to replace the lambda:..., but the same problem show again.
> 
> ```python
> def f1(x):
>     y = Iris(x)
>     return y
> data = sc.parallelize(irisdata).map(lambda x: x.split(",")).map(f1).toDF()
> ```
> 
> 1. Without RDD, just use the python's map function, it is ok.
> 
> ```python
> x = sc.parallelize(irisdata).map(lambda x: x.split(",")).collect()
> for item in list(map(f1,x)):
>     print(item.features, item.label)
> ```

Hi there,
I encountered this problem too today, and fixed it as you suggested.
However, I am wondering what the reason behind this pickle error issue. Do you have any idea?

**Comment by mmckerns** [comment]
@Yeeef: The traceback says that the `lookup` attribute is not serializable with `pickle`.
