### ISSUE TITLE
Issue deserializing dill on scikit learn pipeline

### ISSUE THREAD

**Issue by gsvijayraajaa** [uqfoundation/dill#226]
Hi,

I had serialized a pipeline using dill. When I try to load it inside a docker container, I get the below error;

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 250, in load
    obj = pik.load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1246, in load_build
    for k, v in slotstate.items():
AttributeError: 'mtrand.RandomState' object has no attribute 'items'
```
Load seems to work on the same environment / host. It doesnt load in docker container running python 2.7.

I am using python2.7 , dill==0.2.5

**Comment by mmckerns** [comment]
Can you post a minimal test code that reproduces the above error?

Also, am I understanding correctly that the pipeline serializes with `dill` (using both `dump` and `load` on the same resource), but when you `dump` from the first instance, then `load` in a `docker` instance, it fails?  If that's not the case, please explain... or better, provide minimal code that demonstrates it.

**Comment by mmckerns** [comment]
@gsvijayraajaa: Is this still an issue for you?  If not, close the ticket. If so, can you post some minimal test code that reproduces your error?  Also, can you give me the full list of dependencies for both your system that produced the pickle and the system you are trying to unpickle to?  There can be issues going from say linux to windows, or from 2.7 to 3.6.

**Comment by mmckerns** [comment]
I'm going to close this due to lack of response to the above questions.  Please reopen if it's still an issue for you.
