### ISSUE TITLE
Error unpickling stored function on 0.2.7

### ISSUE THREAD

**Issue by davidstults** [uqfoundation/dill#232]
I don't have proof code for this yet, because I am experiencing this through several layers, including SQLAlchemy (we are storing code snippets in postgresql which have been pickled, and SQLAlchemy is handling the pickling part for us).  I'll keep working on that, but fundamentally it boils down to this:

At dill.py:1367, this new line breaks things for us:
`if not IS_PYPY: pickler.clear_memo()`

Comment it out and everything is okay.  The error manifests as a pretty extensive traceback, but what it boils down to is:

```
...
  File "/home/stultsd/py/lib/python3.6/site-packages/dill-0.2.8.dev0-py3.6.egg/dill/dill.py", line 297, in loads
    return load(file)
  File "/home/stultsd/py/lib/python3.6/site-packages/dill-0.2.8.dev0-py3.6.egg/dill/dill.py", line 286, in load
    obj = pik.load()
  File "/home/stultsd/py/lib/python3.6/site-packages/dill-0.2.8.dev0-py3.6.egg/dill/dill.py", line 444, in find_class
    return StockUnpickler.find_class(self, module, name)
ModuleNotFoundError: No module named 'CodeType'
```

At the point of this traceback, module='CodeType' and name='_create_function'.  I think the module should really be 'dill.dill'.

As I mentioned, I will keep trying to produce a snippet of code that reproduces this.  I'm hoping you recognize this error as something you've run across before.

**Comment by Peque** [comment]
@mmckerns Adding a comment here as it is probably related.

This code used to work just fine with `0.2.6` but fails with `0.2.7`:

```python
from osbrain import run_nameserver
from osbrain import run_agent


def set_method():
    """
    Set new methods for the agent.
    """
    def one(agent):
        return 1

    def two(agent):
        return 2

    ns = run_nameserver()

    a0 = run_agent('a0')

    a0.set_method(one, two)
    assert a0.one() == 1
    assert a0.two() == 2

    ns.shutdown()


if __name__ == '__main__':
    set_method()
```

Fails with:

```
Traceback (most recent call last):
  File "dillbug.py", line 43, in <module>
    set_method()
  File "dillbug.py", line 21, in set_method
    a0.set_method(one, two)
  File "/cache/miniconda/envs/dillbug/lib/python3.6/site-packages/Pyro4/core.py", line 186, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/cache/src/osbrain/osbrain/proxy.py", line 159, in _pyroInvoke
    methodname, args, kwargs, flags, objectId)
  File "/cache/src/osbrain/osbrain/proxy.py", line 204, in _remote_call
    flags=flags, objectId=objectId)
  File "/cache/miniconda/envs/dillbug/lib/python3.6/site-packages/Pyro4/core.py", line 470, in _pyroInvoke
    raise data
ModuleNotFoundError: No module named 'obj_72beac03721e4240af1fcc431c5af57d'
```
Note that it will fail only when calling `.set_method()` with two parameters. If I call `.set_method(one)` or `.set_method(two)`, it will work just fine.

Bisecting the problem, Git tells me the error was introduced in 13f82f36e6bd6575af41223c8919901ecb260aeb, which might coincide with what @davidstults is mentioning.

Have not dug further, so I do not have a test case that not depends on an external package (`osbrain` in this case), nor I know why exactly is this failing.

**Comment by Peque** [comment]
@davidstults Might be interested in reading about [GitHub's Markdown syntax for quoting code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code) (to make your issue a bit more readable. :blush:

**Comment by mmckerns** [comment]
@Peque, @davidstults: does the fix for #234 fix your issues?  I will test code from @Peque in a vm, but I can't test what you are seeing @davidstults.  Fixing this and #234 probably warrants a patch release, so let me know.

**Comment by davidstults** [comment]
@mmckerns: Yes, that does fix the my issue.  Thanks!

**Comment by Peque** [comment]
@mmckerns It seems it is fixed for me too. Is it hard to add a test to prevent this from happening again in the future? :innocent:

**Comment by mmckerns** [comment]
I've added the test from #234.  It's my guess that what happened is that this is related to the `super` bug in python (see #75), and the behavior of recent releases has changed the behavior and that affected my workaround.

**Comment by mmckerns** [comment]
So... closing this.
