### ISSUE TITLE
PicklingError with custom classes after cloudpickle

### ISSUE THREAD

**Issue by PeterMinin** [uqfoundation/dill#239]
I am getting an error trying to serialize objects of a certain custom class that where previously serialized and de-serialized by [cloudpickle](https://github.com/cloudpipe/cloudpickle) (in practice, they are created by `dask` workers). Here is an example, with some comments below.
```python
import cloudpickle


class A(object):
    pass


class B(A):
    def foo(self):
        super()


NewB = cloudpickle.loads(cloudpickle.dumps(B))
b = NewB()

import dill
dill.dumps(b)
```
This produces an error:
`_pickle.PicklingError: Can't pickle <class '__main__.B'>: it's not the same object as __main__.B`
Full stack trace: [gist](https://gist.github.com/PeterMinin/f962da57b771f18d25eded9d30588764).

The error does not happen in either of the following cases:
- the classes are imported from a module;
- class `B` doesn't use `super()`, i.e. if it's defined like this:
```python
class B(A):
    def foo(self):
        A()
        B()
```

Versions:
python - 3.5.2
cloudpickle - 0.4.0
dill - 0.2.7.1

**Comment by anivegesana** [comment]
Fixed in #443
