### ISSUE TITLE
Exception with parameters serialization fails.

### ISSUE THREAD

**Issue by stuz5000** [uqfoundation/dill#241]
```
class MyException(Exception):
    def __init__(self, a,b):
        pass

import dill
def check_serializable(o):
    dill.loads(dill.dumps(o))

check_serializable(MyException(1,2)) # TypeError
```
gets:
```
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 299, in loads
    return load(file)
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 288, in load
    obj = pik.load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1133, in load_reduce
    value = func(*args)
TypeError: __init__() takes exactly 3 arguments (1 given)
```
For some reason, the ```__init__``` method of Exceptions is used to deserialize them.

Shouldn't ```__new__``` be used?

Dill 0.2.7.1
Python 2.7.

**Comment by matsjoyce** [comment]
One fix is to call `__init__` properly:
```py
class MyException(Exception):
    def __init__(self,a, b):
        super(MyException, self).__init__(a, b)
```
Also make sure that this is in a module, otherwise you will need to do:
```py
class MyException(Exception):
    def __init__(self,a, b):
        super(type(self), self).__init__(a, b)
```

**Comment by stuz5000** [comment]
Thanks I will do this update my init function, however.

```
class MyException(Exception):
    def __init__(self, a, b):
        super(MyException, self).__init__("Bad things")
        #super(type(self), self).__init__(a, b)
        self.a = a
        self.b = b

import dill
def check_serializable(o):
    return dill.loads(dill.dumps(o))

e1 = MyException(1,2)
e2 = check_serializable(e1)
assert e1.a == e2.a
assert e1.b == e2.b
assert e1.message == e2.message
```
... gets the same error.

I'm a little surprised __init__ is ever called by dill. Shouldn't it always only ever call __new__ when deserializing? Is there something special about Exception objects here?

**Comment by matsjoyce** [comment]
That should only give an error if that is not in a module, and the error should be at least somewhat different. Anyway, the "special" thing about exceptions is that they define a `__reduce__` method, and it uses `__init__` to reconstruct the exception. It's part of python itself, so complaints to bugs.python.org I'm afraid.

**Comment by stuz5000** [comment]
Thanks. There's a good discussion about this weirdness here:
https://stackoverflow.com/questions/16244923/how-to-make-a-custom-exception-class-with-multiple-init-args-pickleable

In order to serialize exceptions, you should implement __reduce__. Will close.
