### ISSUE TITLE
Seg faults when using a simple function from cpython3 in pypy3

### ISSUE THREAD

**Issue by RichardoC** [uqfoundation/dill#246]
Hi all,

Currently have an issue when I serialise the following function (made in the cpython interpreter) and then unserialise it using the pypy3 interpreter.

```
def func(i):
  j = i + 1000
  return j

c = dill.dumps(func)
print(c)
b'\x80\x03cdill.dill\n_create_function\nq\x00(cdill.dill\n_load_type\nq\x01X\x08\x00\x00\x00CodeTypeq\x02\x85q\x03Rq\x04(K\x01K\x00K\x02K\x02KCC\x0c|\x00d\x01\x17\x00}\x01|\x01S\x00q\x05NM\xe8\x03\x86q\x06)X\x01\x00\x00\x00iq\x07X\x01\x00\x00\x00jq\x08\x86q\tX\x11\x00\x00\x00./local-client.pyq\nX\x04\x00\x00\x00funcq\x0bK\x0bC\x04\x00\x01\x08\x01q\x0c))tq\rRq\x0e}q\x0fh\x0bNN}q\x10tq\x11Rq\x12.'
```
Then in Pypy3 (loaded the above into a variable c)
```
f = dill.loads(c)
print(f(1))
Segmentation fault
```

For comparison, if I serialise that function in Pypy3 I get a different string
```
b'\x80\x03cdill.dill\n_create_function\nq\x00(cdill.dill\n_load_type\nq\x01X\x08\x00\x00\x00CodeTypeq\x02\x85q\x03Rq\x04(K\x01K\x00K\x02K\x02KCC\x0e|\x00\x00d\x01\x00\x17}\x01\x00|\x01\x00Sq\x05NM\xe8\x03\x86q\x06)X\x01\x00\x00\x00iq\x07X\x01\x00\x00\x00jq\x08\x86q\tX\x07\x00\x00\x00<stdin>q\nX\x04\x00\x00\x00funcq\x0bK\x01C\x04\x00\x01\n\x01q\x0c))tq\rRq\x0ec__builtin__\n__main__\nX\x04\x00\x00\x00funcq\x0fNN}q\x10tq\x11Rq\x12.'
```

Also, the first serialisation won't work in the official Python3 docker container (same issue.)

Any help with this would be appreciated!

**Comment by matsjoyce** [comment]
Put `func` in a module. If it is in `__main__` dill will serialize the bytecode, which is not compatible across versions or distributions of python.

**Comment by RichardoC** [comment]
@matsjoyce Would you mind showing me what you mean?

**Comment by matsjoyce** [comment]
Instead of your code do:
```py3
# module.py
def func(i):
  j = i + 1000
  return j
```
```py3
from module import func
c = dill.dumps(func)
```
It should then be pickled by reference and not cause this problem.

**Comment by RichardoC** [comment]
I've tried your suggestion and have the same issue sadly.

**Comment by matsjoyce** [comment]
What serialization do you get if you apply my suggestion? It should look like `\x80\x03cmodule\nfunc\nq\x00.`

**Comment by RichardoC** [comment]
b'\x80\x03ctest\nfunc\nq\x00.'

**Comment by RichardoC** [comment]
b'\x80\x03ctest\nfunc\nq\x00.'

**Comment by matsjoyce** [comment]
Well, it works fine for me (python 3.6, pypy 5.9). Maybe its an issue with your version of pypy?

**Comment by RichardoC** [comment]
I've the issue if I pickle the function locally (normal cpython install), but then unpickle in the official pypy docker image. Were you using that for your tests?

**Comment by matsjoyce** [comment]
No, I've got the Arch Linux pypy3 package. The source doesn't matter, as it produces the same stream of bytes. What happens if you do `pickle.loads(b'\x80\x03ctest\nfunc\nq\x00.')` without importing dill?

**Comment by RichardoC** [comment]
>>> import pickle
>>> f = pickle.loads(b'\x80\x03ctest\nfunc\nq\x00.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'test'

**Comment by matsjoyce** [comment]
Err, is that pypy? It should look more like 
```py3
>>>> import pickle
>>>> pickle.loads(b'\x80\x03ctest\nfunc\nq\x00.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/pypy3/lib-python/3/pickle.py", line 1587, in _loads
    encoding=encoding, errors=errors).load()
  File "/opt/pypy3/lib-python/3/pickle.py", line 1063, in load
    dispatch[key[0]](self)
  File "/opt/pypy3/lib-python/3/pickle.py", line 1362, in load_global
    klass = self.find_class(module, name)
  File "/opt/pypy3/lib-python/3/pickle.py", line 1416, in find_class
    return getattr(sys.modules[module], name)
AttributeError: module 'test' has no attribute 'func'
```

**Comment by RichardoC** [comment]
Sorry, that time I was running cpython. 

I've rerun the tests today and no-longer get seg faults with either cpython3 or pypy3 docker images. I'm not sure what the issue was but I'll update if I work it out.

Thanks for your help.

**Comment by RichardoC** [comment]
Encountered it again, can confirm that it's due to it pickling the bytecode which isn't cross compatible.
