### ISSUE TITLE
[Python] TypeError: ord() expected a character, but string of length 0 found

### ISSUE THREAD

**Issue by Onimask** [uqfoundation/dill#248]
Hello everyone,

I was given this school project, which goal is to take a picture, apply the RLE method in order to compress it in a binary file (.txt), and save some space. And after struglling with it for 3 days now I'm having troubles.
##
```
def lecture_fichier_compresse():
    f2=open("data2.txt",'rb') #open a binary file in reading mod.
    im3=zeros((962,800,3),dtype="uint8") #create picture which size is 962*800 where every pixels are coded on 3 bytes.
    d=0#pixel counter
    i=0#lign indexation
    j=0#column indexation
    b=ord(f2.read(1))# the informations are read a first time
    a=ord(f2.read(1))
    rouge=ord(f2.read(1))
    vert=ord(f2.read(1))
    bleu=ord(f2.read(1))
    while i!=im3.shape[0]: #as long as it doesn't reach the final lign
        if d<=(a+b*255):
            im3[i,j,0] = rouge
            im3[i,j,1] = vert
            im3[i,j,2] = bleu
            d+=1
            j+=1
            if j==im3.shape[1]:
                j=0
                i+=1
        else: #resets pixel counter and starts reading next informations
            d=0
            b=ord(f2.read(1))
            a=ord(f2.read(1))
            rouge=ord(f2.read(1))
            vert=ord(f2.read(1))
            bleu=ord(f2.read(1))       
    f2.close()
    imsave("Copie_compresse.bmp",im3)
    return im3
imshow(lecture_fichier_compresse());show()
```
##

When I execute the pgrm, it gives me this error written in the tittle. Which is something I feel like impossible to correct, since it is writting itself in hex.
[data2.txt](https://github.com/uqfoundation/dill/files/1585990/data2.txt)

**Comment by Onimask** [comment]
Just to add more informations, a pixel is not coded here using  bytes, like we usually do on format such as .bmp.
Here RLE will search for identic pixel on a same lign, and count how many times it encounters it, by comparing 3 levels colors. Finally it stores in two additional bytes than the RGB ones : a and b.
a is for the number of pixels.
b is the number of 255 stacks of pixels. (Since I'm coding data into 8bits and that pictures are usually larger than 255*255 size)

**Comment by matsjoyce** [comment]
Err, how does this use dill?

**Comment by Onimask** [comment]
In absolutely no way, I'm just new to this site and seek help. If there's a moderator that wish to move this topic to the appropriate location, help yourselves.

**Comment by matsjoyce** [comment]
I think your looking for https://stackoverflow.com/. GitHub is for reporting bugs and sharing code, not help.

**Comment by Onimask** [comment]
Dammit. Thanks for the info.
