### ISSUE TITLE
Dump/Load accross Python versions

### ISSUE THREAD

**Issue by rvernica** [uqfoundation/dill#254]
I'm trying to dump a function using Python 2 and load it using Python 3 or vice versa. I'm not sure that this is possible, but I'm running into issues. Here is an example:
```python
> cat d.py
import dill

def f(x, y):
    return x + y

dill.dump(f, open('f.p', 'wb'), 0)
```
Notice how I use protocol `0` for backward compatibility.
```python
> cat l.py
import dill

f = dill.load(open('f.p', 'rb'))

print(f(1, 2))
```
If the Python version consistent, it works fine:
```bash
> python d.py
> python l.py
3

> python3 d.py
> python3 l.py
3
```
If I mix them, it breaks:
```bash
> python d.py
> python3 l.py
Traceback (most recent call last):
  File "l.py", line 3, in <module>
    f = dill.load(open('f.p', 'rb'))
  File ".../python3.6/site-packages/dill/dill.py", line 288, in load
    obj = pik.load()
TypeError: an integer is required (got type str)

> python3 d.py
> python l.py
Traceback (most recent call last):
  File "l.py", line 3, in <module>
    f = dill.load(open('f.p', 'rb'))
  File ".../python2.7/site-packages/dill/dill.py", line 288, in load
    obj = pik.load()
  File "/usr/lib64/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib64/python2.7/pickle.py", line 1139, in load_reduce
    value = func(*args)
TypeError: code() takes at most 14 arguments (15 given)
```
Version info:
```python
> python
Python 2.7.14 (default, Jan 17 2018, 14:28:32) 
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)] on linux2
>>> import dill
>>> dill.__version__
'0.2.7.1'

> python3
Python 3.6.4 (default, Feb  1 2018, 11:06:09) 
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)] on linux
>>> import dill
>>> dill.__version__
'0.2.7.1'
```

**Comment by matsjoyce** [comment]
It is not possible, as the bytecode used in serializing functions changes between python versions. If you want a function to be accessible to different python versions, put it in a module and dill will just remember its name.

**Comment by rvernica** [comment]
I see, so `protocol=0` in the `dump` function does not help with the bytecode used?

Also, would this work is the Python major version is the same, for example `3.4` and `3.6`?

**Comment by matsjoyce** [comment]
The protocol will not change anything, and compatibility between versions of python is not guaranteed (but might work in some cases).

**Comment by mmckerns** [comment]
@rvernica: There is no guarantee for serialization working between different versions of python.  If you use the same `protocol`, it has a chance of working... but likely will not for many objects.  If the major versions are the same (i.e. 3.4 to 3.6), it is also not guaranteed to work.   Anything that relies on `pickle` (as `dill` does) can only provide the same guarantees that `pickle` itself does, and that is serialization for the same version of python used to `dump` and `load`.  If you want to use something that does guarantee serialization that is supposed to be version agnostic, then try `marshal`.   I second what @matsjoyce said about putting the function into a module, and having `dill` just call the module by reference.  The less you serialize, the more likely something will be able to translate across versions.

There is, however, an alternate.  You can try `dill.source`, which will extract an object's source code, and then store that... and then use the source code to `load` a new object on the other side.  In some cases, it might work.  However, there is no guarantee that it works across versions either.

**Comment by rvernica** [comment]
Thanks for the advice. Putting the function in a module is a no go for my use case.

`dill.source` sounds promising. Could you point me to some examples?

**Comment by mmckerns** [comment]
Something like this:

```
>>> import dill
>>>
>>> def foo(x,y):
...   return x+y
... 
>>> class Bar(object):
...   def zap(self):
...     return foo(self.x,self.x)
...   def __init__(self, x):
...     self.x = x
... 
>>> import dill
>>> 
>>> _foo = dill.source.importable(foo)
>>> _Bar = dill.source.importable(Bar)
>>>                               
>>> b = Bar(4)
>>> _b = dill.dumps(b, byref=True)
>>> 
>>> _b 
'\x80\x02c__main__\nBar\nq\x00)\x81q\x01}q\x02U\x01xq\x03K\x04sb.'
>>> 
>>> del b
>>> del foo
>>> del Bar
>>> 
>>> exec(_foo)
>>> exec(_Bar)
>>> b = dill.loads(_b)
>>> b.zap()
8
>>> 
```

You can see for instances, I'm still relying on `dill.dumps`.  I'm doing that because I know you want to go across versions of python.  Actually, `dill.source.importable` does work for instances of classes, but it doesn't do it by reference, which is probably what you want.

I did put a wrapper around `dill.source.importable` so it dumps to a temporary file.  That's `dill.temp.dump_source`, and it has am accompanying `dill.temp.load_source`.  The docs show exactly how to use it.  I'm not sure that is what you want.

There are a limited number of examples, however, you can check out `test_source.py` in the `tests` directory.  `dill.source` is used in `ppft`, which is like `multiprocessing`, but works with source code instead of serialized objects.

I hope that helps.

**Comment by mmckerns** [comment]
Oh, `importable` attempts to create source that can be saved to a file, so that you can import the desired objects from the newly created file.
