### ISSUE TITLE
struct.error: 'I' format requires 0 <= number <= 4294967295

### ISSUE THREAD

**Issue by drastorguev** [uqfoundation/dill#256]
Hi, I am trying to save a class of gensim.similarities.docsim.MatrixSimilarity, using dill, however I keep getting the following error. I appreciate that the file is very big, but not sure of alternatives...:

```
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pickle.py", line 701, in save_bytes
    self.write(BINBYTES + pack("<I", n) + obj)
struct.error: 'I' format requires 0 <= number <= 4294967295
```

**Comment by matsjoyce** [comment]
If you look at the stack trace, dill doesn't get involved. I think you're just exceeding the limits of pickle (the byte string the had to be serialized is longer than 4GiB). Are you sure there isn't a way of reading the matrix as bytes, and just writing that straight to a file?

**Comment by mmckerns** [comment]
@drastorguev: pickles from `dill` will likely be larger than those from `pickle`, given the module can save both -- unless there's some special case where there's a built-in `dump` function (like there is in `numpy`) that `dill` can leverage.   I don't think `gensim` has a buit-in `dump` function.

I agree with @matsjoyce, you seem to be hitting the size limit for pickle.  If you can't dump a reduced object (i.e. using `__reduce__`), then you might need to consider seeing if you can write to a `h5` file.  I have a pretty robust package to dump objects to HDF5 files, in `klepto`.  There's a less robust package (called `hickle`) that provides dumps to leaner `h5` files than `klepto` produces.  Those are just suggestions... I don't know if they will work for you.  Really big objects are hard to store with `pickle`, and if they can't be dissected, I tend to use another storage format (like `h5`).

**Comment by drastorguev** [comment]
@mmckerns @matsjoyce - you are absolutely right. It was an issue with pickle and not dill. Using `from sklearn.externals import joblib` solved it for me for now. Ideally would want to spend time comparing different options available and their pros and cons, but unable to do so atm due to time constraints.

**Comment by mmckerns** [comment]
@drastorguev: `joblib` is likely using `cloudpickle` by default, btw.  So, if you were doing `dill.dump`, and it was erroring... but works with `joblib`, then `cloudpickle` has added a custom `__reduce__` method for your object.  So that's cool.

**Comment by jgujgu** [comment]
If I wanted to drop in hickle or klepto to reduce large objects, where would you recommend doing so within dill?
