### ISSUE TITLE
deprecation warning with python 3.7(beta)

### ISSUE THREAD

**Issue by irmen** [uqfoundation/dill#257]
Hi, when using dill with the upcoming  Python 3.7 release we get this

dill.py:97: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp

**Comment by matsjoyce** [comment]
It's about time they deprecated that I suppose.

**Comment by mmckerns** [comment]
Thanks for the heads-up. Should be fixed in e05a9b52054fa58a993e6a4697cb042bebf6131e.

@matsjoyce: Thanks for jumping on this.  I didn't see your PR until now, and it seems that it's still failing some tests.  I had one merged in by the time I saw yours.

**Comment by matsjoyce** [comment]
No problem.

**Comment by mmckerns** [comment]
If there are some other PRs you'd like have a race on, I'm game.  :laughing:

**Comment by matsjoyce** [comment]
I'm not sure about the failing tests, as the failing tests have no logs, like they weren't or something. Weird.

**Comment by mmckerns** [comment]
Yeah, I saw some weird stuff going on in the logs too.  I had a `pypy3` failure that is a completely blank log.  The failure I had in `2.6` was odd... it had an error show up that didn't locally when I ran `tox`.  Anyway, I don't know what's up with the blank test logs.
