### ISSUE TITLE
dill fails to pickle classes with super, if byref=False

### ISSUE THREAD

**Issue by phantomas1234** [uqfoundation/dill#26]
I stumbled over a weird case where dill fails to serialize an object that pickle handles fine. I guess the issues has something to do with inheriting from a builtin type and the usage of super in overriding `append`.

```
import pickle
import dill

class InheritsList(list):
    """docstring for InheritsList"""
    def __init__(self):
        super(InheritsList, self).__init__()

    def append(self, obj):
        super(InheritsList, self).append(obj)

obj = InheritsList()
obj.append('string')

# Works
repickled = pickle.loads(pickle.dumps(obj))
print repickled

# Does not work
redilled = dill.loads(dill.dumps(obj))
print repickled
```

It's related to an issue I posted here.
https://github.com/opencobra/cobrapy/issues/72

**Comment by panamantis** [comment]
Strange that for Python 2.7 dill 2.7.1 it doesn't like to load classes with the super statement?  Seems to be related to the above?

`class List_Wrap(list):
    def __init__(self):
        super(List_Wrap,self).__init__()
        return
def test_dill():
    a_dill=dill.dumps(List_Wrap)
    AB=dill.loads(a_dill)
    AB()
    return`

Still getting the error:
   super(List_Wrap,self).__init__()
TypeError: super(type, obj): obj must be an instance or subtype of type

**Comment by mmckerns** [comment]
@panamantis: Thanks for the comment.  I believe it's a duplicate of this or #75 or #56.  Cases that we see failure to serialize in the presence of `super` has been documented in other issues.
