### ISSUE TITLE
clean out cruft from outdated versions of python

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/dill#260]
`dill` still has some code knocking around from the days of python `2.3`/`2.4`, I believe. It supported `2.5` for a long long time, until I basically couldn't test against `2.5` any longer. Now that `2.6` and several versions of `3.x` are unsupported, the code that supports those versions can probably be cleaned out... and that might simplify the logic in several places... and potentially unstick an old ticket or two that were stuck due to a "need" to support older versions. My reasoning for supporting older versions has been that a version of python should be supported until vendors stop shipping systems with that version of python on it.  I've also let that definition slide a bit to keep older versions around if they are typically found on well-maintained institutional cluster computing resources.

So, should `dill` stop supporting some of the older versions of python -- and if so, which versions should still be supported?

**Comment by irmen** [comment]
My $0.02: don't support Python releases that have reached EOL. People that still run these should be able to pin an older compatible dill version in their projects, anyway.   What 'EOL' means can be difficult, the official EOL date from python.org may not be the same as say, a linux distribution's EOL date...

**Comment by mmckerns** [comment]
@irmen: I'm going to kill off some of the older versions.  That's certain.  I think the dividing line should be somewhere between only supporting versions that python has is still releasing updates for (python.org's EOL), and versions that are still supported as system python on large HPC clusters (a linux distribution's EOL).   The latter is what I was previously using as my cutoff, since `dill` is intimately connected to parallel computing on clusters, and that will probably continue to be what the criterion is unless someone convinces me otherwise.  That being said, there currently are some versions by `dill` that need to be EOL'd.

**Comment by hugovk** [comment]
In general, supporting and testing EOL versions is becoming increasingly difficult as other packages and tools drop them. 

EOL Pythons (<=2.6, 3.0-3.3) no longer receive security updates, or any updates, from the core Python team. It is possible to upgrade Python on Linux to a supported version for those who care about security. Those who don't can pin to an older version.

Dropping old ones, particularly Python 2.6 (which has been EOL for over 4 years) and 3.2 (2 years), allows code to be updated to use more modern features of Python.

https://en.wikipedia.org/wiki/CPython#Version_history

Also, EOL versions are also little used.

Here's the pip installs for dill from PyPI for last month:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  70.53% |        223,761 |
| 3.6            |  15.89% |         50,408 |
| 3.5            |   7.16% |         22,715 |
| 3.4            |   6.36% |         20,171 |
| 2.6            |   0.03% |             84 |
| 3.7            |   0.02% |             66 |
| 3.3            |   0.01% |             43 |
| None           |   0.00% |              5 |
| 3.2            |   0.00% |              1 |

Source: `pypinfo --start-date -60 --end-date -30 --percent --pip --markdown dill pyversion`

**Comment by mmckerns** [comment]
@hugovk: very few new downloads over the past month for EOL versions of python means that very few people are choosing to install `dill` on old resources -- it does not mean, however, that support for the EOL versions should be dropped.  The main driver I've used thus far in selecting which versions of python to support is to look at what versions of python are being supported on the national computing infrastructure (i.e. machines at LANL, ORNL, BNL, LLNL, etc).  A particular version of python ships with linux (or whatever is used, commonly RHEL), and that particular version is often what is supported on the machine until it is retired.  This definition typically corresponds fairly well to a linux distribution's EOL.  On these types of clusters (as well, to a lesser extent, in a corporate cluster environment), the user often doesn't have the opportunity to upgrade to a newer python.  Some do, but many don't.  It's my experience that most institutional clusters are running python 2.6-2.7, and/or python 3.4-3.6 -- however, I haven't done a careful study lately, and 2.6 may no longer be supported.  So, in my opinion, the definition of when to drop a version should be somewhere between python EOL and linux EOL.  Meaning, 3.3 and below are probably no longer necessary to support, and 2.6 is questionable (and probably can go, but I'll have to verify that).

**Comment by hugovk** [comment]
> Meaning, 3.3 and below are probably no longer necessary to support, and 2.6 is questionable (and probably can go, but I'll have to verify that).

@mmckerns Hello! What do you think about keeping 2.6-2.7 and 3.4+ for the time being, and dropping 2.5 and 3.1-3.3?

At least Python 2.5 and 3.1 are failing on the CI because Travis no longer supports them ([2.5 was removed 6 years ago](https://blog.travis-ci.com/2013-11-18-upcoming-build-environment-updates/)), so they should go from the CI matrix:

```
Downloading archive: https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/14.04/x86_64/python-3.1.tar.bz2
0.05s$ curl -sSf -o python-3.1.tar.bz2 ${archive_url}
curl: (22) The requested URL returned error: 404 Not Found
Unable to download 3.1 archive. The archive may not exist. Please consider a different version.
```
https://travis-ci.org/uqfoundation/dill/builds/590834530

**Comment by mmckerns** [comment]
Old code cruft has been cleaned out, and 2.x is no longer supported.  This can be closed.
