### ISSUE TITLE
dill.dumps() fails inside KNIME python environment

### ISSUE THREAD

**Issue by andressommerhoff** [uqfoundation/dill#265]
Hi! I'm trying to serialize any simple function written in python inside a software KNIME, however it fails saying that "Cannot serialize socket object". My function is not using sockets, but apparently KNIME is using sockets to interact with a python environment under the hook. I believe that DILL is finding a reference to that socket object when traveling the objects of the module where my function belongs. 

Is there any possibility to silently ignore socket object when serializing a function?

Looking forward to getting someone's help?

**Comment by matsjoyce** [comment]
```py3
import dill, socket

@dill.register(socket.socket)
def serialize_socket(pickler, obj):
    pickler.save_reduce(type(None), (), obj=obj)
```
Will change all sockets to `None`.

**Comment by mmckerns** [comment]
Another possibility is to change the value of `dill.settings['recurse']` so that the `globals` dictionary is not attempted to stored... just the global objects that are referenced.

**Comment by mmckerns** [comment]
@andressommerhoff: I'm going to assume from the lack of response here that we have addressed your question.  If that's not the case, please reopen this ticket.

**Comment by a-z-e-r-i-l-a** [comment]
@mmckerns I have the same problem when I use python3 instead of python2 and my usage is like the following:
```
                with open(self._snapshot_path, 'wb') as f: 
                    dill.dump(self, f)
```

But I didn't understand how I can use the solution that you mentioned. is there a simple line of code that I can add to it for solving this issue?
