### ISSUE TITLE
No module named dill.dill

### ISSUE THREAD

**Issue by Huyston** [uqfoundation/dill#268]
This happened today after I pip installed dill. When I'm trying to load some variables in my script. This is the traceback:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 627, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 686, in _do_respond
    response.body = self.handler()
  File "/usr/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "main.py", line 945, in open
    req = self.openFile(docID,filename)
  File "main.py", line 964, in openFile
    self.archive[docID] = pickle.load(archive)
  File "/usr/lib/python3.6/site-packages/dill/_dill.py", line 304, in load
    obj = pik.load()
  File "/usr/lib/python3.6/site-packages/dill/_dill.py", line 466, in find_class
    return StockUnpickler.find_class(self, module, name)
ModuleNotFoundError: No module named 'dill.dill'

I put an If statement before line 464 to modify the name of the module to dill._dill and now everything works as expected.
Interestingly if I save the variables again with this modified _dill.py and delete the added lines in the _dill.py and try to load again, it works. But not with the older file version.

PS: I'm in a new system. The script I am running didn't give any errors up to now. So I am not sure if this is a problem in the last version of dill (from pip3.6) or something in my new system.

**Comment by mmckerns** [comment]
I did just upload a new release to PYPI yesterday or so...
However, @Huyston: I'm not sure I understand you entirely.  Can you clarify:

1) Did this happen when you were installing `dill`?   What exactly did you type?
2) Which code did you modify, and how?  (i.e. line 464 in which file)
3) Generally... what do you mean about older file version?  You mean the unmodified _dill.py?

**Comment by mmckerns** [comment]
Also what system are you on (it seems like python 3.6 on a cherrypy...)?  More details the better.

**Comment by Huyston** [comment]
Sorry I was not complete in my description.

> Did this happen when you were installing dill? What exactly did you type?
No, it installs fine. The error was given when I was using the library to load some variables in my script.

> Which code did you modify, and how? (i.e. line 464 in which file)
I modified the _dill.py file. I did this because I saw that the file "dill.py" was not in the directory of the dill installation. So, before calling StockUnpickler.find_class(self, module, name), I changed the name of the module from 'dill.dill' to 'dill._dill'.

> Generally... what do you mean about older file version? You mean the unmodified _dill.py?
If I try to load a file from a previous file ("pickled with my other system") using this newly installed dill (my new system dill), I get the error I described (the traceback above).
If, however, I modify the "_dill.py" for changing the module name from 'dill.dill' to 'dill._dill' (before the line 464) and created a file with this modified dill, I can now "unpickle" this file with the version without the modification (the fresh install of my new system).

This new system is an Arch based distro called Porteus Nemesis.
Linux porteus 4.16.7-porteus #2 SMP PREEMPT Thu May 3 14:55:13 UTC 2018 x86_64 GNU/Linux

I think the problem might be the change in the file. I saw in http://pydoc.net/dill/0.2.7/dill.dill/ that there is no _dill.py there and this installation has. So probably there is a typo or some place that was forgotten to be changed to "_dill".

**Comment by Huyston** [comment]
And yes, I'm using python3.6 with a cherrypy server. It is basically a webpage that loads a file. The full project is available here https://github.com/Huyston/WillNotebook

**Comment by mmckerns** [comment]
First, it's best that you produce a minimal snippet of code from which I can try and reproduce the issue.  So, whatever you did to generate the Traceback is good, but the minimal thing to produce the Traceback is the best.

Second, `dill._dill` is the expected (but unnecessary) interface.  Are you trying to import `dill.dill`?  Because you should just be importing `dill`.  For example:
```
>>> import dill
>>> dill.dumps('foo')
'\x80\x02U\x03fooq\x00.'
```

**Comment by Huyston** [comment]
It is attached a minimal example.

It seems that this version of dill is incompatible with files produced with the earlier version of dill, because of the different naming convention.

[test.zip](https://github.com/uqfoundation/dill/files/2128957/test.zip)

**Comment by mmckerns** [comment]
Aha... I see.

If you put everything back to how it was off the fresh download, and then make this one substitution below, what happens?
```
    def find_class(self, module, name):
        if (module, name) == ('__builtin__', '__main__'):
            return self._main.__dict__ #XXX: above set w/save_module_dict
        elif (module, name) == ('__builtin__', 'NoneType'):
            return type(None) #XXX: special case: NoneType missing
        if module == 'dill.dill': module = 'dill._dill'
        return StockUnpickler.find_class(self, module, name)
```

Because, when I try your test file, after the edit above, I get this:
```
dude@borel>$ python main.py 
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    print(data)
UnicodeEncodeError: 'ascii' codec can't encode character '\xfa' in position 104: ordinal not in range(128)
```
I think either the best route is to always internally substitute `dill.dill` with `dill._dill` for old pickles, or to make an alias for `dill.dill` in `dill.__init__`.  I think the former is probably the better path.

Let me know if this is what you get, and if this is an expected result from your .pkl file.

**Comment by Huyston** [comment]
> if module == 'dill.dill': module = 'dill._dill'

This is exactly what I did. This UnicoreEncodeError is expected because there is 'utf-8' characters in this file.

**Comment by Huyston** [comment]
You can see the content if you change the line:
`print(data)`

to
`print(str(data).encoding('utf8'))`

**Comment by mmckerns** [comment]
Ok, so you are saying, that it works now as expected everywhere?  Because, if that is true, I'll commit the change, and then cut a new release.

**Comment by Huyston** [comment]
It is working for all files I tested up to now.

**Comment by mmckerns** [comment]
Awesome, thanks.

**Comment by Huyston** [comment]
No problem. I`m closing the issue.

**Comment by sid573** [comment]
![Screenshot from 2019-06-01 17-46-26](https://userimages.githubusercontent.com/35433185/58748360-3c68b780-8495-11e9-82a9-4269cd4d8c2a.png)
I'm trying to use pickel.load() and I have installed dill 0.2.9 but its showing dill.dill not found.
Hope you can help me!!!
Thanks

**Comment by sid573** [comment]
![Screenshot from 2019-06-01 17-46-26](https://user-images.githubusercontent.com/35433185/58748400-c284fe00-8495-11e9-8207-046b47a2b683.png)

**Comment by mmckerns** [comment]
@sid573: you should try what is detailed above... and if that doesn't work, then open a new ticket.
