### ISSUE TITLE
dill dump raises SimpleQueue objects should only be shared between processes through inheritance

### ISSUE THREAD

**Issue by Alonreznik** [uqfoundation/dill#271]
Hi There.
I'm trying to dump my code using dill (which has some deque in other function) and gets the following exception:

`SimpleQueue objects should only be shared between processes through inheritance`

Do you familiar with that exception? What should I do?

Thanks

Alon

**Comment by mmckerns** [comment]
Best thing to do is post a very simple version of your code that reproduces the error, and then also the traceback.

It would seem that the `SimpleQueue` object is not serializable.  Post code you are seeing it in, and I can check it.

You do have some simple options, which I can recommend in the abstract.

Try changing the `dill.settings`, so `dill.settings['recurse'] = True`.  There's also `'byref'`, which you could set to `True`.  You can either change the settings globally (with `settings`) or on a object by object basis (by passing kwd `recurse=True` into the `dump` method).

**Comment by mmckerns** [comment]
@Alonreznik: Due to the lack of activity on this thread, I'm going to assume we have addressed your issue.  Please reopen if this is not the case.
