### ISSUE TITLE
ImportError: No module named 'dill._dill' using to 0.2.7.1 depickle object from 0.2.8.2 

### ISSUE THREAD

**Issue by ddebrunner** [uqfoundation/dill#272]
I pickled a lambda function using 0.2.8.2 and then transmitted it to a system with 0.2.7.1. Receive the `ImportError` trying to depickle the object.

According to comments in #270 this should be supported.

Here's output for a small test, switching between dill versions on the same system.
```
+ pip install --upgrade dill
Collecting dill
pyasn1-modules 0.2.1 has requirement pyasn1<0.5.0,>=0.4.1, but you'll have pyasn1 0.1.9 which is incompatible.
Installing collected packages: dill
  Found existing installation: dill 0.2.7.1
    Uninstalling dill-0.2.7.1:
      Successfully uninstalled dill-0.2.7.1
Successfully installed dill-0.2.8.2
+ pip show dill
Name: dill
Version: 0.2.8.2
Summary: serialize all of python
Home-page: https://pypi.org/project/dill
Author: Mike McKerns
Author-email: UNKNOWN
License: 3-clause BSD
Location: /home/streamsadmin/anaconda3/lib/python3.5/site-packages
Requires: 
Required-by: 
+ python3 read.py
15
+ pip install dill==0.2.7.1
Collecting dill==0.2.7.1
pyasn1-modules 0.2.1 has requirement pyasn1<0.5.0,>=0.4.1, but you'll have pyasn1 0.1.9 which is incompatible.
Installing collected packages: dill
  Found existing installation: dill 0.2.8.2
    Uninstalling dill-0.2.8.2:
      Successfully uninstalled dill-0.2.8.2
Successfully installed dill-0.2.7.1
+ python3 read.py
Traceback (most recent call last):
  File "read.py", line 6, in <module>
    fn = dill.loads(base64.b64decode(saved))
  File "/home/streamsadmin/anaconda3/lib/python3.5/site-packages/dill/dill.py", line 299, in loads
    return load(file)
  File "/home/streamsadmin/anaconda3/lib/python3.5/site-packages/dill/dill.py", line 288, in load
    obj = pik.load()
  File "/home/streamsadmin/anaconda3/lib/python3.5/site-packages/dill/dill.py", line 445, in find_class
    return StockUnpickler.find_class(self, module, name)
ImportError: No module named 'dill._dill'
```

**Comment by ddebrunner** [comment]
This script (`save.py`) echos the pickled string:
```
import dill
import base64
function = lambda x : x+7
e = base64.b64encode(dill.dumps(function)).decode("ascii")
print(e)
```

I used the output of that (with dill 0.2.8.2 installed) as the input in `read.py`
```
import dill
import base64

saved='gANjZGlsbC5fZGlsbApfY3JlYXRlX2Z1bmN0aW9uCnEAKGNkaWxsLl9kaWxsCl9sb2FkX3R5cGUKcQFYCAAAAENvZGVUeXBlcQKFcQNScQQoSwFLAEsBSwJLQ0MIfAAAZAEAF1NxBU5LB4ZxBilYAQAAAHhxB4VxCFgHAAAAc2F2ZS5weXEJWAgAAAA8bGFtYmRhPnEKSwNDAHELKSl0cQxScQ1jX19idWlsdGluX18KX19tYWluX18KaApOTn1xDnRxD1JxEC4='

fn = dill.loads(base64.b64decode(saved))

print(fn(8))
```

**Comment by mmckerns** [comment]
New versions of `dill` are backward compatible with older versions, and support loading saved pickles from old versions of `dill`. 

For this particular case, there was a change made as the interface `dill.dill` should not be used, and thus was moved to `dill._dill` to highlight that it is private.  I argue that the solution here is to upgrade the older version of dill to `0.2.8.2`.

Is there a particular reason that you'd need a dependency on an older version of `dill`?  I realize that if you are using `dill` to ship objects between two systems, then yes, going from `0.2.8.2` to `0.2.7.1` won't work for objects that depend on the `dill._dill` reference until the older version is upgraded. 

If it's an absolute need.  The thing to do would be to find where `dill` stores the name of the module when it serializes the function, class, etc... and if it is `dill._dill` then store it as `dill.dill`.

**Comment by mmckerns** [comment]
@ddebrunner: I was just correcting myself in #270.  We nearly always do have compatibility across versions of `dill` in both directions -- however, the guarantee is from old to new versions.  Sorry about the temporary confusion.

Yes, the part that I missed is that when you store a function, it stores the name of the module that the function lives... and for functions like `dill._dill._create_function`, the name that gets stored is `dill._dill`.  Which is why you have the break.  So, TBH, I missed that impact of moving `dll.dill` to `dill._dill` on storing the name of the functions inside of the internal module.  We don't test that new pickles will load into old versions.  Sorry about that.
