### ISSUE TITLE
PyPI project metadata doesn't specify requires_dist

### ISSUE THREAD

**Issue by RaptDept** [uqfoundation/dill#273]
[poetry](https://github.com/sdispater/poetry)'s dependency resolver uses [PyPI's JSON API](https://wiki.python.org/moin/PyPIJSON), particularly the `info.requires_dist` field, to determine a package's dependencies. [In dill's case](https://pypi.org/pypi/dill/json), this field is null. Because of this, poetry won't pick up the `pyreadlines` dependency when installing dill on Windows.

(see https://github.com/sdispater/poetry/issues/20#issuecomment-374237508 for a bit of similar context)

**Comment by mmckerns** [comment]
I believe this was silently addressed in 2019 or so, and the issue not closed.  If you check the link you provided above, it seems to work as `requires_dist` is not null.  Closing this issue. Please reopen if it was closed in error.
