### ISSUE TITLE
Attempting to pickle an entire Jupyter Notebook kernel - getting an error

### ISSUE THREAD

**Issue by beflyguy** [uqfoundation/dill#281]
I'm writing code in a Jupyter Notebook that involves cleaning and analyzing a large amount of consumer data. I'm trying to use dill to save the dataframes with thousands of rows so I don't have to run the code every time I want to make an adjustment, so dill seems like the perfect package to do so... Except I'm getting this error when attempting to pickle the notebook:

`AttributeError: module 'dill' has no attribute 'dump_session'`

Let me know if the program code is necessary - I don't think it should make a difference. The imports are:

`import numpy as np`
`import pandas as pd`
`import dill`
`import scipy`
`from matplotlib import pyplot as plt`
`from __future__ import division`
`from collections import OrderedDict`
`from sklearn.cluster import KMeans`
`pd.options.display.max_columns = None`

and when I run this code I get the error from above:

`dill.dump_session('recengine.db')`

Is there another package that's interfering with `dill`'s use of `pickle` vs. `cpickle`?

**Comment by mmckerns** [comment]
@beflyguy: Sorry for the delayed response.  Did you work this out?  I tried the imports above, using python 2.x and 3.x, and I don't see an error when I try a `dill.dump_session`.  It's odd that you are seeing the `AttributeError` that says the `dill` module doesn't have a `dump_session`.  That type of error can be seen when pickling fails (typically, a reference to a class or function is pickled poorly, and upon load, the class/function is missing)... but not seen on a `dump_session` in `dill`.  I can't think of why that would happen.

There are a few possible interferences I can think of: (1) you should import `__future__` first -- I did, (2) `sklearn` has a fork of `joblib`, which when run in parallel uses `cloudpickle`, which can interfere with `dill` if you import it into globals, and (3) an object you've built is messing with `dill` (I don't know of anything that would do that, but in theory, it's possible).  `dill` should be able to pickle `sklearn` models and `pandas` objects without issue.

What version of `dill`, `python`, `jupyter`, etc are you using?  If you resolved it, let me know, and close the ticket.

**Comment by mmckerns** [comment]
I'm closing this, as I can't reproduce this issue... and there's no response to give further information.  So, if you are still experiencing an issue, please reopen the issue.
