### ISSUE TITLE
dill.tests fails

### ISSUE THREAD

**Issue by Oliver-Chalkley** [uqfoundation/dill#286]
Here's what happens when I run the tests:

`$ python -m dill.tests`
`<function <lambda> at 0x7f5f65b92048>`
`<function <lambda> at 0x7fec49ed1048>`
`<function <lambda> at 0x7f2642517048>`
`<function <lambda> at 0x7f4b63b7e048>`
`<function <lambda> at 0x7fa02fd88048>`
`fails: BigEndianStructureType <class 'ctypes._endian.BigEndianStructure'>`
`fails: SocketType <class 'socket.socket'>`
`fails: SocketPairType <class 'socket.socket'>`
`fails: FileType <class '_io.FileIO'>`
`fails: GzipFileType <class 'gzip.GzipFile'>`
`..................`

I tried to update dill just in case that helped

`$ conda update dill`
`Fetching package metadata ...........`
`Solving package specifications: .`

`# All requested packages already installed.`
`# packages in environment at /space/oc13378/software/anaconda/anaconda3/envs/wholecell_modelling_suite_35:`
`#`
`dill                      0.2.8.2                  py35_0 `

Can anyone suggest what is wrong, how bad it is and how to fix it?

**Comment by mmckerns** [comment]
That's not a failure, it's a "noisy" success.  So, that's the expected behavior.  Sorry it is confusing... it's demonstrating that there are still some objects that aren't able to be pickled.
