### ISSUE TITLE
Serialize method with global variables

### ISSUE THREAD

**Issue by yuhc** [uqfoundation/dill#291]
Here's an example code which dill fails to serialize. `FLAG` is a global variable and the method `A.func` is a blackbox to me so that I don't know it calls FLAG before serialization.

```python
import dill as pickle
FLAG = 100

class A:
  def func(self):
    print FLAG * 10

a = A()
dump = pickle.dumps(a.func)
del FLAG
foo = pickle.loads(dump) # fail here "NameError: global name 'FLAG' is not defined"
foo()
```

One way is to copy the value of `FLAG` to `A`'s variable, say `A._flag`, then dill can work perfectly. However I don't want to modify the source code (because it's a blackbox).
Is there any way to serialize such functions with its global dependencies by dill?
Thanks!

The mirror question:
https://stackoverflow.com/questions/53342955/serialize-a-python-method-with-global-variables-by-dill

**Comment by mmckerns** [comment]
Yes, you can either use the setting: `dill.settings['recurse'] = True`, or use the `recurse` keyword when you `dump`:
```
>>> import dill
>>> FLAG = 100
>>> 
>>> class A:
...   def func(self):
...     return FLAG*10
... 
>>> a = A()
>>> dump = dill.dumps(a.func, recurse=True)
>>> del FLAG
>>> foo = dill.loads(dump)
>>> foo()
1000
>>> 
```

**Comment by yuhc** [comment]
Thanks, it works! And thank you for adding the answer to the stackoverflow.
Btw, if `func()` is dependent on an imported module's function, and the module moo is implemented in a file moo.py (not installed in the system), then is it possible to unpickle serialized `func()` without moo.py?.
The answer here https://stackoverflow.com/a/28639569/3847417 seems to require the file moo.py to be present on the unpickler side.

```python
import moo
def func():
  return moo.bar()
```

moo.py:
```python
def bar():
  print("X")
```

**Comment by yuhc** [comment]
The `dill.settings['recurse'] = True` option actually introduces another problem:

```python
import dill as pickle

FLAG = 100

class B(object):
    def __init__(self):
        print "hello"

class A(B):
    def __init__(self):
        super(A, self).__init__()

    def func(self):
      print FLAG * 10

a = A()
dump = pickle.dumps(a, recurse=True)
del FLAG
del A
foo = pickle.loads(dump) # fail here if recurse=True, "AttributeError: 'module' object has no attribute 'A'"

print foo
print foo.func() # fail here if recurse=False, "NameError: global name 'FLAG' is not defined"
```
Did I miss anything?

**Comment by mmckerns** [comment]
@yuhc: No, I don't think you have missed anything.  If the module `moo.py` is not installed, but a dependency, then I believe `dill` fails to find `moo.py`.  There's already an existing ticket for that.  Secondly, I'd argue that the `'recurse'` option doesn't introduce a "problem" -- it's just that there are some constructs that don't serialize easily, and each of the different serialization variants have coverage of portions of the total scope of all possible python objects.  I believe the two `# fail` above that you are reporting are also duplicates of existing issues.  See #123, #75, #56, and related.

I'm tempted to mark this ticket as duplicate, as it seems to be repeating existing issues.  I understand it's somewhat frustrating that everything doesn't serialize easily... there are many known patterns where `dill` fails to serialize an object.  Do you have any other new input or questions with regard to the above, or can this ticket be closed?

**Comment by yuhc** [comment]
Sure, I'm closing this ticket. I'll check the related issues that you gave. Thanks for the help!
