### ISSUE TITLE
Problem with dill.copy() in Python3.  

### ISSUE THREAD

**Issue by 3fon3fonov** [uqfoundation/dill#293]
First of all thank you for developing dill! 

The problem I am facing is with Python3. As far as understood in Py3
one cannot compare 'None' with a integer (which works in Py2).

One gets the following error in Py3
TypeError: unorderable types: NoneType() > int()

So when I try:
```
.....
copied_obj = dill.copy(obj)
.....
```

I am getting:

  File "/home/tito/trifon/RV_mod.py", line 524, in phase_planet_signal
    copied_obj = dill.copy(obj) 
  File "/usr/local/lib/python3.5/dist-packages/dill/_dill.py", line 239, in copy
    return loads(dumps(obj, *args, **kwds))
  File "/usr/local/lib/python3.5/dist-packages/dill/_dill.py", line 316, in loads
    return load(file, ignore)
  File "/usr/local/lib/python3.5/dist-packages/dill/_dill.py", line 304, in load
    obj = pik.load()
  File "/usr/local/lib/python3.5/dist-packages/dill/_dill.py", line 636, in _create_filehandle
    if position > current_size:
TypeError: unorderable types: NoneType() > int()

I traced the problem to:

line 949 in _dill.py

```
def _save_file(pickler, obj, open_):
    if obj.closed:
        position = None

```

This will fail later at "if position > current_size:". 
Therefor just as a quick hack i replaced  None --> 0, i.e.:

```
def _save_file(pickler, obj, open_):
    if obj.closed:
        position = 0

```
which now works.

Can you comment on that and possibly fix it in the current release?

All the best,
Trifon

**Comment by RobbeSneyders** [comment]
I've encountered the same problem. I've submitted a PR at #294.

**Comment by mmckerns** [comment]
Fixed by @RobbeSneyders with #294.

**Comment by tvalentyn** [comment]
Thanks @RobbeSneyders for the fix and thanks @mmckerns for quick review and merge. 
@mmckerns Do you know when we could expect to have dill minor version release with the fix?

**Comment by tvalentyn** [comment]
Hi @mmckerns, do you by chance have an updated ETA for next minor version release? Once again, thanks a lot for maintaining dill!

**Comment by mmckerns** [comment]
@tvalentyn: After some delays... it's 99.99% happening this weekend.

**Comment by tvalentyn** [comment]
That's great news, thank you, @mmckerns !
