### ISSUE TITLE
Strange behavior when "dilling" an execute code block

### ISSUE THREAD

**Issue by HolgerMoser** [uqfoundation/dill#295]
I encountered the following behavior and i am not sure what is causing it or if there is a "fix" or workaround.

I have the following program:

```
import sys
import dill
from base64 import b64encode


def tracer(frame, event, arg):
    if event == 'return' and frame.f_lineno == 6:
        names = ('a', 'b')
        for name in names:
            obj = frame.f_globals.get(name)
            if obj:
                print('{} = {}'.format(name, b64encode(dill.dumps(obj))))
    return tracer


def main():
    code = """def a():
  b()
print('.')
def b():
  print("Test")
a()
"""

    # state = globals()             <-- doing this works as expected
    state = {}
    state.update(globals())      <-- doing it like this does not work as expected

    code_obj = compile(code, '__main__', 'exec')
    sys.settrace(tracer)
    exec(code_obj, state)
    sys.settrace(None)


if __name__ == '__main__':
    main()
```

When i take the dumped content for function a and b and "undill" them i get different results for `state = globals()` and `state = {} state.update(globals())`. Just having state as a reference of globals gives me a result which can be "used" (i can call a and b and get the expected result). In the second case, i get two functions which dont even have access to the builtins (b throws an error that print is not defined). Also the dumped content for the second ("failing") case is much bigger. The background of this whole question is that i would want to store the state between code block executions (dumping the state for each executed line, and be able to later inject it back in) which gives me unusable results because of the "problem" i described above.

**Comment by matsjoyce** [comment]
Have you tried putting that code in a module and importing that module from `__main__`? There are quite a few interesting behaviors that occur when code comes from `__main__` that allow serializing interpreter sessions. Also try `recurse=True` in the options for dumping.

**Comment by HolgerMoser** [comment]
Putting the code in an extra module did not change the behavior but adding "recurse=True" did! Thanks for your help
