### ISSUE TITLE
[deleted]

### ISSUE THREAD

**Issue by robert-314** [uqfoundation/dill#303]
[deleted]

**Comment by mmckerns** [comment]
@robert-314: I appreciate what you said (before deleting your ticket.  `dill` has had consistent funding over a decade -- admittedly, not at a high level.  I do not foresee support for `dill` dropping off in any way.  It would be nice to have more support for it, and I have applied for support for `dill` a few times in the past.  I'd like to support a portion of a developer on `dill`, however will also happily take user contributions and PRs.
