### ISSUE TITLE
Can't pickle the generator object?

### ISSUE THREAD

**Issue by brutemap-dev** [uqfoundation/dill#311]
In [18]: def gen():
    ...:     for i in range(1, 5):
    ...:         yield i
    ...:

In [19]: g = gen()

In [20]: g_clone = dill.loads(dill.dumps(g)
    ...: )
-------------------------------------------
TypeError Traceback (most recent call last)
<ipython-input-20-498e48118755> in <module>()
----> 1 g_clone = dill.loads(dill.dumps(g))

/usr/local/lib/python2.7/dist-packages/dill/_dill.pyc in dumps(obj, protocol, byref, fmode, recurse)
    292     """pickle an object to a string"""
    293     file = StringIO()
--> 294     dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
    295     return file.getvalue()
    296

/usr/local/lib/python2.7/dist-packages/dill/_dill.pyc in dump(obj, file, protocol, byref, fmode, recurse)
    285         raise PicklingError(msg)
    286     else:
--> 287         pik.dump(obj)
    288     stack.clear()  # clear record of 'recursion-sensitive' pickled objects
    289     return

/usr/lib/python2.7/pickle.pyc in dump(self, obj)
    222         if self.proto >= 2:
    223             self.write(PROTO + chr(self.proto))
--> 224         self.save(obj)
    225         self.write(STOP)
    226

/usr/lib/python2.7/pickle.pyc in save(self, obj)
    304             reduce = getattr(obj, "__reduce_ex__", None)
    305             if reduce:
--> 306                 rv = reduce(self.proto)
    307             else:
    308                 reduce = getattr(obj, "__reduce__", None)

TypeError: can't pickle generator objects

**Comment by mmckerns** [comment]
Thanks for reporting.  Yes, this is a well known issue (see: #10).

**Comment by brutemap-dev** [comment]
Hmm, I found a way to make pickle object generators in python, try visiting: https://github.com/tonyroberts/generator_tools. (This works for me, but the process is very long) I don't know why.

**Comment by mmckerns** [comment]
@brutemap-dev: Yep, I know of that package.  It works, it's been around a while.  I've been hesitant to include it in `dill` for reasons that I don't remember.  Thanks for the reminder.
