### ISSUE TITLE
Document differences to cloudpickle and other stuff doing pickling better than pickle

### ISSUE THREAD

**Issue by KOLANICH** [uqfoundation/dill#314]

**Comment by mmckerns** [comment]
Which other stuff "doing pickling better"?  You mean doing better than `pickle`, correct?

I only know of the two primary choices for serialization that are alternatives to `pickle`: `dill` and `cloudpickle`... and note that `dill` has a `cloudpickle` mode that mimics the behavior of `cloudpickle`.  Generally `dill` handles more varied types of items, and has greater flexibility.  If you are asking for an extensive list of what can be serialized and what can't -- and how it compares to `pickle` -- `dill` already provides a decent such list, and haven't seen another comparison like it yet anywhere.

**Comment by KOLANICH** [comment]
>Which other stuff "doing pickling better"? You mean doing better than pickle, correct?

Yeah.

>If you are asking for an extensive list of what can be serialized and what can't -- and how it compares to pickle -- dill already provides a decent such list, and haven't seen another comparison like it yet anywhere.

I mean a table comparing dill, pickle and cloudpickle and other libs. Columns are libs. Rows are things can be pickled and other features. Intersections are either ✔️ or ❌ showing if the feature present in the lib.

**Comment by mmckerns** [comment]
This is the most extensive list I know of: https://github.com/uqfoundation/dill/blob/master/dill/_objects.py.  It's `dill` and `pickle`.  There are obviously other things that could be included, such as objects from common packages like `sklearn`, `maplotlib`, `sympy`, `pandas`, etc.  If I do dig into `cloudpickle` a bit more (it's been years since I did last), then I may add it to the above file.  Anyone is welcome to expand on this file themselves, as long as it doesn't impact the import time of `dill`.

**Comment by KOLANICH** [comment]
Thank you for the info.

**Comment by mmckerns** [comment]
Note that the test for `objects`: https://github.com/uqfoundation/dill/blob/master/tests/test_objects.py, can use `cloudpickle` (it's currently commented out, but easy to uncomment).  With regard to some of the more recent objects added to the STL (python `3.7+`) and some of the most common packages (listed above), I've scheduled to add such objects over the next couple months.  This should close some gaps between `cloudpickle` and `dill`.

I'm going to close this ticket.  Please reopen if you feel your question/request has not been addressed.
