### ISSUE TITLE
refactor setup.py

### ISSUE THREAD

**Issue by KOLANICH** [uqfoundation/dill#315]
The code in `setup.py` is damn bad. It heavily needs refactoring.
1 remove all the large docstrings that can be read from files
2 stop constructing code and then executing it
3 use `setup.cfg` for storing metadata

Your `setup.py` should look like

```python
from setuptools import setup
setup(use_scm_version = True)
```

**Comment by mmckerns** [comment]
Duplicate of #114.

**Comment by mmckerns** [comment]
Feel free to submit a PR.

**Comment by KOLANICH** [comment]
OK
