### ISSUE TITLE
dill fails to dump/load io module-based files on Py2

### ISSUE THREAD

**Issue by mobiusklein** [uqfoundation/dill#333]
Under Python 2.7, `dill` 0.3 does not serialize `io` objects correctly. In `dill._dill`, it obtains instances of each file type using `get_file_type`:
https://github.com/uqfoundation/dill/blob/master/dill/_dill.py#L189-L208
Reproduced below:
```python
def get_file_type(*args, **kwargs):
    open = kwargs.pop("open", __builtin__.open)
    f = open(os.devnull, *args, **kwargs)
    t = type(f)
    f.close()
    return t

FileType = get_file_type('rb', buffering=0)
TextWrapperType = get_file_type('r', buffering=-1)
BufferedRandomType = get_file_type('r+b', buffering=-1)
BufferedReaderType = get_file_type('rb', buffering=-1)
BufferedWriterType = get_file_type('wb', buffering=-1)
try:
    from _pyio import open as _open
    PyTextWrapperType = get_file_type('r', buffering=-1, open=_open)
    PyBufferedRandomType = get_file_type('r+b', buffering=-1, open=_open)
    PyBufferedReaderType = get_file_type('rb', buffering=-1, open=_open)
    PyBufferedWriterType = get_file_type('wb', buffering=-1, open=_open)
except ImportError:
    PyTextWrapperType = PyBufferedRandomType = PyBufferedReaderType = PyBufferedWriterType = None
```
and https://github.com/uqfoundation/dill/blob/master/dill/_dill.py#L993-L1013
```python
@register(FileType) #XXX: in 3.x has buffer=0, needs different _create?
@register(BufferedRandomType)
@register(BufferedReaderType)
@register(BufferedWriterType)
@register(TextWrapperType)
def save_file(pickler, obj):
    log.info("Fi: %s" % obj)
    f = _save_file(pickler, obj, open)
    log.info("# Fi")
    return f

if PyTextWrapperType:
    @register(PyBufferedRandomType)
    @register(PyBufferedReaderType)
    @register(PyBufferedWriterType)
    @register(PyTextWrapperType)
    def save_file(pickler, obj):
        log.info("Fi: %s" % obj)
        f = _save_file(pickler, obj, _open)
        log.info("# Fi")
        return f
```
This uses the `builtin.open` function, which under Py3 is just an alias of `io.open` which returns the appropriate types. Under Py2, these just return instances of the `file` type. To fix this issue, you would have to create another block like the one enclosed in the `try` block at the end explicitly calling `get_file_type` with `io.open`.

Using this snippet:
```python
import io, dill
fh = io.open("path/to/file", "rb")
print(dill.dumps(fh))
```
Under Py2: `'\x80\x02c_io\nBufferedReader\nq\x00)\x81q\x01.'`
Under Py3: `b'\x80\x03cdill._dill\n_create_filehandle\nq\x00(X\x15\x00\x00\x00path/to/fileq\x01X\x02\x00\x00\x00rbq\x02K\x00\x89cdill._dill\n_get_attr\nq\x03cdill._dill\n_import_module\nq\x04X\x02\x00\x00\x00ioq\x05\x85q\x06Rq\x07X\x04\x00\x00\x00openq\x08\x86q\tRq\n\x89K\x00X\x00\x00\x00\x00q\x0btq\x0cRq\r.'`

Unpickling under Py2 produces a new `io.BufferedReader` instance, but any attempt to manipulate it is met with `ValueError: I/O operation on uninitialized object`.

Should I open a PR for this?

**Comment by mmckerns** [comment]
Sorry this got ignored. I'm closing it as not relevant, as 2.7 is no longer supported.
