### ISSUE TITLE
pickles from 0.3.1.1 are not guaranteed to unpickle with 0.3.0

### ISSUE THREAD

**Issue by tvalentyn** [uqfoundation/dill#341]
We observed in https://issues.apache.org/jira/browse/BEAM-8324 that main sessions pickled with dill==0.3.1.1 cannot be unpickled with dill==0.3.0. 
```
... return dill.load_session(file_path)
  File "/usr/local/lib/python3.7/site-packages/dill/_dill.py", line 410, in load_session
    module = unpickler.load()
TypeError: _create_function() takes from 2 to 6 positional arguments but 7 were given
```

This is due to changes https://github.com/uqfoundation/dill/pull/336 that happened between 0.3.0 and 0.3.1.1. 

The changes  https://github.com/uqfoundation/dill/pull/336 improve dill functionality, however they also open a question whether such changes should be implemented in a backwards-compatible way, when minor version is not increased.

@mmckerns - does dill intend to have any backwards-compatibility guarantees between versions?  

cc:@lazylynx

**Comment by mmckerns** [comment]
Dill does intend to have backward compatibility, in general.  It has not, only in cases that were missed in review -- like this one.

**Comment by tvalentyn** [comment]
I see, thanks. Does dill target a particular window for backwards compatibility such as with one minor version, but not across multiple minor versions?

**Comment by tvalentyn** [comment]
Reworded the issue, thanks for correction.

**Comment by mmckerns** [comment]
No, the intent is to be as backward compatible as possible across all versions.  I missed it in my review.  This has happened twice as far as I can remember.  I'll prioritize a patch for this.

There's another release scheduled for less than a month from now.

**Comment by mmckerns** [comment]
I believe this is contained to `_create_function`

**Comment by lazylynx** [comment]
@mmckerns Sorry for my carelessness. I'll work on this if needed.

**Comment by tvalentyn** [comment]
@lazylynx To be honest, I don't think you were careless here, this problem is not easy to see. I think in order to maintain compatibility guarantees, dill needs to have tests that verify the compatibility, and such tests need to run using multiple versions of dill. These test could run either per PR (catch errors early), or when qualifying a release.

**Comment by ddebrunner** [comment]
@tvalentyn FYI earlier discussion of compatibility in #270 & #272 

Thanks for entering this, we also hit this.

**Comment by mmckerns** [comment]
@lazylynx: no I missed it in the review.  The requirement isn't in the tests, it's only stated in the PRs @ddebrunner is referencing above (this is the other time I was mentioning).  As soon as a patch goes in for the change, I'll cut a new patch release.

**Comment by tvalentyn** [comment]
@mmckerns there may be one other issue related to #336: after an upgrade to dill==0.3.1.1 one of our tests began to fail, but only when the test is running as a part of a suite, and only on Python 3.7 (https://issues.apache.org/jira/browse/BEAM-8324?focusedCommentId=16941261&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16941261).
We did not rootcause the issue yet, but I wanted to give you a heads-up. On Beam side, this issue is investigated in https://issues.apache.org/jira/browse/BEAM-5878.

**Comment by mmckerns** [comment]
@tvalentyn: for pickling, one of the best diagnostic tools is `dill.detect.trace(True)`.  Depending on the complexity of the issue, it may be better as it's own issue.  I'll see what I can do to expedite a patch release for this.

**Comment by mmckerns** [comment]
@tvalentyn: I tried to produce pickling errors when pickling a function in 0.3.0 and unpicking in 0.3.1.1, and I couldn't... the function is written robustly (thanks @lazylynx!), and it avoids issues when using older pickles.  This is what is typically guaranteed by `dill`.  After reading the issue you quoted from BEAM... I see that you are actually pickling with 0.3.1.1, and then unpicking with 0.3.0. 
So, I misunderstood you.  That's typically not a case I consider... but it makes sense with what you guys are doing (with client and server, for example).  So, this case isn't typically on my radar at all, and much harder to support.

**Comment by mmckerns** [comment]
@ddebrunner, @tvalentyn: if this is something that you both need support for (apparently it is), then maybe you both can come up with a plan for how to do that.  Again, it's something that I don't currently support -- and in the abstract, I can try to be more mindful of it... say adding a new function and then detecting the function name... but this is super hard to patch as is.

**Comment by tvalentyn** [comment]
Sure, forwards-compatibility is hard to support, however, it would be helpful if:

-  it is documented (for example, never assume that pickles created by a higher version of dill will be able to unpickle by lower version), 
- or we have compatibility guarantees within a particular version range, which are also documented.

The second alternative would be more user-friendly, but would involve more efforts to maintain. 

When there are no forward-compatibility guarantees, we have no choice but to fix the version of dill on the client and the server to a specific version, which is very restrictive.

**Comment by mmckerns** [comment]
@tvalentyn: my suggestion is this... you have a BEAM test environment that uses the development version of dill (e.g. `0.3.2.dev0`), and checks compatibility for whatever other version of `dill` you need to ship pickled between.  That way, if there's a break in the ability to unpickle to older versions, then you will see it before the release... and it can be planned for before a release is cut, and it becomes much harder to change. 

On this side, we'll try to test potential behavior changes between versions, and assess the impact a bit more for pickles in the backward direction -- still no guarantee, but at the very least we will more strongly consider mitigating the impact as much as possible for such a change.

**Comment by tvalentyn** [comment]
In some cases breaking changes are required, and in fact, we will benefit from #336 in the long term. However the issue is that there is no safe window of compatibility. We can potentially do the testing against dill head, but it would not be practical for us to go back and patch older releases of apache-beam that become affected by incompatibility between dill versions, so the solution for us is to choose a very narrow range for dill, or just pinning the dependency to an exact version. 

Commonly we try to be as flexible as possible with requirements for our dependencies, since it makes dependency management easier for users of our package. Typically, we assume that a dependency will remain compatible within releases with the same major version. 

We wanted to relax dill requirement to be dill>=0.3.0,<0.4.0 in our latest release, but thanks to discovering this issue in time, we set the lower bound to <0.3.1, so this issue is mitigated for us.

**Comment by mmckerns** [comment]
I'm closing this issue, as it seems to have run it's course.  If there's more to say here, please comment and/or reopen.

**Comment by DylanYoung** [comment]
I'm also quite curious about this.  Based on this conversation, I'd like to see a plan for compatibility support in the docs. 

But I actually came here wondering about pickle compatibility across python versions.  Is this documented somewhere?

**Comment by tvalentyn** [comment]
@DylanYoung see https://github.com/uqfoundation/dill/issues/254

**Comment by DylanYoung** [comment]
Thanks! That's more or less what I expected.  Is there any work that you
know of on the python language side towards establishing a consistent
pickle format across versions?

Seems eminently useful.

**Comment by tvalentyn** [comment]
Python has an option to specify the version of pickling protocol, see: https://docs.python.org/3/library/pickle.html#data-stream-format, which sets requirements on minimum interpreter version to unpickle.

**Comment by leogama** [comment]
> I'm closing this issue, as it seems to have run it's course. If there's more to say here, please comment and/or reopen.

In the next release, dill won't use the `fdict` and `fkwdefaults` parameters anymore, as it starts passing a `state` argument to `pickle.Pickler.save_reduce()`:
https://github.com/uqfoundation/dill/blob/5bd56a8e0096c3f45f4c37ff0b67ac6aa341f22b/dill/_dill.py#L1907-L1910

Actually, using this feature, I think it may be possible to use `FuctionType` directly instead of `_create_function()`...
