### ISSUE TITLE
dill 0.2.8.2 faiiles to import objects from objtypes

### ISSUE THREAD

**Issue by saikrish91** [uqfoundation/dill#349]
In `dill 0.2.8.2` , when objtypes get imported in `dill/__init__.py`  , `objtypes` in turn tries to import `object` from the `__init__.py`. This throws an import error , because a circular dependency is created and `object` from `__init__.py` gets called before its loaded.

Error stacktrace -
```
   import dill
  File ".../lib/python2.7/site-packages/dill/__init__.py", line 60, in <module>
    from . import objtypes as types
  File ".../lib/python2.7/site-packages/dill/objtypes.py", line 16, in <module>
    from dill import objects
ImportError: cannot import name objects
```

Versions -
Python - 2.7
Dill - 0.2.8.2

**Comment by mmckerns** [comment]
@saikrish91: That's a relatively old version of `dill`.  I don't see this error on any of the most recent versions (and didn't test on 0.2.8.2, due to it being an older version).  Can you not just upgrade your version of `dill`, or do you need 0.2.8.2 for some particular reason?  If you upgrade, do you still experience your issue?

**Comment by eddyxu** [comment]
I have the same issue with `dill==0.3.1.1` /  Python 2.7.17

**Comment by mmckerns** [comment]
@eddyxu: I can't reproduce this issue.  Can you give me more information?  Can you show code triggering the issue, and provide a traceback?  What platform are you on?

**Comment by lavroffrob13** [comment]
Getting the same error, here's the traceback:

Traceback (most recent call last):
  File "/u/home/l/lavroffr/PGOPT-PROGRAMS/ACNN/main.py", line 26, in <module>
    from utils.io import read_json, write_json
  File "/u/home/l/lavroffr/PGOPT-PROGRAMS/ACNN/utils/io.py", line 2, in <module>
    import os, json, dill, re
  File "/u/home/l/lavroffr/anaconda2/lib/python2.7/site-packages/dill/__init__.py", line 60, in <module>
    from . import objtypes as types
  File "/u/home/l/lavroffr/anaconda2/lib/python2.7/site-packages/dill/objtypes.py", line 16, in <module>
    from dill import objects
ImportError: cannot import name objects

Code for each of these .py here:
[objtypes.txt](https://github.com/uqfoundation/dill/files/5176227/objtypes.txt)
[__init__.txt](https://github.com/uqfoundation/dill/files/5176228/__init__.txt)
[main.txt](https://github.com/uqfoundation/dill/files/5176229/main.txt)
[io.txt](https://github.com/uqfoundation/dill/files/5176230/io.txt)

**Comment by mmckerns** [comment]
@lavroffrob13:  Am I correct in that all you are doing is importing `dill` to see the error?

Can you try this?
In an empty python session, just type:
```
import dill
```
Then let me know if you are still getting the same traceback.

That particular bit of code in `dill` uses both nonlocal and local imports, essentially assuming that you have `dill` installed somewhere in your path -- so maybe you can also tell me how you installed `dill` and any other information about names of files in your local directory and/or your $PATH environment variable. 

I still haven't been able to reproduce this.

**Comment by lavroffrob13** [comment]
@mmckerns After some more digging, my dill package seemed to have gotten corrupted somehow. Uninstalling and reinstalling seems to have fixed the issue. Thanks!

**Comment by mmckerns** [comment]
@eddyxu @saikrish91: I'm going to close this issue as stale, as I'm not seeing responses from either of you, and I can't reproduce the issue... and you may have the same issue as @lavroffrob13.  Feel free to reopen if this is not the case.
