### ISSUE TITLE
Error rised at line _dill.py", line 472, in load, obj = StockUnpickler.load(self) when used with Python 2

### ISSUE THREAD

**Issue by 3fon3fonov** [uqfoundation/dill#351]
First, I would like to say that I am not sure if the problem is in dill at all, but I would appreciate some wisdom. 

It seems that for some reason I cannot dump object that contains ["celerite"](https://github.com/dfm/celerite) class,  when I use Python 2.

The error is:

File "/home/trifonov/.local/lib/python2.7/site-packages/dill/_dill.py", line 270, in load
return Unpickler(file, ignore=ignore, **kwds).load()
File "/home/trifonov/.local/lib/python2.7/site-packages/dill/_dill.py", line 472, in load
obj = StockUnpickler.load(self)
File "/usr/lib64/python2.7/pickle.py", line 864, in load
dispatchkey
File "/usr/lib64/python2.7/pickle.py", line 1089, in load_newobj
obj = cls.new(cls, *args)
TypeError: pybind11_object.new(celerite.solver.CholeskySolver) is not safe, use object.new()

Also reported here:
https://github.com/dfm/celerite/issues/145

**Comment by mmckerns** [comment]
@3fon3fonov: when issue reporting, you should provide a minimal code sample that produces the error and traceback you are seeing (and also include the full traceback).

Looks like in the above, `dill` just hands off to `pickle`, and the `pickle` rejects serializing the object.  A quick look at `celerite` shows me that there's non-python code in the package, so it quite possibly is that the object has a non-python component -- which then can't serialize -- unless you would add a method to the relevant class instructing it how to serialize the class.  You'd need to get the package maintainers to handle that within their code.  Again, the easiest solution (I expect... as you haven't provided all the necessary information) would be to have the package maintainers add a reduction method to the class object.

**Comment by mmckerns** [comment]
This is probably something to handle outside of `dill` , with a [reduce method](https://docs.python.org/3/library/pickle.html#object.__reduce__), as stated above.  So, you may want to close this ticket.

Also, if you want better diagnostics, you might try to pickle the object again with `dill.trace(True)`.

**Comment by 3fon3fonov** [comment]
Hi @mmckerns !

Thanks for your replay! Now, as I said earlier I don't really believe the problem is in "dill" but it is very
strange that it works with Python 3 but it does notwith Python 2. 

FYI, here is the replay from the "celerite" author:

https://github.com/dfm/celerite/issues/145

which points to:

https://discuss.pytorch.org/t/pybind11-object-new-topleveltracedmodule-is-not-safe-use-object-new/32206

So this seems to be out of our hands, but is anoying because it means that [my too](https://github.com/3fon3fonov/exostriker)l cannot be used with Python2 anymore.
