### ISSUE TITLE
Can't get `dill.source.getsource` to work in PyCharm

### ISSUE THREAD

**Issue by amine-aboufirass** [uqfoundation/dill#359]
I am working with the following:

- python version 3.6.7
- dill version :
```
# Name                    Version                   Build  Channel
dill                      0.3.1.1          py36h9f0ad1d_1    conda-forge
```
 
In a regular python interpreter in PyCharm I am running the following commands:

```
>>> def f(x): return x+1
>>> import dill
>>> dill.source.getsource(f)
```

The last line throws the following error:

> Traceback (most recent call last):
>   File "<input>", line 1, in <module>
>   File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\fipy-dev\lib\site-packages\dill\source.py", line 354, in getsource
>     lines, lnum = getsourcelines(object, enclosing=enclosing)
>   File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\fipy-dev\lib\site-packages\dill\source.py", line 325, in getsourcelines
>     code, n = getblocks(object, lstrip=lstrip, enclosing=enclosing, locate=True)
>   File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\fipy-dev\lib\site-packages\dill\source.py", line 251, in getblocks
>     lines, lnum = findsource(object)
>   File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\fipy-dev\lib\site-packages\dill\source.py", line 154, in findsource
>     raise IOError('could not extract source code')
> OSError: could not extract source code
> 

When running from a script however, this seems to work fine.

**Comment by mmckerns** [comment]
I think this is a compatibility issue with pycharm, not `dill` itself.  I tested your version of `dill` and python on Windows, and it works fine.    It's known that `dill.source` and `IPython` have some compatibility issues, so I'm assuming that interaction with pycharm is the issue.  Can you try an interpreter without using pycharm (e.g. in the command shell)?

**Comment by awa5114** [comment]
I tried and it works outside of pycharm. I will log an issue with Pycharm. Thanks.

**Comment by mmckerns** [comment]
Can you link the issue with this one?  On cross-comparability issues, any mods may need to be made here or there, or both.

**Comment by awa5114** [comment]
@mmckerns here it is

https://youtrack.jetbrains.com/issue/PY-41239

I still didn't get a response on it though...

**Comment by mmckerns** [comment]
Cross-module compatibility issues can take a while.  Hopefully you get some movement on it here or there.
