### ISSUE TITLE
dump_session to a io.stringIO?

### ISSUE THREAD

**Issue by hotsoupisgood** [uqfoundation/dill#364]
Hey, I want to dump the session to a string rather than a file so I can put it in a database. But I am getting an error when I do:
`output = io.StringIO()  `
`dill.dump_session(filename=output)`

The error is:
`TypeError: string argument expected, got 'bytes'`

Any fixes are appreciated!

**Comment by effigies** [comment]
`io.BytesIO`?

**Comment by mmckerns** [comment]
@hotsoupisgood: do you actually need a string (not bytes) object for the database?  Because, if you do, then you should be able to convert with `decode` (i.e. `output.decode('ascii')`).  If this doesn't answer your question, then please reopen.
