### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by djarecka** [uqfoundation/dill#369]
http://trac.mystic.cacr.caltech.edu/project/pathos from README doesn't work

**Comment by mmckerns** [comment]
Thanks for the ping.  Recently (a few days ago), there was a power event at Caltech where the legacy project pages are housed, and they have not put the legacy site back online yet.  I've been in touch with Caltech, and assume they will get the site back online at some point in the near future.  If not, I'll need to make some changes.

**Comment by mmckerns** [comment]
Follow-up.  Caltech has modified their FQDN, so the link is going to be modified slightly.  The solution is to come up with a perm-link that removes the legacy Caltech from the URL. Legacy site is actually hosted here: http://trac.mystic.cacr.caltech.edu.s3-website-us-west-2.amazonaws.com/project/pathos/wiki/dill.html, but there will be some other shorter URL that will be used going forward.

**Comment by mmckerns** [comment]
Updated links/redirects here: https://github.com/uqfoundation/dill/commit/19d24fa9c514dccf71e5c5fd33d6c691388b9e0d. Most public sites are updated, with the exception of those that update upon release... so I'm closing this.  Thanks for reporting.
