### ISSUE TITLE
Unpickling Python 3 function in Python 2?

### ISSUE THREAD

**Issue by Peter92** [uqfoundation/dill#378]
The industry I work in still primarily uses Python 2, and since I've just asked IT to get Py3 installed on every machine, I've been attempting to upgrade a process wrapper I made earlier, to allow you to execute functions from Python 3 in Python 2 (some libraries are not 3 compatible yet).

I've now got to the point it's _almost_ working, but I've hit an issue and I'm honestly not sure if it's a limitation of Python, or if there's something that could be done. 

I understand that it's an issue nobody else is likely to have, but it'd be cool if there was a little tweak I could do to get it working.

Works in Python 3, breaks in Python 2:
```python
s = 'gAJjZGlsbC5fZGlsbApfY3JlYXRlX2Z1bmN0aW9uCnEAKGNkaWxsLl9kaWxsCl9sb2FkX3R5cGUKcQFYCAAAAENvZGVUeXBlcQKFcQNScQQoSwBLAEsCSwNLT2NkaWxsLl9kaWxsCl9nZXRfYXR0cgpxBWNkaWxsLl9kaWxsCl9pbXBvcnRfbW9kdWxlCnEGWAcAAABfY29kZWNzcQeFcQhScQlYBgAAAGVuY29kZXEKhnELUnEMWA8AAAB0AHwAfAHCgwIBAGQBUwBxDVgGAAAAbGF0aW4xcQ6GcQ9ScRBOSwGGcRFYBQAAAHByaW50cRKFcRNYBAAAAGFyZ3NxFFgGAAAAa3dhcmdzcRWGcRZYJwAAAGM6L0JsdWUtWm9vL1BpcGVsaW5lL2J6L2FwcHMvZXhlY3V0ZS5weXEXWAQAAABmdW5jcRhNRQFoDFgEAAAAAAEKAXEZaA6GcRpScRspKXRxHFJxHWNfX2J1aWx0aW5fXwpfX21haW5fXwpoGE5OfXEeTnRxH1JxIC4='
dill.loads(base64.b64decode(s))
```

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\resources\lib\python\site-packages\dill\_dill.py", line 275, in loads
    return load(file, ignore, **kwds)
  File "C:\resources\lib\python\site-packages\dill\_dill.py", line 270, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "C:\resources\lib\python\site-packages\dill\_dill.py", line 472, in load
    obj = StockUnpickler.load(self)
  File "C:\Python27_x64\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "C:\Python27_x64\lib\pickle.py", line 1139, in load_reduce
    value = func(*args)
TypeError: code() takes at most 14 arguments (15 given)
````

**Comment by matsjoyce** [comment]
I think your endeavor may me doomed even if this is fixed, because the bytecode used in py3 is different to py2. Unless you can somehow translate bytecode (essentially write a py3 VM running on the py2 VM) this isn't going to work.

The particular issue you have hit is because the py3 dill serializes the code to a call to the py3 code function, which doesn't work for the py2 code function. You could modify the py3 dill to produce code for the py2 code function, but due to the above problem, I doubt it will work.

Using some sort of RPC system is probably a better solution for calling py3 from py2.

**Comment by Peter92** [comment]
Thanks for the reply, I was really hoping using an older pickle protocol would somehow allow it to be compatible.

If a complex case is required in the future, I may be able to spawn a new process and setup the function in that, it's just a shame I'll have to manually code it each time it's needed.

**Comment by matsjoyce** [comment]
No, the way dill serializes functions is _very_ version dependant. It is not even compatible between different py3 versions if there has been a bytecode change between those versions. That is the reason pickle does not serialise functions, only references to functions. If you need py2-3 compatibility, you need to use pure pickle, without dill.

If you want a transparent interface between py2 and 3, something like [Pyro](https://pyro5.readthedocs.io/en/latest/) may be useful, or just liberal use of subprocesses. Most things in Python can be smoothed over if you throw enough decorators and metaclasses at it.

**Comment by Peter92** [comment]
Oh right thanks, that's extremely useful to know then, I've been passing data from 2.7.17 down to 2.7.3 just fine, but that's gonna throw a huge spanner in the works when some of our software gets updated to different py3 versions.

I think pyro is probably quite overkill for my needs, this will only be run by individual users for a few minutes at a time. I'll have to give it some proper thought tomorrow, the important bit I guess will be to find a robust way to reconstruct a class without `dill` to avoid the bytecode issues. I'll try remain using `multiprocessing` for efficiency, then fall back to `subprocessing` for sending between 2 and 3.

**Comment by mmckerns** [comment]
@matsjoyce: python doesn't even guarantee python2-3 compatible pickles... the only guarantee is within the same (minor, and I believe typically, major) version.   Cross-version compatibility is something that has been long desired, and I still see no light at the end of the tunnel.

**Comment by matsjoyce** [comment]
The pickle docs say:

> The pickle serialization format is guaranteed to be backwards compatible across Python releases provided a compatible pickle protocol is chosen and pickling and unpickling code deals with Python 2 to Python 3 type differences if your data is crossing that unique breaking change language boundary.

So I think that means that it is compatible inside py2 or py3, but not across. I guess that just leaves JSON and XML.

**Comment by Peter92** [comment]
Cheers for the replies guys, I've just managed to get the module working. Using protocol 2, pickle does indeed appear to work fine between 3.7 and 2.7. I'm sending the class instance, name of the method, and args/kwargs across the versions without any trouble (it's a somewhat complex setup to receive output and exceptions for - 3.8 loads 2.7, then 2.7 loads the required program).

It's a shame I'm having to move away from directly sending the bytecode, but at least this'll stay working for the cases I need it for :)
