### ISSUE TITLE
Wheel support for linux aarch64/x86

### ISSUE THREAD

**Issue by odidev** [uqfoundation/dill#384]
**Summary**
Installing dill on aarch64/x86 via pip using command "pip3 install dill" tries to build wheel from source code

**Problem description**
dill doesn't have wheel for aarch64/x86 on PyPI repository. So, while installing dill via pip on aarch64/x86 machine, pip builds the source code resulting in it takes more time to install dill. Making wheel available for aarch64/x86 will benefit aarch64/x86 users by minimizing dill installation time.

**Expected Output**
Pip should be able to download dill wheel from PyPI repository rather than building it from source code.

@dill-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make dill wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by mmckerns** [comment]
@odidev: It's in the current plan that the next release will have wheels.  The release will happen next month.  We build wheels for other codes, but for whatever reason, hadn't for `dill` yet.  The resulting wheels should be platform-independent. I'm not that familiar with aarch64, does ARM require something platform-specific?

**Comment by mmckerns** [comment]
@odidev: added a universal wheel in the latest release.  let me know if that works for you

**Comment by mmckerns** [comment]
if this still doesn't work for you, then please reopen this ticket
