### ISSUE TITLE
Pickling functions that have their own imports

### ISSUE THREAD

**Issue by batearedcollie** [uqfoundation/dill#385]
Hi, 

I am experiencing issues when trying to running pickled functions like 

```
def CustomFunction():
    import numpy as np
    arr = np.linspace(0,10,11)
    return np.max(arr)
```

I can export the function using something like 

```
base64.b64encode( dill.dumps(CustomFunction) ).decode('ascii')
```

And import it again 

```
dill.loads(base64.b64decode(functionstring))
```

But when I call it I get an import error

```
    import numpy as np
ImportError: __import__ not found
```

This error does not happen if the function is written like so  

```
import numpy as np

def CustomFunction():
    arr = np.linspace(0,10,11)
    return np.max(arr)
```

I am guessing because dill pickles the local environment. But sometimes it is helpful to perform imports inside the function, although I appreciate this might not always be best practice.

Any suggestions for how to pickle functions that perform their own imports would be gratefully received. 

Thanks

**Comment by mmckerns** [comment]
@batearedcollie: I'm not sure what you are trying to do, so please clarify.  For example, what's the purpose of the decoding, etc?

`dill` actually pickles more than the local environment.  It can pickle the global environment, and with functions this is often the case.  There are several variants for how `dill` can trace objects that are needed to properly serialize any object. Also, generally, pickling works much better if the imports are encapsulated in the function, as opposed to exterior.  I've tested your function on all supported versions of python (but not on windows), and I don't see any issues with pickling your function.

>>> def customfunction():
...     import numpy as np
...     arr = np.linspace(0,10,11)
...     return np.max(arr)
... 
>>> import dill
>>> dill.dumps(customfunction)
b'\x80\x03cdill._dill\n_create_function\nq\x00(cdill._dill\n_create_code\nq\x01(K\x00K\x00K\x02K\x04KCC d\x01d\x00l\x00}\x00|\x00j\x01d\x01d\x02d\x03\x83\x03}\x01|\x00j\x02|\x01\x83\x01S\x00q\x02(NK\x00K\nK\x0btq\x03X\x05\x00\x00\x00numpyq\x04X\x08\x00\x00\x00linspaceq\x05X\x03\x00\x00\x00maxq\x06\x87q\x07X\x02\x00\x00\x00npq\x08X\x03\x00\x00\x00arrq\t\x86q\nX\x07\x00\x00\x00<stdin>q\x0bX\x0e\x00\x00\x00customfunctionq\x0cK\x01C\x06\x00\x01\x08\x01\x0e\x01q\r))tq\x0eRq\x0fc__builtin__\n__main__\nh\x0cNN}q\x10Ntq\x11Rq\x12.'
>>> 

and in a new session
>>> import dill
>>> s = b'\x80\x03cdill._dill\n_create_function\nq\x00(cdill._dill\n_create_code\nq\x01(K\x00K\x00K\x02K\x04KCC d\x01d\x00l\x00}\x00|\x00j\x01d\x01d\x02d\x03\x83\x03}\x01|\x00j\x02|\x01\x83\x01S\x00q\x02(NK\x00K\nK\x0btq\x03X\x05\x00\x00\x00numpyq\x04X\x08\x00\x00\x00linspaceq\x05X\x03\x00\x00\x00maxq\x06\x87q\x07X\x02\x00\x00\x00npq\x08X\x03\x00\x00\x00arrq\t\x86q\nX\x07\x00\x00\x00<stdin>q\x0bX\x0e\x00\x00\x00customfunctionq\x0cK\x01C\x06\x00\x01\x08\x01\x0e\x01q\r))tq\x0eRq\x0fc__builtin__\n__main__\nh\x0cNN}q\x10Ntq\x11Rq\x12.'
>>> 
>>> f = dill.loads(s)
>>> f()
10.0
>>>

**Comment by batearedcollie** [comment]
I am experimenting with a mechanism for running functions inside docker containers. My original plan was to encode the function into JSON (hence the encode/decode) in order to export it to the container. However, It appears the encoding/ decoding messes with parts of the pickle. I can verify that using binary strings (as above) or dumping the pickle to a file works. 

So the easy workaround is to write the pickled function to a file and then transfer that filename to the container via JSON, the container can then read in the pickle file and do the work. 

Thanks for your help with this.

**Comment by matsjoyce** [comment]
You could base64 encode the pickle, then put it into JSON.

**Comment by mmckerns** [comment]
@batearedcollie: I encourage you to look at one of my other codes, `klepto`, which has encoding and decoding of pickled objects, and storage in files of different formats (SQL, HDF, etc).  If nothing else, it might give you some ideas.

Close this issue if/when you feel like you have a sufficient response.

**Comment by batearedcollie** [comment]
Thanks will do. And thanks once again for your help here.
