### ISSUE TITLE
TypeError: cannot pickle 'dict_keys' object

### ISSUE THREAD

**Issue by anne-leroy-T** [uqfoundation/dill#390]
Hi,

I got this message when using dill.dump_session 
I have dictionary objects in my session but I saw in the doc that they were supported.

Any idea ?
Thanks.

**Comment by mmckerns** [comment]
Duplicate of #353

**Comment by anne-leroy-T** [comment]
ok; so the answer is "dictionary is unsupported" ?

**Comment by mmckerns** [comment]
No, `dict` objects are fully serializable, so a dictionary is fully supported.  Iterator-based objects (such as a `dict_keys` object) are generally not yet supported.
