### ISSUE TITLE
Can't dump_session with inline plots

### ISSUE THREAD

**Issue by niallrobinson** [uqfoundation/dill#4]
dump_session() seems to fail when used with ipython notebook set up for inline plots. When the `%matplotlib inline` magic is used you get a traceback resulting in 
`PicklingError: Can't pickle 'RendererAgg' object: <RendererAgg object at 0x42a2bb8>`
and when using the `--pylab=inline` option at start up you get a traceback resulting in
`PicklingError: Can't pickle <class 'matplotlib.axes.AxesSubplot'>: it's not found as matplotlib.axes.AxesSubplot`

Using Dill 0.2a.dev, ipython 1.1.0

**Comment by mmckerns** [comment]
FYI: this likely has become a lot easier as of #101.
