### ISSUE TITLE
Is dill secure?

### ISSUE THREAD

**Issue by jakiki6** [uqfoundation/dill#402]
Is it safe to unpack untrusted data with dill?
pickle has some issues with code execution.

e.g.
`pickle.loads(b"cos\nsystem\n(S'ls'\ntR.")`

**Comment by matsjoyce** [comment]
Dill has all of the security problems of pickle, and more. So no, it is not secure. If you need security, either get trusted data with a valid cryptographic signature, or use a less risky format like JSON, YAML or XML.

**Comment by jakiki6** [comment]
ok
