### ISSUE TITLE
dill can't load classes derived from torch.nn.Module

### ISSUE THREAD

**Issue by renatolfc** [uqfoundation/dill#408]
Assume you have a simple PyTorch model such as the one below. In regular Python code, it would live in its own Python module, but when defined in ipython/jupyter, it would live in `__main__`:

```python
import torch
import torch.nn

class LR(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.lr = torch.nn.Linear(1, 1)
    def forward(self, x):
        return self.lr(x)

model = LR()
```

Now, suppose you are using dill to serialize this model (for example, to submit it for remote training with ipyparallel, or just to load it later, or in another process). You would probably just call

```python
import dill
dill.dump_session('/tmp/lr.pkl')
```

Which would work fine. Unfortunately, though, deserialization would fail:

```python
>>> dill.load_session('/tmp/lr.pkl')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venvs/dill/lib/python3.9/site-packages/dill/_dill.py", line 376, in load_session
    module = unpickler.load()
  File "/tmp/venvs/dill/lib/python3.9/site-packages/dill/_dill.py", line 481, in load
    obj = StockUnpickler.load(self)
  File "/tmp/venvs/dill/lib/python3.9/site-packages/dill/_dill.py", line 471, in find_class
    return StockUnpickler.find_class(self, module, name)
AttributeError: Can't get attribute 'LR' on <module '__main__' (built-in)>
```

One could try serializing just the class definition, in hopes that it would work (`with open('/tmp/lr', 'wb') as fp: dill.dump(LR, fp)`), but it fails with the same exception.

I've also tried registering a serializer specific to PyTorch using `@dill.register` and implemented with `torch.save`/`torch.load`, but that fails as well.

If the developers can point me a direction to investigate, I might be able to contribute a PR to fix this.

Versions tested:
Python: 3.9.2
Pytorch: 1.7.1 & 1.8.1
Dill: 0.3.3

**Comment by mmckerns** [comment]
I expect that the easiest thing to do is to add `__reduce__` and `__set_state__` methods to the `LR` class.  However, if that doesn't work, you'll probably want to see what is happening when the serialization is happening, which you can do with `dill.detect.trace(True)`.  You can also try alternate serialization settings, such as `dill.settings['recurse'] = True`.  If you have trouble interpreting the trace, you can post it here and I'll help interpret it.

**Comment by renatolfc** [comment]
Thanks @mmckerns, both suggestions seem to work.

Is it "safe" to always use `recurse=True`, or is there something I should be wary about?

**Comment by mmckerns** [comment]
@renatolfc: It's just a serialization variant.  Basically, the three main ones are `byref` -- which is similar to how `pickle` works, `recurse` -- which is similar to how `cloudpickle` works, and the default for `dill`'s default behavior.   You can use whatever works, and you can choose the setting on a per-object basis, as a keyword in `dump`.

**Comment by mmckerns** [comment]
If you feel this issue is no longer needed, then close it.  Or... if you want to push forward with a related PR, then leave it open, if it's still relevant.

**Comment by renatolfc** [comment]
Thanks for the clarification. I don’t think a PR is needed for this, so I’m closing this issue.
