### ISSUE TITLE
Using dill to pass between functions?

### ISSUE THREAD

**Issue by aronchick** [uqfoundation/dill#409]
I have a distribute app that executes two containers serially. I'd love to use dill to export the state of a python script in one container to be an input in the second container.

My thought was to convert the current state to a string, and pass it as a parameter. But when approaching a trivial function like this: 

```
import dill
import os
import io
import locale


def fun1():
    def my_func(a):
        return a * a

    output = io.BytesIO()
    dill.dump_session(filename=output)
    output.getbuffer()
    os.environ["PASSED_PARAMS"] = str(
        output.getvalue(), encoding=locale.getdefaultlocale()[1]
    )
```

I get the following error:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

I've dug through the code and can't quite figure out what the default encoding for the file is - any ideas here?

(small aside, have you checked to see if dill supports python 3.9? i was having a weird problem with pickling going back to the system pickle function until i moved back to 3.8, but it could have been a venv problem)

**Comment by matsjoyce** [comment]
The encoding is pickle-specific, so you should treat it as an arbitrary bytestring. If you want to pass it around as a utf-8 string, first encode it with something like base64 (https://docs.python.org/3/library/base64.html#base64.b64encode). You will then need to do the corresponding decode on the other side.

**Comment by aronchick** [comment]
makes sense - thanks!
________________________________

**Comment by mmckerns** [comment]
@aronchick: with regard to your aside, we are not seeing any new failures on our test cases for `dill` with python 3.9.  If you have experienced something in particular, then open an new issue.

**Comment by aronchick** [comment]
No worries - i'm sure it was just a weird venv issue.

It was just hard to debug because it appeared that dill was falling through to use system pickling (and I was getting an error with not being able to support ellipsis) Thanks for all your work!

**Comment by mmckerns** [comment]
You can turn on pickle tracing, with`dill.detect.trace`, for help diagnosing what is happening during serialization.

```
>$ python
Python 3.9.2 (default, Mar 18 2021, 05:36:08) 
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dill
>>> dill.load_types()
>>> dill.detect.trace(True)
>>> dill.dumps(dill.objects['EllipsisType'])
Si: Ellipsis
F2: <function _eval_repr at 0x1105c98b0>
# F2
# Si
b'\x80\x04\x95,\x00\x00\x00\x00\x00\x00\x00\x8c\ndill._dill\x94\x8c\n_eval_repr\x94\x93\x94\x8c\x08Ellipsis\x94\x85\x94R\x94.'
>>> dill.loads(_)
Ellipsis
>>> dill.dumps(lambda x: x)
F1: <function <lambda> at 0x11021a1f0>
F2: <function _create_function at 0x1105c9040>
# F2
Co: <code object <lambda> at 0x116091a80, file "<stdin>", line 1>
F2: <function _create_code at 0x1105c90d0>
# F2
# Co
D1: <dict object at 0x110126bc0>
# D1
D2: <dict object at 0x1160a5f00>
# D2
# F1
b'\x80\x04\x95\x96\x00\x00\x00\x00\x00\x00\x00\x8c\ndill._dill\x94\x8c\x10_create_function\x94\x93\x94(h\x00\x8c\x0c_create_code\x94\x93\x94(K\x01K\x00K\x00K\x01K\x01KCC\x04|\x00S\x00\x94N\x85\x94)\x8c\x01x\x94\x85\x94\x8c\x07<stdin>\x94\x8c\x08<lambda>\x94K\x01C\x00\x94))t\x94R\x94c__builtin__\n__main__\nh\nNN}\x94Nt\x94R\x94.'
```
