### ISSUE TITLE
Using Dill to transparently import/export globals & locals?

### ISSUE THREAD

**Issue by aronchick** [uqfoundation/dill#410]
Hi -- I'm trying to serialize state across container boundaries, and I've mocked up the code like this:
```python
import dill
from base64 import urlsafe_b64encode


def fun1():
    value_one = "abcdef"

    def sub_fun_one(x):
        return x * x

    __context_export = {}

    __context_export["globals"] = dill.dumps(globals())
    __context_export["locals"] = dill.dumps(locals())
    b64_string = str(urlsafe_b64encode(dill.dumps(__context_export)), encoding="ascii")

    print(b64_string)

fun1()
```

This outputs the following (as expected): `gASVdwEAAAAAAAB9lCiMB2dsb2JhbHOUQyKABJUXAAAAAAAAAGNfX2J1aWx0aW5fXwpfX21haW5fXwoulIwGbG9jYWxzlEI0AQAAgASVKQEAAAAAAAB9lCiMCXZhbHVlX29uZZSMBmFiY2RlZpSMC3N1Yl9mdW5fb25llIwKZGlsbC5fZGlsbJSMEF9jcmVhdGVfZnVuY3Rpb26Uk5QoaASMDF9jcmVhdGVfY29kZZSTlChLAUsASwBLAUsCS1NDCHwAfAAUAFMAlE6FlCmMAXiUhZSMMS9ob21lL2RhYXJvbmNoL2NvZGUvc2FtZS1jbGkvZXhwZXJpbWVudGFsL2Z1bjEucHmUaANLCEMCAAGUKSl0lFKUY19fYnVpbHRpbl9fCl9fbWFpbl9fCmgDTk59lE50lFKUjBBfX2NvbnRleHRfZXhwb3J0lH2UjAdnbG9iYWxzlEMigASVFwAAAAAAAABjX19idWlsdGluX18KX19tYWluX18KLpRzdS6UdS4=`

Then in the second function, the mock up looks like this:
```python
import dill
from base64 import urlsafe_b64decode


def fun2(import_string):
    __base64_decode = urlsafe_b64decode(import_string)
    __context_import_dict = dill.loads(__base64_decode)
    __globals_import = dill.loads(__context_import_dict["globals"])
    __locals_import = dill.loads(__context_import_dict["locals"])
    print(__context_import_dict)
    globals().update(__globals_import)
    locals().update(__locals_import)

    print(value_one)
    print(f"Square value: {sub_fun_one(5)}")


import_value = "gASVdwEAAAAAAAB9lCiMB2dsb2JhbHOUQyKABJUXAAAAAAAAAGNfX2J1aWx0aW5fXwpfX21haW5fXwoulIwGbG9jYWxzlEI0AQAAgASVKQEAAAAAAAB9lCiMCXZhbHVlX29uZZSMBmFiY2RlZpSMC3N1Yl9mdW5fb25llIwKZGlsbC5fZGlsbJSMEF9jcmVhdGVfZnVuY3Rpb26Uk5QoaASMDF9jcmVhdGVfY29kZZSTlChLAUsASwBLAUsCS1NDCHwAfAAUAFMAlE6FlCmMAXiUhZSMMS9ob21lL2RhYXJvbmNoL2NvZGUvc2FtZS1jbGkvZXhwZXJpbWVudGFsL2Z1bjEucHmUaANLCEMCAAGUKSl0lFKUY19fYnVpbHRpbl9fCl9fbWFpbl9fCmgDTk59lE50lFKUjBBfX2NvbnRleHRfZXhwb3J0lH2UjAdnbG9iYWxzlEMigASVFwAAAAAAAABjX19idWlsdGluX18KX19tYWluX18KLpRzdS6UdS4="
fun2(import_value)
```

But when i do this, even though `value_one` and `sub_fun_one` appear in globals() and locals(), I get this error:  
`NameError: name 'value_one' is not defined`

I tried using dump_session to accomplish this, but I couldn't see anything. Any suggestions?

**Comment by matsjoyce** [comment]
This is not a dill issue. According to the documentation of [`locals()`](https://docs.python.org/3/library/functions.html#locals):
> *Note* The contents of this dictionary should not be modified; changes may not affect the values of local and free variables used by the interpreter.

Also see https://stackoverflow.com/questions/4997184/why-is-it-bad-idea-to-modify-locals-in-python. If you want to execute some code in the unpickled locals, use `exec()`.

**Comment by aronchick** [comment]
Oh thank you! I wonder if there's a better way to get at what I'm doing here - i'm trying to serialize both variables and functions across a boundary.

It's not about executing code specifcially - just recreating the original environment without prefixes - e.g. 

```
# preferred 
value_one

# works, but not preferred 
__locals_import["value_one"]
```

**Comment by aronchick** [comment]
Ok, it APPEARS the following works:
```
    for k in __context_import_dict:
        if globals().get(k) is None:
            globals()[k] = dill.loads(__context_import_dict[k])
```

What kind of pain am i signing myself up for?

**Comment by aronchick** [comment]
Lol - this isn't going to work either :( Just can't get 'value_one' to exist in locals() or globals()

Is load_session designed to get around this?

**Comment by matsjoyce** [comment]
I think<sup>[citation needed]</sup>, that load_session only updates globals, which works because globals() does not have the same restrictions as locals(). For example, the following works:
```py3
>>> globals().update({"a":1, "b":range(10)})
>>> a
1
>>> b
range(0, 10)
```

So as long as you don't need the values to be act like locals (or are happy to add a bunch of `global x` lines to the top of your function), it should work.

**Comment by aronchick** [comment]
Ok, I’ll give this a shot. Qq - in this context, what does it mean to “act like locals” mean?


________________________________

**Comment by mmckerns** [comment]
What @matsjoyce is suggesting should work in many cases -- but there will obviously be namespace conflict issues by populating the old local variables to globals.

You also might want to look at `dill.detect` where there's some work to support recreating `locals` for `dill.source`.  For example:
```
>>> def foo(x):
...   a = 1
...   def bar(y):
...     return a*x + y
...   return bar
... 
>>> import dill
>>> foo(5)
<function foo.<locals>.bar at 0x10aecde18>
>>> dill.detect.freevars(_)
{'a': 1, 'x': 5}
>>> 
```
Here, instead of messing with `locals`, it directly addresses the function objects (the code and the cells) where the local variables are stored.  For example;
```
>>> foo.__code__.co_cellvars
('a', 'x')
```
It's not a full solution, however.

**Comment by aronchick** [comment]
Yeah, there's no question there are going to be a lot of edge cases here. We'll have to work through this once we get it up and running.

**Comment by aronchick** [comment]
Been chatting with folks over here - https://stackoverflow.com/questions/67512918/dynamically-creating-variables-without-using-a-dict?noredirect=1#comment119333232_67512918

Feel free to comment (until they close it anyway).

BTW, this still doesn't work :(

```python
exec(f"global {k}")
vars(sys.modules[__name__])[k] = dill.loads(__context_import_dict[k])
```

**Comment by aronchick** [comment]
FWIW, here's a single block of code that reproduces the issue - am I going about this wrong?

--------
```python
def fun_1() -> str:
    import dill
    from base64 import urlsafe_b64decode, urlsafe_b64encode
    from types import ModuleType

    b = 100

    locals_keys = frozenset(locals().keys())
    global_keys = frozenset(globals().keys())
    __context_export = {}
    for val in locals_keys:
        if not val.startswith("_") and not isinstance(val, ModuleType):
            __context_export[val] = dill.dumps(locals()[val])

    for val in global_keys:
        if not val.startswith("_") and not isinstance(val, ModuleType):
            __context_export[val] = dill.dumps(globals()[val])

    b64_string = str(urlsafe_b64encode(dill.dumps(__context_export)), encoding="ascii")

    from collections import namedtuple

    output = namedtuple("FuncOutput", ["context"])
    return output(b64_string)


def fun_2(context):
    import dill
    from base64 import urlsafe_b64encode, urlsafe_b64decode
    from types import ModuleType
    from pprint import pprint as pp

    __base64_decode = urlsafe_b64decode(context)
    __context_import_dict = dill.loads(__base64_decode)
    pp(__context_import_dict)
    for k in __context_import_dict:
        val = dill.loads(__context_import_dict[k])
        if globals().get(k) is None and not isinstance(val, ModuleType):
            globals()[k] = val

    b = b + 20


output = fun_1()
fun_2(output[0])
```

**Comment by matsjoyce** [comment]
In order for the globals update to work, you need to add a `global b` line to `fun_2`:
```py3
def fun_2(context):
    import dill
    from base64 import urlsafe_b64encode, urlsafe_b64decode
    from types import ModuleType
    from pprint import pprint as pp

    __base64_decode = urlsafe_b64decode(context)
    __context_import_dict = dill.loads(__base64_decode)
    pp(__context_import_dict)
    for k in __context_import_dict:
        val = dill.loads(__context_import_dict[k])
        if globals().get(k) is None and not isinstance(val, ModuleType):
            globals()[k] = val

    global b

    b = b + 20
    print(b)
```

Otherwise it is looking for a local variable, which doesn't exist.

**Comment by aronchick** [comment]
The problem is, as I understand it, is that global is a parser command, which I’m not going to know unless I parse the original code and generate it in fun_2.

Is there a way to dynamically mount these variables in the second function?


________________________________

**Comment by matsjoyce** [comment]
I don't believe so. The parser must know while parsing whether a variable is global or local if the variable is assigned inside the function. If you can put the code into a big multiline string (or in a separate file which can be read), and then run it using `exec`, then you can provide the variables dynamically, since the parsing problem only exists inside functions (module-level is fine).

**Comment by aronchick** [comment]
Interesting - what about if I wrap the entire function here inside another function? I don’t THINK I can do the exec trick you mention, but maybe? I won’t know the variable names until runtime


________________________________

**Comment by matsjoyce** [comment]
If you can get the code in a string, you don't need to know the variable names. Just `exec(code_string, globals_dict, locals_dict)`.

**Comment by aronchick** [comment]
Ok, FWIW, I got it working and ... in the grand scheme of things... it's not hideous?

Given I'm already taking code, in my mind, wrapping the code inside an exec block and mounting env variables in actually makes a lot of sense to me. Here you go:

```python
def fun_1() -> str:
    import dill
    from base64 import urlsafe_b64decode, urlsafe_b64encode
    from types import ModuleType, FunctionType

    b = 100

    locals_keys = frozenset(locals().keys())
    global_keys = frozenset(globals().keys())
    __context_export = {}
    for val in locals_keys:
        if (
            not val.startswith("_")
            and not isinstance(val, ModuleType)
            and not isinstance(val, FunctionType)
        ):
            __context_export[val] = dill.dumps(locals()[val])

    for val in global_keys:
        if (
            not val.startswith("_")
            and not isinstance(val, ModuleType)
            and not isinstance(val, FunctionType)
        ):
            __context_export[val] = dill.dumps(globals()[val])

    b64_string = str(urlsafe_b64encode(dill.dumps(__context_export)), encoding="ascii")

    from collections import namedtuple

    output = namedtuple("FuncOutput", ["context"])
    return output(b64_string)


def fun_2(context):
    import dill
    from base64 import urlsafe_b64encode, urlsafe_b64decode
    from types import ModuleType, FunctionType
    from pprint import pprint as pp

    __base64_decode = urlsafe_b64decode(context)
    __context_import_dict = dill.loads(__base64_decode)

    variables = {}
    for k in __context_import_dict:
        variables[k] = dill.loads(__context_import_dict[k])

    loc = {}
    exec("b = b + 20", variables, loc)
    print(loc["b"])


output = fun_1()
fun_2(output[0])
```
