### ISSUE TITLE
[Enhancement] pickle function __annotations__

### ISSUE THREAD

**Issue by ghost** [uqfoundation/dill#420]
Hello,

Is it possible to implement function.__annotations__ pickle on loads / dumps ?

Br
Nick

**Comment by mmckerns** [comment]
I'm unclear as to what you are asking for.  Are you looking for `dumps.__annotations__` and `loads.__annotations__` to be added?

**Comment by NickFillot** [comment]
Yes, to add it natively in function serialization

**Comment by NickFillot** [comment]
See [https://github.com/uqfoundation/dill/pull/421](PullRequest)
