### ISSUE TITLE
Unpacking loaded object cause pylint error

### ISSUE THREAD

**Issue by Alalalalaki** [uqfoundation/dill#430]
I find when I unpack the file (which is a turple) that is loaded by dill, pylint reports `pylint(unpacking-non-sequence)`. This does not happen if I use pickle. 

```python
import dill as pickle
# import pickle

def read_file(file_name, path="../"):
    with open(path+file_name, 'rb') as f:
        file = pickle.load(f)
    return file

x, y, z = read_file("...")
```

![image](https://user-images.githubusercontent.com/31154974/136164716-7c307d63-4be9-4714-ba48-959293985c2b.png)

**Comment by Alalalalaki** [comment]
@mmckerns Sorry, but I think I have already given a minimal self-contained example. Maybe this is a problem of pylint rather than dill, though replacing dill with pickle make this error disappear.

**Comment by mmckerns** [comment]
@Alalalalaki: I meant: How have you written the tuple to the file?  Did you use pickle or dill?  What is the tuple composed of?  Is it intended the filename "../..."?

**Comment by Alalalalaki** [comment]
@matsjoyce Ok, I will consider muting this error.

@mmckerns I use dill to write a tuple to the file, which includes some numpy matrx and sklearn models. I use python 3.8.10 and dill 0.3.4.

**Comment by Alalalalaki** [comment]
@mmckerns That's strange. I lint no more than above code and run in terminal but the error appears. Sorry, maybe it's the problem of my environment. I will check if I can reproduce this error in a clean environment when I have time.

```
Code(main) $ pylint test.py
************* Module test
test.py:1:0: C0114: Missing module docstring (missing-module-docstring)
test.py:5:0: C0116: Missing function or method docstring (missing-function-docstring)
test.py:6:39: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
test.py:11:0: E0633: Attempting to unpack a non-sequence defined at line 97 of pickle (unpacking-non-sequence)

-------------------------------------------------------------------
Your code has been rated at -3.33/10 (previous run: 1.67/10, -5.00)
```

**Comment by Alalalalaki** [comment]
@Sorry I confirm that it's the problem of my environment. I update all packages and python to the latest version and then the error disappears.
