### ISSUE TITLE
dill.pickles() crashes on scipy.sparse.csr_matrix

### ISSUE THREAD

**Issue by jsbryaniv** [uqfoundation/dill#440]
I have found a crash here:

`import dill as pickle
from scipy import sparse

a = sparse.csr_matrix([[1, 2, 3], [4, 5, 6]])

pickle.pickles(a)`

returns:

`SparseEfficiencyWarning: Comparing sparse matrices using == is inefficient, try using != instead.
  pickle.pickles(a)
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tf/lib/python3.9/site-packages/dill/_dill.py", line 1547, in pickles
    if result: return True
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tf/lib/python3.9/site-packages/scipy/sparse/base.py", line 283, in __bool__
    raise ValueError("The truth value of an array with more than one "
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all().`

It seems that pickle.pickles() should be able to handle any object because it fundamentally is a function that tells you if the object can be pickled. In this case the way of determining whether or not a sparse matrix can be pickled causes a crash.

**Comment by mmckerns** [comment]
Yes, this it looks like this is a consequence of `if a` (essentially, `bool(a)`) where `a` is an array.  The if statement needs to be modified for arrays.
