### ISSUE TITLE
single `shims` function calls `move_to` and `Getattr`

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/dill#447]
The `@move_to` decorator must be paired with the overloading by the `Getattr` later in the `shims` module.  It seems like with a little redesign, this could be consolidated to a single function / decorator.

**Comment by mmckerns** [comment]
See #443 for reference.

**Comment by anivegesana** [comment]
This construct tries to give a base definition for a function that will be or was defined differently in another version of Python or dill. Because of this, should we just call both `move_to` and `Getattr` put together `soft_def`?

**Comment by mmckerns** [comment]
I was thinking about something along those lines, yes.

**Comment by anivegesana** [comment]
Do you do think there is any value in having a separate `Getattr` and `move_to` function along with a `soft_def` function? I guess we could add them back in if they are found to be useful for something else.

**Comment by mmckerns** [comment]
It doesn't hurt to keep them available as separate functions.
