### ISSUE TITLE
sunset pypy27 support

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/dill#453]
Discontinue support for pypy 2.7

**Comment by leogama** [comment]
Will support for CPython 2.7 continue? I thought you would drop both...

If dill becomes Python 3 only, which would be probably a major release (4.0), do you think it's a good opportunity to remove conditional logic for really old Python 3 versions? Even Debian "oldoldstable" uses Python 3.5 and Python 3 versions pre-installed in macOS are pretty recent (~ 3.7+). It would require a single, very careful, full code revision.

If you want I can help with this task. I don't understand very much about `pickle` internals —so would not even try to refractor something— but I'm well familiarized with the Python's syntax and library evolution in the last decade.

Beyond the current code, I'd like to know if there are any code conventions. For example, even if dill **supports** just CPython/PyPy's officially supported versions:
- Should it keep conditional code _that still works unmodified_ for versions one or two less than the oldest supported?
- Should it use only _syntax_ compatible with the version one or two below the oldest supported?

Both conditions have minor impact in the codebase and impose negligible maintenance hassle, but could make life much easier for users of unsupported Python versions that need just a subset of dill's functionality or want to backport it, if they really have to.

It could be something in this line...

Python version support:
- Supported >= 3.7
- Deprecated == 3.6 [DeprecationWarning, PyPI requirement]
- Syntax compatible == 3.5 [DeprecationWarning]
- Unsupported <= 3.4 [ImportWarning (if it loads at all)]

**Comment by mmckerns** [comment]
See issue #413, yes CPython 2.7 support will be dropped in the at the same time as pypy2.7.  Yes, it's an opportunity to clean out all the old logic from 3.1-3.6, and any of 2.x.  There's probably some lingering conditions from really old versions of 2.x.  No, I'm going to drop build support for python 2 and older versions of 3. If people want to continue to use `dill` for 2.7 or older 3, then they will need to use older releases. `dill` is often one of the packages that is slow to drop old versions of python, as it's users have to deal with unpicking old files that were created with old versions of python.

**Comment by leogama** [comment]
I think I understood the reasons. So that means that I may use all Python 3.7+ valid syntax for new code? Sweet!

**Comment by leogama** [comment]
> I'm going to drop build support for python 2 and older versions of 3.

What do you mean by "drop build support"? Will `setup.py` simply check the version and refuse to build? Or do you mean the build will fail for versions < 3.7 for other reasons?

Also, the PyPI package doesn't have a python version requirement for pip currently... Is it bad?
