### ISSUE TITLE
Pickling fails for immutable objects that occur in recursive structures

### ISSUE THREAD

**Issue by anivegesana** [uqfoundation/dill#458]
Minimal failure case:
```py
def f():
  d = {}
  def g():
    return d
  d['g'] = g
  return g

import dill
dill.dumps(f())
```

`g.__closure__` contains `g`, but not directly. Currently, `save_cell` only breaks cycles that directly contain the function, not collections or objects that contain the function.

CloudPickle's solution of breaking the cycles within functions as opposed to within cells (like dill does) may be undesirable in some situations:

```py
import cloudpickle

class C:
  def __init__(self, fx):
    self.fx = fx
    print(self.fx.d)
  def __reduce__(self):
    return (C, (self.fx,))

def f():
  t = ((lambda: t),)
  t[0].d = 0
  t[0].c = C(t[0])
  return t

pkl = cloudpickle.dumps(f())
cloudpickle.loads(pkl)
```
```pycon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in __init__
AttributeError: 'function' object has no attribute 'd'
```

Therefore, a more dynamic cycle breaking mechanism would be preferred, but tradeoffs of each method should be deliberated.

Another example:

uqfoundation/mystic@f6f71f5ffebe2a4c26319f54de83d75f625073c6

**Comment by mmckerns** [comment]
@anivegesana: I'm really hesitant to put out a new release that removes functionality, however we are at that point after your PR #443.  What are your plans for this issue?  I may have to roll back #443, or try to fix this issue, before I put out the next release.  I've been delaying it in hopes this gets resolved. Essentially, it's my fault that I didn't catch you'd removed functionality in #443. However, let me know what your plans are with addressing this, or if I need to do it.

**Comment by anivegesana** [comment]
I was unable to find any significant cases where cloudpickle's approach (break cycles in the functions) fails. The only two cases that their approach fails are ones where the `__closure__` member of a function is used in its own definition and ones that depend on the insertion order of `__dict__` (like the one I mentioned above.) Neither case would appear in normal Python code.

**Comment by mmckerns** [comment]
sounds like a good plan, thanks for the quick follow-up

**Comment by mmckerns** [comment]
@anivegesana: What do you want to do with this issue in light of #461 and #448?

**Comment by anivegesana** [comment]
I think we can close it. Although there are some objects that cannot be handled by the PR, a custom `__reduce__` function can be written to manually break the circularity. Another issue can be opened if this is not the case.
