### ISSUE TITLE
Pip installs package on unsupported Python versions 3.1 ... 3.6

### ISSUE THREAD

**Issue by andy-maier** [uqfoundation/dill#459]
Pip uses the package metadata created from the `python_requires` parameter of `setup()` to find out whether the package can be installed on a particular Python version.

The current master branch of this project specifies:
```
python_requires='>=2.7, !=3.0.*',
```
which allows Pip to install the package on Python 3.1 ... 3.6, which are not supported by this package according to the runtime check in setup.py.

The runtime check is not a very great solution to this problem, because the child has already fallen into the well (German saying) by the time that is done, i.e. Pip has already picked the wrong version to install.

The solution is to constrain this parameter to only the supported versions:
```
python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*, !=3.6.*',
```

Once that is done, the runtime check might as well be removed, but that is really up to you and I'm sure I don't have a complete overview on all the scenarios that drove you to have it in the first place.

Reference: https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#python-requires

**Comment by mmckerns** [comment]
Hm... I didn't realize that was still there.  I'll fix it. Thanks for the prompting.
