### ISSUE TITLE
dill.load report weird ModuleNotFound Error

### ISSUE THREAD

**Issue by YalingQing** [uqfoundation/dill#465]
I am calling dill.load on a file. And I got a very weird ModuleNotFoundError. I have no idea what the "adapted_data_to_input" module is. It is not a customized module. And it is not a released open-source module either. I also double-check and it is not a variable name. Do anyone know how to solve this problem?

Traceback (most recent call last):
  File "vis_graph_salad.py", line 33, in <module>
    temp = dill.load(f)
  File "/work/08582/yqing/maverick2/miniconda3/envs/aida/lib/python3.7/site-packages/dill/_dill.py", line 313, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/work/08582/yqing/maverick2/miniconda3/envs/aida/lib/python3.7/site-packages/dill/_dill.py", line 525, in load
    obj = StockUnpickler.load(self)
  File "/work/08582/yqing/maverick2/miniconda3/envs/aida/lib/python3.7/site-packages/dill/_dill.py", line 515, in find_class
    return StockUnpickler.find_class(self, module, name)
ModuleNotFoundError: No module named 'adapted_data_to_input'

**Comment by leogama** [comment]
Hello! I need some more information to help you:

How was this pickle file generated? Did you generate it (with `dill` or `pickle`) or did you get it from somewhere? Note that dill does most of its work in the `dump*()` functions. By the traceback, it's actually doing the equivalent of calling `pickle.load(f)` in this case. You can try it yourself and you should get the same error.

Note that if the object you are trying to load is an instance of a class from a local module (i.e. it's not in `PYTHONPATH`), then you *need to* load it in the same working directory from where such module was imported. In this case, the directory that contains the `adapted_data_to_input` module.

**Comment by mmckerns** [comment]
If you didn't create the pickled file, then you should probably contact the author of the file.  It sounds like you are missing a local module that needs to be loaded, as @leogama says.

**Comment by mmckerns** [comment]
I'm going to assume that this is resolved. Closing, but @YalingQing please reopen if it isn't resolved.
