### ISSUE TITLE
test failures for python 3.11a7

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/dill#467]
```
$ python test_detect.py; python test_temp.py; python test_recursive.py 
Traceback (most recent call last):
  File "/Users/mmckerns/dev/svn/pathos/dill/tests/test_detect.py", line 155, in <module>
    test_globals()
    ^^^^^^^^^^^^^^
  File "/Users/mmckerns/dev/svn/pathos/dill/tests/test_detect.py", line 71, in test_globals
    assert set(res) == set(['squared', 'a'])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/Users/mmckerns/dev/svn/pathos/dill/tests/test_temp.py", line 102, in <module>
    test_one_arg_functions()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mmckerns/dev/svn/pathos/dill/tests/test_temp.py", line 80, in test_one_arg_functions
    assert _obj(4) == obj(4)
           ^^^^^^^
  File "<string>", line 1, in g
NameError: name 'f' is not defined
Traceback (most recent call last):
  File "/Users/mmckerns/dev/svn/pathos/dill/tests/test_recursive.py", line 178, in <module>
    test_recursive_function()
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mmckerns/dev/svn/pathos/dill/tests/test_recursive.py", line 145, in test_recursive_function
    assert fib2(5) == 5
           ^^^^^^^
  File "/Users/mmckerns/dev/svn/pathos/dill/tests/test_recursive.py", line -1, in fib
NameError: name 'fib' is not defined
```

**Comment by anivegesana** [comment]
I believe that part of it might be that the code object constructor is different now and has a new argument:

https://docs.python.org/3.11/whatsnew/3.11.html#column-information-for-code-objects

More things might be at play, but that is the big one.

**Comment by mmckerns** [comment]
Maybe.  It seems that the errors don't show up in `3.11a6` and earlier.  If there's a new argument for the code constructor, then `_dill` needs to be updated to accommodate for that.

**Comment by anivegesana** [comment]
I retract what I said. I think the output is different in the REPL, in tox, and when running it directly, which is very strange. Maybe it is best to wait for the beta before supporting 3.11?

**Comment by mmckerns** [comment]
I'll do a bit more investigation into change and bug reports in python.  It might be best to add a single-version workaround for 3.11a7 if the one-line change is all that is needed.

**Comment by mmckerns** [comment]
It looks like this is related to changes associated with [CALL](https://docs.python.org/3.11/library/dis.html#opcode-CALL) and [PUSH_NULL](https://docs.python.org/3.11/library/dis.html#opcode-PUSH_NULL), although I'm not seeing when these changes were made (i.e. so they would first show up in 3.11a7).  It seems that there were significant changes to `dis` in 3.11.

**Comment by anivegesana** [comment]
I think that the changes are in function calls. The modification to `LOAD_GLOBAL` was to allow it to push `NULL` prior to pushing the global to the stack because that would be a common pattern in the bytecode and it would save CPU time to have that as one instruction. I guess that means that this is not a bug and the change is permanent.

The `if` statement isn't needed. The replacement would do nothing before Python 3.11.

**Comment by mmckerns** [comment]
I added the if as it should be roughly an order of magnitude faster than calling `replace` each time.  And, no, I agree, the change seems to be permanent, so I'm going to modify the if.
