### ISSUE TITLE
incorrect traceback from serialized function in python 3.10

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/dill#488]
The following code:
```
import traceback
import dill
#dill.settings['recurse'] = True
#dill.detect.trace(True)

def function(x):
    return 1/x

def modified_function(x):
    try:
        return 1/x
    except Exception as e:
        import traceback
        error = str(e)
        tb = traceback.format_exc()
        return type(e)(f"{e}\n\nOriginal {tb}")

if __name__ == '__main__':
    mapped_function = dill.loads(dill.dumps(modified_function))
    results = list(map(mapped_function, [0, 1, 2, 3]))
    print(results[0])
```
Results in an erroneous traceback in python 3.10, but not 3.7-3.9::
```
$ python3.10 div0err3.py 
division by zero

Original Traceback (most recent call last):
  File "/Users/mmckerns/div0err3.py", line 12, in modified_function
    except Exception as e:
ZeroDivisionError: division by zero

$ python3.9 div0err3.py 
division by zero

Original Traceback (most recent call last):
  File "/Users/mmckerns/div0err3.py", line 11, in modified_function
    return 1/x
ZeroDivisionError: division by zero
```
It seems that the pickling of the function in 3.10 is slightly off.
This bug is in `dill-0.3.5.1`; however, was also reported as being seen in `dill-0.3.4`.
The error is not seen with `pickle` (i.e. `import pickle as dill`).

Originating issue is here: https://github.com/uqfoundation/pathos/issues/238

**Comment by mmckerns** [comment]
```
Python 3.10.4 (main, May 10 2022, 03:02:03) [Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import traceback
>>> import dill
>>> #dill.settings['recurse'] = True
>>> #dill.detect.trace(True)
>>> 
>>> def function(x):
...     return 1/x
... 
>>> def modified_function(x):
...     try:
...         return 1/x
...     except Exception as e:
...         import traceback
...         error = str(e)
...         tb = traceback.format_exc()
...         return type(e)(f"{e}\n\nOriginal {tb}")
... 
>>> mapped_function = dill.loads(dill.dumps(modified_function))
>>> results = list(map(mapped_function, [0, 1, 2, 3]))
>>> print(results[0])
division by zero

Original Traceback (most recent call last):
  File "<stdin>", line 4, in modified_function
ZeroDivisionError: division by zero

>>> import pickle as dill
>>> mapped_function = dill.loads(dill.dumps(modified_function))
>>> results = list(map(mapped_function, [0, 1, 2, 3]))
>>> print(results[0])
division by zero

Original Traceback (most recent call last):
  File "<stdin>", line 3, in modified_function
ZeroDivisionError: division by zero

>>> 
```
also shows up in the interpreter, and/or when using `recurse`

**Comment by anivegesana** [comment]
This is because a ton of arguments to code objects were removed in Python 3.10. It should now be this:
```py
args = (
                obj.co_argcount, obj.co_posonlyargcount,
                obj.co_kwonlyargcount, obj.co_nlocals, obj.co_stacksize,
                obj.co_flags, obj.co_code, obj.co_consts, obj.co_names,
                obj.co_varnames, obj.co_filename, obj.co_name,
                obj.co_firstlineno, obj.co_linetable, obj.co_freevars,
                obj.co_cellvars
        )
```

Right now, this is a bit of a mess and it is hard to disambiguate different cases in `save_code` and `_create_code`. As mentioned in #480, we need a more principled way of dealing with dropped arguments to code.

**Comment by anivegesana** [comment]
Unfortunately, this is the best that I can come up with:

We create a couple of named tuples:
```py
class CodeArgs38(typing.NamedTuple):
  ...
class CodeArgs39(typing.NamedTuple):
  ...
class CodeArgs310(typing.NamedTuple):
  ...
...
```

At when we pickle the first code object, we also pickle an instruction to the dill pickler (just a function call that changes a `code_args_class` attribute of the current pickler according to the version of Python that was used for pickling). If `code_args_class` is `None`, default to current behavior.

@mmckerns @leogama @matsjoyce How does that sound?

**Comment by mmckerns** [comment]
@anivegesana: if you are interested in refactoring `save_code` and `_create_code`, then open up a new issue to discuss doing so.  Let's keep this issue focused on tracking down the reason the line number of the exception is off.  Note that the `args` you quote above are already in `save_code`, so I'm hesitant to believe that an argument mismatch in `save_code` and `_create_code` is the root cause of the issue here until some due diligence has been done.

**Comment by mmckerns** [comment]
Here's the trace run for 3.9:
```
$ python3.9 div0err3.py 
F1: <function modified_function at 0x1094b9940>
F2: <function _create_function at 0x1094a4310>
# F2
Co: <code object modified_function at 0x108f7e710, file "/Users/mmckerns/div0err3.py", line 9>
F2: <function _create_code at 0x1094a43a0>
# F2
# Co
D1: <dict object at 0x108f7d780>
# D1
D2: <dict object at 0x1094ae400>
# D2
D2: <dict object at 0x1091ac100>
D2: <dict object at 0x1091a89c0>
# D2
# D2
# F1
division by zero

Original Traceback (most recent call last):
  File "/Users/mmckerns/div0err3.py", line 11, in modified_function
    return 1/x
ZeroDivisionError: division by zero

```
and 3.10:
```
$ python div0err3.py 
F1: <function modified_function at 0x10d981750>
F2: <function _create_function at 0x10d970160>
# F2
Co: <code object modified_function at 0x10d491fd0, file "/Users/mmckerns/div0err3.py", line 9>
F2: <function _create_code at 0x10d9701f0>
# F2
# Co
D1: <dict object at 0x10d48f3c0>
# D1
D2: <dict object at 0x10d97c040>
# D2
D2: <dict object at 0x10d48f880>
D2: <dict object at 0x10d667c40>
# D2
# D2
# F1
division by zero

Original Traceback (most recent call last):
  File "/Users/mmckerns/div0err3.py", line 12, in modified_function
    except Exception as e:
ZeroDivisionError: division by zero

```
So, looks like the primary reason for the difference should be in the `_create_code` or `_create_function` code itself.

**Comment by mmckerns** [comment]
```
Python 3.9.13 (main, May 21 2022, 02:35:37) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import traceback
>>> import dill
>>> #dill.settings['recurse'] = True
>>> #dill.detect.trace(True)
>>> 
>>> def function(x):
...     return 1/x
... 
>>> def modified_function(x):
...     try:
...         return 1/x
...     except Exception as e:
...         import traceback
...         error = str(e)
...         tb = traceback.format_exc()
...         return type(e)(f"{e}\n\nOriginal {tb}")
... 
>>> mapped_function = dill.loads(dill.dumps(modified_function))
>>> fc = modified_function.__code__
>>> gc = mapped_function.__code__
>>> [arg for arg in dir(fc) if arg.startswith('co_') and getattr(fc, arg) != getattr(gc, arg)]
[]
```
and in 3.10
```
Python 3.10.4 (main, May 10 2022, 03:02:03) [Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import traceback
>>> import dill
>>> #dill.settings['recurse'] = True
>>> #dill.detect.trace(True)
>>> 
>>> def function(x):
...     return 1/x
... 
>>> def modified_function(x):
...     try:
...         return 1/x
...     except Exception as e:
...         import traceback
...         error = str(e)
...         tb = traceback.format_exc()
...         return type(e)(f"{e}\n\nOriginal {tb}")
... 
>>> mapped_function = dill.loads(dill.dumps(modified_function))
>>> mapped_function.__dict__ == modified_function.__dict__
True
>>> mapped_function.__closure__
>>> mapped_function.__defaults__
>>> fc = modified_function.__code__
>>> gc = mapped_function.__code__
>>> [arg for arg in dir(fc) if arg.startswith('co_') and getattr(fc, arg) != getattr(gc, arg)]
['co_lines', 'co_linetable', 'co_lnotab']
>>> fc.co_linetable
b'\x02\x01\n\x01\x0e\x01\x08\x01\x08\x01\x08\x01"\x01\x08\x80\x02\xfc'
>>> gc.co_linetable
b'\x00\x01\x02\x01\n\x01\x0e\x01\x08\x01\x08\x01\x08\x01*\xfc'
>>> fc.co_lnotab
b'\x00\x01\x02\x01\n\x01\x0e\x01\x08\x01\x08\x01\x08\x01*\xfc'
>>> gc.co_lnotab
b'\x00\x02\x02\x01\n\x01\x0e\x01\x08\x01\x08\x01\x08\xfc'
>>> 
```
Interestingly... it looks like a new things that python started doing in 3.10 is to use a line iterator. Not sure if this has something to do with it, but it could...

In 3.9:
```
>>> hasattr(fc, 'co_lines')
False
```
in 3.10:
```
>>> fc.co_lines()
<line_iterator object at 0x10639f7d0>
```

**Comment by mmckerns** [comment]
```
>>> import dis
>>> dis.dis(fc.co_lnotab)
          0 <0>
          2 ROT_TWO
          4 UNARY_POSITIVE
          6 <14>
          8 <8>
         10 <8>
         12 <8>
         14 <42>
>>> dis.dis(gc.co_lnotab)
          0 <0>
          2 ROT_TWO
          4 UNARY_POSITIVE
          6 <14>
          8 <8>
         10 <8>
         12 <8>
>>> dis.dis(fc.co_linetable)
          0 ROT_TWO
          2 UNARY_POSITIVE
          4 <14>
          6 <8>
          8 <8>
         10 <8>
         12 COPY_DICT_WITHOUT_KEYS
         14 <8>
         16 ROT_TWO
>>> dis.dis(gc.co_linetable)
          0 <0>
          2 ROT_TWO
          4 UNARY_POSITIVE
          6 <14>
          8 <8>
         10 <8>
         12 <8>
         14 <42>
```

**Comment by mmckerns** [comment]
Aha.
```
>>> from types import CodeType
>>> cc = CodeType(fc.co_argcount, fc.co_posonlyargcount, fc.co_kwonlyargcount, fc.co_nlocals, fc.co_stacksize, fc.co_flags, fc.co_code, fc.co_consts, fc.co_names, fc.co_varnames, fc.co_filename, fc.co_name, fc.co_firstlineno, fc.co_linetable, fc.co_freevars, fc.co_cellvars)
>>> cx = CodeType(fc.co_argcount, fc.co_posonlyargcount, fc.co_kwonlyargcount, fc.co_nlocals, fc.co_stacksize, fc.co_flags, fc.co_code, fc.co_consts, fc.co_names, fc.co_varnames, fc.co_filename, fc.co_name, fc.co_firstlineno, fc.co_lnotab, fc.co_freevars, fc.co_cellvars)
>>> 
>>> mapped_function.__code__ = cc
>>> print(mapped_function(0))
division by zero

Original Traceback (most recent call last):
  File "<stdin>", line 3, in modified_function
ZeroDivisionError: division by zero

>>> mapped_function.__code__ = cx
>>> print(mapped_function(0))
division by zero

Original Traceback (most recent call last):
  File "<stdin>", line 4, in modified_function
ZeroDivisionError: division by zero

>>> 
```
So, between 3.9 and 3.10, the number of arguments to build a `CodeType` didn't change, but `co_lnotab` was replaced with `co_linetable`. That could make it difficult in `_create_code` to know whether the pickled code was built in 3.9 or 3.10.  Maybe a good solution is to serialize an additional argument that indicates which version of python was used (i.e. which version of _create_code_ to use).

**Comment by mmckerns** [comment]
...I can wrap `co_linetable` in a tuple if it exists, and serialize that.  Then check for a tuple for that arg `create_code`.

**Comment by anivegesana** [comment]
Hmm. It is kind of odd that `_create_code` still works if you still give the removed argument `co_qualname`. Can't really find a reason why and it doesn't seem like there is an explicit check for it, but the function has many different cases which are hard to interpret.

I think the idea of adding an additional argument to indicate the version is a good idea and would avoid the complexity of the method I suggested while still being scalable in the future.

**Comment by mmckerns** [comment]
The change I'm referring to was executed here: https://peps.python.org/pep-0626/

Not sure what... if an extra argument for the version, or to serialize `(fc.co_linetable, fc.co_lnotab)` in 3.10 and on, or both... will work better.  Needs some fiddling to see what works.

**Comment by anivegesana** [comment]
If all else fails, we could just pass `b''` to drop all line number information. Not preferable, but there might not be anything we can do.

**Comment by leogama** [comment]
I've read through all the discussion, but I don't have any reasonable idea to tackle this without breaking compatibility.

After dropping Python 2 support, it would be great if dill could use Structural Pattern Macthing, as it fits perfectly to this kind of problem. But it's a far-fetched dream as this is exclusively a Python 3.10+ feature (with no plans to include it in `__future__`).

However, what do you think of a solution using a "backport" of Pattern Macthing like [pattern-matching-pep634](https://pypi.org/project/pattern-matching-pep634/)? It could be included either as a lightweight dependency or a streamlined copy of it to handle just the "variable length tuple of things" case of reductions. (The latter would be better for my proposed "portable" mode.)

This would produce much clearer code, less prone to bugs, and in the long future could be easily converted to built-in `match/case` statements. If you like the idea, I can provide a draft version for further discussions.

**Comment by mmckerns** [comment]
I've read already that python 3.12 will again change CodeType objects... and as noted in PEP626, `co_lnotab` is expected to be removed.  I've left in the case for python 3.11a, as I expect that could be the interface that is being planned for python 3.12.  It would be nice to make this code simpler to maintain.  One potential way would be to zip the args with a list of argnames, and then produce a dict, then work with the dict internally.
