### ISSUE TITLE
AttributeError: module 'dill._dill' has no attribute 'stack'

### ISSUE THREAD

**Issue by LolitaSian** [uqfoundation/dill#502]
AttributeError: module 'dill._dill' has no attribute 'stack'

what should I do.

**Comment by anivegesana** [comment]
Is this at all related to #489?

**Comment by LolitaSian** [comment]
> Is this at all related to #489?

Thank you. Nou I use 0.3.4 and everything is ok.

**Comment by LolitaSian** [comment]
> Is this at all related to #489?

Thank you. Now I use 0.3.4 and everything is ok.
