### ISSUE TITLE
dill.source.getsource() does not return expected results in IPython terminal or Notebook

### ISSUE THREAD

**Issue by vinc456** [uqfoundation/dill#54]
dill.source.getsource(some_function, enclosing=True) appears to return incorrect output when called from within an IPython terminal or Notebook session. The results differ from that of an ordinary Python terminal.

I'm running Python 2.7.7 |Anaconda 2.0.1 (64-bit)| (default, Jun 11 2014, 10:40:02) [MSC v.1
500 64 bit (AMD64)] on Windows 7 professional.

**Comment by mmckerns** [comment]
@vinc456: I'm assuming this was a suitable conclusion, then…?  or would you prefer a ticket with an option to remove IPython content so it looks like the same you'd get from raw python?

**Comment by pcko1** [comment]
> Actually it's an "IOError: could not get source code" error.
> 
> The follow getsource() call works as expected in an IPython session running from the Windows command line.
> 
> ```python
> In [1]: def doubler(f):
>    ...:         def func(*args, **kwds):
>    ...:                 return 2 * f(*args, **kwds)
>    ...:         return func
>    ...:
> 
> In [2]: @doubler
>    ...:
>    ...: def double_squared(x):
>    ...:         return x**2
>    ...:
> 
> In [3]: double_squared(5)
> Out[3]: 50
> 
> In [4]: import dill
> 
> In [5]: print dill.source.getsource(double_squared) # returns the expected result
> %%javascript
> from ctypes import CDLL
> # This will crash a linux system; equivalent calls can be made on Windows or Mac
> 
> libc = CDLL("libc.so.6")
> libc.time(-1)  # BOOM!!
> from time import sleep
> sleep(2)
> print 'test'
> from time import sleep
> sleep(2)
> print 'hi'
> %load soln/load.py
> import dill
> %clear
> import dill
> >>> def foo(x):
> ```
> 
> However, when running in the IPython Notebook or the IPython QT Console there is the following IOError.
> 
> ```python
> print dill.source.getsource(double_squared)
> ---------------------------------------------------------------------------
> IOError                                   Traceback (most recent call last)
> <ipython-input-5-a2b1f49c66be> in <module>()
> ----> 1 print dill.source.getsource(double_squared)
> 
> C:\Users\vinc456\Documents\GitHub\dill\dill\source.pyc in getsource(object, alias, lstrip, enclosing, force, builtin)
>     324     # get source lines; if fail, try to 'force' an import
>     325     try: # fails for builtins, and other assorted object types
> --> 326         lines, lnum = getsourcelines(object, enclosing=enclosing)
>     327     except (TypeError, IOError): # failed to get source, resort to import hooks
>     328         if not force: # don't try to get types that findsource can't get
> 
> C:\Users\vinc456\Documents\GitHub\dill\dill\source.pyc in getsourcelines(object, lstrip, enclosing)
>     295     If lstrip=True, ensure there is no indentation in the first line of code.
>     296     If enclosing=True, then also return any enclosing code."""
> --> 297     code, n = getblocks(object, lstrip=lstrip, enclosing=enclosing, locate=True)
>     298     return code[-1], n[-1]
>     299 
> 
> C:\Users\vinc456\Documents\GitHub\dill\dill\source.pyc in getblocks(object, lstrip, enclosing, locate)
>     221     DEPRECATED: use 'getsourcelines' instead
>     222     """
> --> 223     lines, lnum = findsource(object)
>     224 
>     225     if ismodule(object):
> 
> C:\Users\vinc456\Documents\GitHub\dill\dill\source.pyc in findsource(object)
>     125 
>     126     if not lines:
> --> 127         raise IOError('could not get source code')
>     128 
>     129     #FIXME: all below may fail if exec used (i.e. exec('f = lambda x:x') )
> 
> IOError: could not get source code
> ```

this is still an issue for me, `getsource` still fails in ipython (jupyter notebook)

**Comment by mmckerns** [comment]
@pcko1: are you seeing the exact error above with the exact same code, or what?
