### ISSUE TITLE
c++ function cannot be pickled

### ISSUE THREAD

**Issue by sddi** [uqfoundation/dill#547]
I implemented some functions in c++， and Python with SWIG， then I used  `dill.dumps` to pickle.
Finally, I get the message "PicklingWarning: Cannot pickle <type 'SwigPyObject'"

how can i solve it？

**Comment by mmckerns** [comment]
In order to pickle a C++ object, you'll need to implement a `__reduce__` method (or the equivalent). https://docs.python.org/3/library/pickle.html#object.__reduce__

**Comment by mmckerns** [comment]
Feel free to reopen this issue if you feel your question is not answered.
