### ISSUE TITLE
Massive performance loss from 0.3.5 to 0.3.6

### ISSUE THREAD

**Issue by cvjjm** [uqfoundation/dill#563]
I am seeing some massive performance loss going from `dill==0.3.5` to `dill==0.3.6`. 

Profiling the program with which I discovered this problem looks like this with `0.3.6`: 

![image](https://user-images.githubusercontent.com/60615188/200097361-f88fbbeb-7079-4c27-a07a-6a8f2e4c8a0c.png)

With `0.3.5` less than 2% of the runtime are spent in this branch.

The fact that `_dill:343 save` is called an enormously large number of times looks suspicious...

**Comment by mmckerns** [comment]
Thanks for the `gprof2dot` results.  Are you seeing this for some corner case, or in general?  It's generally helpful to include some test code that would enable us to try to reproduce your results.  It seems you might be dumping a `numpy.ufunc` or a `numpy.ndarray`.

**Comment by mmckerns** [comment]
Added profiling script for `dumps` in bae57e9bf36a.
Test suite:
```
get_gprof -n 2 -e 2 "import mystic; mystic.monitors.Monitor()"
get_gprof -n 2 -e 2 "import numpy; numpy.array([1,2,3])"
get_gprof -n 2 -e 2 "[1,2,3]"
get_gprof -n 2 -e 2 "import numpy; numpy.sin"
get_gprof -n 2 -e 2 "lambda x: x*x"

```
Tested `dill-0.3.5` versus `dill-0.3.6`.
Speed difference in all cases was negligible.

Call path looks very different, but it appears that runtime is pretty much the same in all cases, according to my testing (`python 3.7` on `macos`).

ndarray in 0.3.5:
![ndarray call](https://user-images.githubusercontent.com/321534/208317240-469cc097-901c-4e8b-899c-11cd4e42844d.png)

ndarray in 0.3.6:
![ndarray call](https://user-images.githubusercontent.com/321534/208317284-7b481fe8-2c34-40f4-b500-c3ea76b65552.png)

Times were nearly identical.

ufunc in 0.3.5:
![ufunc call](https://user-images.githubusercontent.com/321534/208317371-1412d23e-edb0-437f-a3d3-4fccc71c754e.png)

ufunc in 0.3.6:
![ufunc call](https://user-images.githubusercontent.com/321534/208317381-e5ba1072-f60c-49ec-be3d-8d62e234dfd4.png)

Times were nearly identical.
Same for the other objects tested.

I'm interested to see why you are experiencing a difference.  I'll try your example once you post it.

**Comment by mmckerns** [comment]
With the new `get_gprof` profiling script, I've been regularly testing objects and comparing to prior releases.  I'm not seeing any real performance differences in the last two releases.  I'm going to close this, but please feel free to reopen this if you post an example of what you were seeing that triggered this issue.
