### ISSUE TITLE
Remove the tests from wheels

### ISSUE THREAD

**Issue by KOLANICH** [uqfoundation/dill#576]

**Comment by mmckerns** [comment]
I don't have a compelling reason to do that.  Feel free to reopen this if you'd like to put some rationale behind why it'd be better to do that.

**Comment by KOLANICH** [comment]
>I don't have a compelling reason to do so.

I don't see any compelping reason to waste space on users' machines and PyPI for storage of the code they never need (they are not devs of `dill`, they are users of it).

**Comment by mmckerns** [comment]
I'd argue that the tests are useful if users are going to test support on platforms or versions that aren't formally stated, and potentially useful when users are reporting or contributing issues.  But, ok, thanks for your comments.
