### ISSUE TITLE
How to drop dill in python.multiprocessing?

### ISSUE THREAD

**Issue by adizhol** [uqfoundation/dill#584]
I'm trying to pickle objects that are not "pickable" using multiprcoessing.Process or multiprcoessing.manager.
Seems like importing dill at the head of my python program doesn't override the pickle functionality of multiprcoessing.
Is there a way to support this?

Thank you

**Comment by mmckerns** [comment]
use the package `multiprocess` instead of `multiprocessing`.  https://pypi.org/project/multiprocess/

**Comment by mmckerns** [comment]
Please reopen if this doesn't answer your question.
