### ISSUE TITLE
Question: Is `dill` compatible with Python 3.11?

### ISSUE THREAD

**Issue by inikolaev** [uqfoundation/dill#591]
I'm trying to migrate project to Python 3.11 and we use `pylint` that uses `dill`, but when installing `pylons` with `pipenv` I end up with the following entry for `dill`:

```
"dill": {
    "hashes": [
        "sha256:a07ffd2351b8c678dfc4a856a3005f8067aea51d6ba6c700796a4d9e280f39f0",
        "sha256:e5db55f3687856d8fbdab002ed78544e1c4559a130302693d839dfe8f93f2373"
    ],
    "markers": "python_version < '3.11'",
    "version": "==0.3.6"
},
``` 

Please note the `python_version < '3.11'`.

At the same time `dill` project page states it requires Python >= 3.7:
<img width="249" alt="image" src="https://github.com/uqfoundation/dill/assets/7585750/34e4d72c-34d9-4199-a362-a4c63712f3f0">

But then checking metadata in [PyPi](https://pypi.org/project/dill/) has no mention of Python 3.11:
<img width="272" alt="image" src="https://github.com/uqfoundation/dill/assets/7585750/a2d5376d-1417-437a-89ee-1c814d6555ef">

This well might be the way `pipenv` works and figures out the requirements, but it surely does not help :)

If `dill` does support Python 3.11, can we please update metadata and hopefully this will fix `pipenv` configuration?

**Comment by mmckerns** [comment]
The information above is all correct.  The latest release of `dill` was Oct 23, 2022, which pre-dates the release of python 3.11, so python 3.11 is not formally supported in the latest release. That release of `dill` does, however, work with python 3.11, and formal support came on Oct 25, 2022 (in master), just after the release of python 3.11.  What needs to happen is a new release of `dill` needs to be cut.  I had a target release date for the new release, but we slipped past it (I was in hospital). I basically just need some time during the weekend to cut a release, and I've been working non-stop in proposals the past few weeks. A new release is imminent, however.  If this doesn't answer your question, then please reopen the ticket.
