### ISSUE TITLE
Exception: --- Logging error ---

### ISSUE THREAD

**Issue by almostintuitive** [uqfoundation/dill#635]
<img width="771" alt="image" src="https://github.com/uqfoundation/dill/assets/5416288/511f2ae9-a74c-494b-81d6-b19574c34625">

Hi! We're using dill actively, it's of course extremely useful for us as well.
We're getting this exception just by adding a single class into the pickeld object. Did anyone bump into similar error messages? What could be the root cause?

Thank you!

**Comment by mmckerns** [comment]
Could you please provide a minimal self-contained bit of code that reproduces the error message you are seeing?  That would help us identify and diagnose what you are experiencing.

**Comment by mmckerns** [comment]
I added a guard for the size calculation... but please reopen if this doesn't fix your issue (and please post minimal example code with the full traceback next time).

**Comment by almostintuitive** [comment]
Thanks! Unfortunately it was really hard to reproduce outside of our codebase. In the end what helped is to move an enum declaration to a standalone file. I can not explain why, but since then, we don't have this issue.
