### ISSUE TITLE
add an ability to find the import string for constants and typedefs

### ISSUE THREAD

**Issue by chrisdonlan** [uqfoundation/dill#694]
Currently, if I set up a constant or typedef:

```
constant = 'foo'

Label = str
```

Then when I query for the import string with the constant or typedef's value, the getimport function will not work (of course):

```
dill.source.getimport(constant) 
```

This is a meaningless request, because `dill.source.getimport(constant)` will look at the value of constant to determine the import, which is a string, 'foo'. 

In order to support the look-up of typedefs and constants' import paths, something different would need to be attempted, likely involving reflection.

**Comment by chrisdonlan** [comment]
I was able to get around this with some logic.  Might be worth looking into though. Closing.

**Comment by mmckerns** [comment]
interesting -- thanks for the post
