### ISSUE TITLE
PicklingError for sqlalchemy Session

### ISSUE THREAD

**Issue by imazor** [uqfoundation/dill#74]
Hi,

Do you know about any issues with dill and sqlalchemy.

I am getting the following error when trying to create session with sqlalchemy:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/processing-0.52_pathos-py2.7-linux-x86_64.egg/processing/pool.py", line 207, in _handleTasks
    put(task)
  File "/usr/local/lib/python2.7/dist-packages/dill-0.2.3.dev-py2.7.egg/dill/dill.py", line 194, in dumps
    dump(obj, file, protocol, byref, fmode)#, strictio)
  File "/usr/local/lib/python2.7/dist-packages/dill-0.2.3.dev-py2.7.egg/dill/dill.py", line 184, in dump
    pik.dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 562, in save_tuple
    save(element)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 548, in save_tuple
    save(element)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 548, in save_tuple
    save(element)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python2.7/dist-packages/dill-0.2.3.dev-py2.7.egg/dill/dill.py", line 632, in save_function
    obj.__dict__), obj=obj)
  File "/usr/lib/python2.7/pickle.py", line 401, in save_reduce
    save(args)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 562, in save_tuple
    save(element)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 548, in save_tuple
    save(element)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python2.7/dist-packages/dill-0.2.3.dev-py2.7.egg/dill/dill.py", line 832, in save_cell
    pickler.save_reduce(_create_cell, (obj.cell_contents,), obj=obj)
  File "/usr/lib/python2.7/pickle.py", line 401, in save_reduce
    save(args)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 548, in save_tuple
    save(element)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python2.7/dist-packages/dill-0.2.3.dev-py2.7.egg/dill/dill.py", line 800, in save_instancemethod0
    obj.im_class), obj=obj)
  File "/usr/lib/python2.7/pickle.py", line 401, in save_reduce
    save(args)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 548, in save_tuple
    save(element)
  File "/usr/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python2.7/dist-packages/dill-0.2.3.dev-py2.7.egg/dill/dill.py", line 664, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib/python2.7/pickle.py", line 681, in _batch_setitems
    save(v)
  File "/usr/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python2.7/dist-packages/dill-0.2.3.dev-py2.7.egg/dill/dill.py", line 664, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib/python2.7/pickle.py", line 681, in _batch_setitems
    save(v)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python2.7/dist-packages/dill-0.2.3.dev-py2.7.egg/dill/dill.py", line 999, in save_type
    StockPickler.save_global(pickler, obj)
  File "/usr/lib/python2.7/pickle.py", line 753, in save_global
    (obj, module, name))
PicklingError: Can't pickle <class 'sqlalchemy.orm.session.Session'>: it's not the same object as sqlalchemy.orm.session.Session

my code is following:
db_engine = create_engine('%s://%s:%s@%s%s/%s' % ('postgresql+psycopg2', db_user, db_passwd, db_host, db_port, db_name))
Session = sessionmaker(bind=db_engine)

*** when the Session part is committed everything works fine.

Thanks,

**Comment by mmckerns** [comment]
It appears you are trying to pickle a `sqlalchemy.orm.session.Session` object -- or at least that's what the error says.  What are you trying to do, specifically?  Is what you posted above (reproduced below), the entirety of your test code (implicit imports, of course)?

    db_engine = create_engine('%s://%s:%s@%s%s/%s' % ('postgresql+psycopg2', db_user, db_passwd, db_host, db_port, db_name))
    Session = sessionmaker(bind=db_engine)

Note I do have a package that provides `dill` to be used more easily with `sqlalchemy` -- it's called `klepto` (found here: https://github.com/uqfoundation/klepto).  Although, I don't know what your underlying goal is, so I can't say for certain it will be useful to you.

**Comment by imazor** [comment]
I have a class the take json file and format it to csv file and in the next
step will load the csv file to the db (psql).
therefore I have different class methods for those different steps.

One of the class methods responsible for  getting db connection details
from config file and creates session instance (using sqlalchemy) that will
be used in order to load the csv file.
The method simply creates the session instance and assign it to class
property.

So actually, this method ran in the __init__.  Something like:
Self.session = self.get_session(config_fpath)

Btw, I have noticed that when creating the session instance inside the
get_session method but not assign it to "self", all run fine.
Am 14.01.2015 18:44 schrieb "Mike McKerns" <notifications@github.com>:

**Comment by mmckerns** [comment]
I did just try to serialize a `Session` object, and the default object seems to pickle:

    >>> import dill
    >>> from sqlalchemy import orm as sqlorm
    >>> s = sqlorm.session.Session()
    >>> s
    <sqlalchemy.orm.session.Session object at 0x10ad21ed0>
    >>> _s = dill.dumps(s)
    >>> s_ = dill.loads(_s)
    >>> s_
    <sqlalchemy.orm.session.Session object at 0x10af62910>>>> 
    >>> 
    >>> _s
    '\x80\x02csqlalchemy.orm.session\nSession\nq\x00)\x81q\x01}q\x02(U\nautocommitq\x03\x89U\tautoflushq\x04\x88U\x0btransactionq\x05csqlalchemy.orm.session\nSessionTransaction\nq\x06)\x81q\x07}q\x08(U\r_key_switchesq\t(cweakref\nWeakKeyDictionary\nq\noq\x0b}q\x0c(U\x07_removeq\rcdill.dill\n_create_function\nq\x0e(cdill.dill\n_unmarshal\nq\x0fTF\x01\x00\x00c\x02\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00S\x00\x00\x00sB\x00\x00\x00|\x01\x00\x83\x00\x00}\x02\x00|\x02\x00d\x00\x00k\t\x00r>\x00|\x02\x00j\x01\x00r1\x00|\x02\x00j\x02\x00j\x03\x00|\x00\x00\x83\x01\x00\x01q>\x00|\x02\x00j\x04\x00|\x00\x00=n\x00\x00d\x00\x00S(\x01\x00\x00\x00N(\x05\x00\x00\x00t\x04\x00\x00\x00Nonet\n\x00\x00\x00_iteratingt\x11\x00\x00\x00_pending_removalst\x06\x00\x00\x00appendt\x04\x00\x00\x00data(\x03\x00\x00\x00t\x01\x00\x00\x00kt\x07\x00\x00\x00selfreft\x04\x00\x00\x00self(\x00\x00\x00\x00(\x00\x00\x00\x00sT\x00\x00\x00/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.pyt\x06\x00\x00\x00remove\x1c\x01\x00\x00s\n\x00\x00\x00\x00\x01\t\x01\x0c\x01\t\x01\x13\x02q\x10\x85q\x11Rq\x12cweakref\n__dict__\nU\x06removeq\x13cdill.dill\n_create_weakref\nq\x14h\x0b\x85q\x15Rq\x16\x85q\x17N}q\x18tq\x19Rq\x1aU\x11_pending_removalsq\x1b]q\x1cU\n_iteratingq\x1dc__builtin__\nset\nq\x1e]q\x1f\x85q Rq!U\x04dataq"}q#ubU\x04_newq$(h\noq%}q&(h\rh\x0e(h\x12cweakref\n__dict__\nh\x13h\x14h%\x85q\'Rq(\x85q)N}q*tq+Rq,h\x1b]q-h\x1dh\x1e]q.\x85q/Rq0h"}q1ubU\x06_dirtyq2(h\noq3}q4(h\rh\x0e(h\x12cweakref\n__dict__\nh\x13h\x14h3\x85q5Rq6\x85q7N}q8tq9Rq:h\x1b]q;h\x1dh\x1e]q<\x85q=Rq>h"}q?ubU\x06_stateq@csqlalchemy.util.langhelpers\nsymbol\nqAU\x06ACTIVEqBU\x01xqCI-6214148235684208424\n\x87qDRqEU\x08_deletedqF(h\noqG}qH(h\rh\x0e(h\x12cweakref\n__dict__\nh\x13h\x14hG\x85qIRqJ\x85qKN}qLtqMRqNh\x1b]qOh\x1dh\x1e]qP\x85qQRqRh"}qSubU\x06nestedqT\x89U\x07_parentqUNU\x07sessionqVh\x01U\x0c_connectionsqW}qXubU\x08hash_keyqYK\x01U\x10expire_on_commitqZ\x88h$}q[U\x04bindq\\NhF}q]U\t_flushingq^\x89U\x0cidentity_mapq_csqlalchemy.orm.identity\nWeakInstanceDict\nq`)\x81qa}qb(U\x03_wrqch\x14ha\x85qdRqeU\t_modifiedqfh\x1e]qg\x85qhRqiubU\x08dispatchqjcsqlalchemy.event.base\n_UnpickleDispatch\nqk)\x81ql}qmbh\x00\x85qnRqoU\x1e_enable_transaction_accountingqp\x88U\r_identity_clsqqh`U\x08twophaseqr\x89U\x0f_warn_on_eventsqs\x89U\x0f_Session__bindsqt}quU\n_query_clsqvcsqlalchemy.orm.query\nQuery\nqwub.'

That means that your code might be adding something to it, where the combination is unpicklable, or that a `Session` created with the `sessionmaker` and using an engine instance is unpicklable,  I'm not sure, and it's hard to tell without playing with your (or similar) code.

`dill` does have some diagnostic utilities in `dill.detect`.  The methods therein enable you to inspect objects for methods and attributes that cause pickle failures.  My first step is usually to set `dill.detect.trace(True)` and look at the pickle-trace.

**Comment by mmckerns** [comment]
From your traceback, it looks like `dill` handles a `FunctionType`, then a `CellType` (so probably a `lambda`), then two calls to the "module dict" (typically for globals), then lastly it fails on the `Session` `type` object -- well, it actually punts to `pickle`, and `pickle` fails.

If you are building a class instance, you could also possibly add a `__reduce__` method to your class, to help with the serialization.

**Comment by imazor** [comment]
I have created the following code in order to test sqlalchemy session,
using sessionmaker:

import dill

from sqlalchemy import create_engine
from sqlalchemy.exc import OperationalError
from sqlalchemy.orm import sessionmaker
import yaml


dill.detect.trace(True)


class TestDill():
    def __init__(self, config_fpath):
        self.hallo = "hallo"
        self.world = self.get_world()
        self.db_connection = self.__get_db_connection(config_fpath)

    def get_world(self):
        return 'world'

    def __get_db_connection_config(self, yml_config_file_path):

        try:
            with open(yml_config_file_path, 'r') as db_connection:
                try:
                    return yaml.load(db_connection)
                except yaml.YAMLError as e:
                    msg = "Fail to extract db connection config data.
exit process"
                    exit(e)
        except IOError as e:
            msg = "Fail to extract db connection config data. exit process"
            exit(e)

    def __get_db_connection(self, db_connection_config_file_path):

        db_connection_config =
self.__get_db_connection_config(db_connection_config_file_path)
        try:
            db_type = db_connection_config['db_type']
            db_user = db_connection_config['db_user']
            db_passwd = db_connection_config['db_passwd']
            db_name = db_connection_config['db_name']
            db_host = db_connection_config['db_host']
            db_port = ":"+db_connection_config['db_port']
            db_schema = db_connection_config.get('db_schema', "")
            db_handle_null = db_connection_config.get('db_handle_null', None)

            db_engine = create_engine('%s://%s:%s@%s%s/%s' %
('postgresql+psycopg2', db_user, db_passwd, db_host, db_port,
db_name))
            Session = sessionmaker(bind=db_engine)

            return Session

        except KeyError, e:
            msg = "one of the db connection config details is missing,
please verify the config file. exit process"
            exit(e)

        except OperationalError, e:
            msg = "Operational Error"
            exit(e)



if __name__ == '__main__':
    dill_test = TestDill('psql_dwh_config.yml')
    _s = dill.dumps(dill_test)
    print [_s]
    #s_ = dill.loads(dill_test)


when __get_db_connection returns the Session, it fails. Here is the full
trackback:

C1: __main__.TestDill
T1: <type 'classobj'>
F2: <function _load_type at 0x7fa17e6a8410>
D2: <dict object at 0x7fa1775f74b0>
F1: <function __get_db_connection at 0x7fa1775f9488>
F2: <function _create_function at 0x7fa17e6a8500>
Co: <code object __get_db_connection at 0x7fa1b70eb9b0, file
"test_dill.py", line 43>
F2: <function _unmarshal at 0x7fa17e6a8398>
D1: <dict object at 0x7fa1b71e4168>
D2: <dict object at 0x7fa1b32ca5c8>
F1: <function __get_db_connection_config at 0x7fa1775f9410>
Co: <code object __get_db_connection_config at 0x7fa1b7148eb0, file
"test_dill.py", line 23>
D1: <dict object at 0x7fa1b71e4168>
D2: <dict object at 0x7fa1b0eb4d70>
F1: <function get_world at 0x7fa1775f9398>
Co: <code object get_world at 0x7fa1b7148ab0, file "test_dill.py", line 20>
D1: <dict object at 0x7fa1b71e4168>
D2: <dict object at 0x7fa1b0ece168>
F1: <function __init__ at 0x7fa1775f9320>
Co: <code object __init__ at 0x7fa1b7148bb0, file "test_dill.py", line 15>
D1: <dict object at 0x7fa1b71e4168>
D2: <dict object at 0x7fa1b0ece6e0>
D2: <dict object at 0x7fa1775f7e88>
T4: <class 'sqlalchemy.orm.session.sessionmaker'>
D2: <dict object at 0x7fa1b0eadc58>
T4: <class 'sqlalchemy.orm.session.Session'>
Traceback (most recent call last):
  File "test_dill.py", line 82, in <module>
    _s = dill.dumps(dill_test)
  File
"/usr/local/lib/python2.7/dist-packages/dill-0.2.3.dev-py2.7.egg/dill/dill.py",
line 194, in dumps
    dump(obj, file, protocol, byref, fmode)#, strictio)
  File
"/usr/local/lib/python2.7/dist-packages/dill-0.2.3.dev-py2.7.egg/dill/dill.py",
line 184, in dump
    pik.dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 725, in save_inst
    save(stuff)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File
"/usr/local/lib/python2.7/dist-packages/dill-0.2.3.dev-py2.7.egg/dill/dill.py",
line 664, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib/python2.7/pickle.py", line 681, in _batch_setitems
    save(v)
  File "/usr/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File
"/usr/local/lib/python2.7/dist-packages/dill-0.2.3.dev-py2.7.egg/dill/dill.py",
line 664, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib/python2.7/pickle.py", line 681, in _batch_setitems
    save(v)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File
"/usr/local/lib/python2.7/dist-packages/dill-0.2.3.dev-py2.7.egg/dill/dill.py",
line 1000, in save_type
    StockPickler.save_global(pickler, obj)
  File "/usr/lib/python2.7/pickle.py", line 753, in save_global
    (obj, module, name))
pickle.PicklingError: Can't pickle <class
'sqlalchemy.orm.session.Session'>: it's not the same object as
sqlalchemy.orm.session.Session


However, when creating the Session but returning something else (like None
or some String or even the db_engine), it works fine.

Any Ideas ?


On Wed, Jan 14, 2015 at 9:20 PM, Mike McKerns wrote: > From your traceback,
it looks like dill handles a FunctionType, then a > CellType (so probably a
lambda), then two calls to the "module dict" > (typically for globals),
then lastly it fails on the Session type object -- > well, it actually
punts to pickle, and pickle fails. > > If you are building a class
instance, you could also possibly add a > __reduce__ method to your class,
to help with the serialization. > > — > Reply to this email directly or
view it on GitHub. --
--------------------------------------------------------------------------
Igor Mazor Senior Business Intelligence Manager Rocket Internet AG |
Johannisstraße 20 | 10117 Berlin | Deutschland skype: igor_rocket_internet
| mail: igor.mazor@rocket-internet.de www.rocket-internet.de
Geschäftsführer: Dr. Johannes Bruder, Arnt Jeschke, Alexander Kudlich
Eingetragen beim Amtsgericht Berlin, HRB 109262 USt-ID DE256469659

**Comment by mmckerns** [comment]
You can see from the traceback and the `T4` in the `dill` trace tells me that `dill` is passing off the pickling of the `Session` class to `pickle` with `save_global`.  For most classes, `pickle` can do the job, but apparently this is one of those cases where `pickle` fails on a user-built class.  Since the return of the `Session` object is a problem, could you not just store it as `self.session`, or in a dict of `self.sessions`, and then return `None` or a string for the key for the session?

Another workaround would be to add a `__reduce__` method to your class, or to equivalently teach pickle how to reduce your class with `copy_reg`.

Workarounds aside, this seems to be a corner case that, as far as I can tell, is due to your class construction more than the inability to serialize a `Session` object -- which `dill` should handle when asked directly (demonstrated previously).  So what I'd say here, is that unless you can distill the example down to something that demonstrates it's a more general pickling failure, it's not something that `dill` should handle in it's code base.   What I mean is that if you can construct a minimal example that can help demonstrate it a broader type of failure (e.g. a programming pattern that fails for all classes, or it's **the** primary use case in `sqlalchemy`, or something like that), then one of my suggestions above is probably the best path forward.

**Comment by imazor** [comment]
Could you extend more regarding __reduce__ and how to use it or if you can
refer to example?

I took the code logic outside the class as following:

if __name__ == '__main__':

    def get_db_connection_config(yml_config_file_path):
        """
        Load yaml config file

        :param config_path: String - the path to the config file.

        :return Dict - parsed yaml file to Dict
        """

        try:
            with open(yml_config_file_path, 'r') as db_connection:
                try:
                    return yaml.load(db_connection)
                except yaml.YAMLError as e:
                    msg = "Fail to extract db connection config data.
exit process"
                    exit(e)
        except IOError as e:
            msg = "Fail to extract db connection config data. exit process"
            exit(e)

    db_connection_config = get_db_connection_config('psql_dwh_config.yml')

    db_type = db_connection_config['db_type']
    db_user = db_connection_config['db_user']
    db_passwd = db_connection_config['db_passwd']
    db_name = db_connection_config['db_name']
    db_host = db_connection_config['db_host']
    db_port = ":"+db_connection_config['db_port']
    db_schema = db_connection_config.get('db_schema', "")
    db_handle_null = db_connection_config.get('db_handle_null', None)

    db_engine = create_engine('%s://%s:%s@%s%s/%s' %
('postgresql+psycopg2', db_user, db_passwd, db_host, db_port,
db_name))
    Session = sessionmaker(bind=db_engine)

    _s = dill.dumps(Session)
    print [_s]


and it still fails - so my conclusion that session created via sessionmaker
could not be pickled or dilled.
(I thought that another workaround can be return dill(session) to the class
attribute and than undill it when necessary)

using the other workarounds is also possible (although I haven't tried them
yet) however at the moment its too overhead for something that I want to
keep simple.
I did further analysis of my code goals and realized that I can satisfied
with lower level API of sqlalchemy - meaning using only
create_engine().connect().
since I am not using in this case with any ORM type, I don't really need
the Session object.
pickling the db_engine looks to be fine. So at the moment I will stick to
this approach.



On Thu, Jan 15, 2015 at 2:23 PM, Mike McKerns <notifications@github.com>
wrote:

> You can see from the traceback and the T4 in the dill trace tells me that
> dill is passing off the pickling of the Session class to pickle with
> save_global. For most classes, pickle can do the job, but apparently this
> is one of those cases where pickle fails on a user-built class. Since the
> return of the Session object is a problem, could you not just store it as
> self.session, or in a dict of self.sessions, and then return None or a
> string for the key for the session?
>
> Another workaround would be to add a __reduce__ method to your class, or
> to equivalently teach pickle how to reduce your class with copy_reg.
>
> Workarounds aside, this seems to be a corner case that, as far as I can
> tell, is due to your class construction more than the inability to
> serialize a Session object -- which dill should handle when asked
> directly (demonstrated previously). So what I'd say here, is that unless
> you can distill the example down to something that demonstrates it's a more
> general pickling failure, it's not something that dill should handle in
> it's code base. What I mean is that if you can construct a minimal example
> that can help demonstrate it a broader type of failure (e.g. a programming
> pattern that fails for all classes, or it's *the* primary use case in
> sqlalchemy, or something like that), then one of my suggestions above is
> probably the best path forward.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uqfoundation/dill/issues/74#issuecomment-70084589>.
>



-- 
*--------------------------------------------------------------------------*

*Igor Mazor*
Senior Business Intelligence Manager


Rocket Internet AG  |  Johannisstraße 20  |  10117 Berlin  |  Deutschland
skype: igor_rocket_internet | mail: igor.mazor <http://goog_862328191>
@rocket-internet.de
www.rocket-internet.de

Geschäftsführer: Dr. Johannes Bruder, Arnt Jeschke, Alexander Kudlich
Eingetragen beim Amtsgericht Berlin, HRB 109262 USt-ID DE256469659

**Comment by mmckerns** [comment]
Well, that's good news.

Yes, I had tested `dill` for `Session` objects, but not building them via `sessionmaker` -- so maybe that is the issue… that `sessionmaker` does something funny in the construction which makes the `Session` unpicklable.  Either way, I'm going to pass on adding a fix to `dill` for this case unless I can discover that what `sessionmaker` is doing is a more broadly applicable issue.

If you want to look at examples of `__reduce__`, you can see some here:

  - https://github.com/uqfoundation/klepto/blob/master/klepto/_archives.py
  - https://github.com/uqfoundation/klepto/blob/master/klepto/_cache.py

What `__reduce__` does is help you declare what's needed to identify what the state of the object is, and when put in the form that `__reduce__` requires, it should serialize and save all the necessary state the object needs.

See https://docs.python.org/2/library/pickle.html#object.__reduce__ for the definition of what to return from `__reduce__`.

**Comment by flewellyn** [comment]
Hello,

I have run into an issue along these lines myself.  The problem is not trying to pickle a session object, per se, but a session object with a bound engine.  The engine fails to pickle, with an error about trying to pickle _thread.RLock objects.  

I've attached the output of the trace, using dill.detect.trace(True), as well as the exception thrown.

[dillerrorlog.txt](https://github.com/uqfoundation/dill/files/1076138/dillerrorlog.txt)

**Comment by mmckerns** [comment]
@flewellyn: that's weird that it fails on a `_thread.RLock` object.  That object can be serialized by `dill`.   Can you open a new ticket, and post some simplified code that produces the error you are seeing as well as the traceback?

**Comment by makmanalp** [comment]
@mmckerns re `threading.RLock` being picklable: https://bugs.python.org/issue29423#msg286830

**Comment by mmckerns** [comment]
@makmanalp: Thanks, but I'm not sure that's relevant... as `dill` has code to serialize a `_thread.RLock` object outside of `pickle`.
