### ISSUE TITLE
dill.pickles should be clarified for dynamically modified classes

### ISSUE THREAD

**Issue by lgerardSRI** [uqfoundation/dill#82]
I was expecting the following to return True

```python
import dill
class Bunch(object):
    def __init__(self, **kw):
        self.__dict__.update(kw)
b1 = Bunch(c=1)
print(dill.pickles(b1))
```

I got to this minimal example after some time. If this is expected I can make it more complex so that the dump actually throw various exceptions.

**Comment by mmckerns** [comment]
Here's the deal… they sort-of are picklable, and sort-of aren't.
The reason `dill.pickles` says `False` is that modifications to the class `dict` make it "different" than what you have coded.  You can see this a little more clearly if you look at this:

    >>> dill.detect.errors(b1)
    AssertionError("Unpickling produces <class '__main__.Bunch'> instead of <class '__main__.Bunch'>",)

So, I guess, I could relax the conditions that `dill.pickles` checks… so it doesn't count changes to the class as "unpicklable".  That probably should at least be a "strict" option that I should add.

But they do indeed pickle… in a less strict sense.

    >>> dill.dumps(b1)
    '\x80\x02cdill.dill\n_create_type\nq\x00(cdill.dill\n_load_type\nq\x01U\x08TypeTypeq\x02\x85q\x03Rq\x04U\x05Bunchq\x05h\x01U\nObjectTypeq\x06\x85q\x07Rq\x08\x85q\t}q\n(U\r__slotnames__q\x0b]q\x0cU\n__module__q\rU\x08__main__q\x0eU\x07__doc__q\x0fNU\x08__init__q\x10cdill.dill\n_create_function\nq\x11(cdill.dill\n_unmarshal\nq\x12U\x90c\x01\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00K\x00\x00\x00s\x14\x00\x00\x00|\x00\x00j\x00\x00j\x01\x00|\x01\x00\x8d\x00\x00\x01d\x00\x00S(\x01\x00\x00\x00N(\x02\x00\x00\x00t\x08\x00\x00\x00__dict__t\x06\x00\x00\x00update(\x02\x00\x00\x00t\x04\x00\x00\x00selft\x02\x00\x00\x00kw(\x00\x00\x00\x00(\x00\x00\x00\x00s\x07\x00\x00\x00<stdin>t\x08\x00\x00\x00__init__\x02\x00\x00\x00s\x02\x00\x00\x00\x00\x01q\x13\x85q\x14Rq\x15c__builtin__\n__main__\nh\x10NN}q\x16tq\x17Rq\x18utq\x19Rq\x1a)\x81q\x1b}q\x1cU\x01cq\x1dK\x01sb.'
    >>> b_ = _
    >>> dill.loads(b_)
    <__main__.Bunch object at 0x10fb70110>
    >>> b2 = _
    >>> b1.__dict__
    {'c': 1}
    >>> b2.__dict__
    {'c': 1}

So the action item then is that `dill.pickles` should be updated, and an option added to turn off/on checking for changes to class definitions?

**Comment by lgerardSRI** [comment]
I see, indeed I stripped the bunch part from my full example and dump still crashes, I'll try to find the actual culprit and probably open another ticket ;)
Thanks.

**Comment by mmckerns** [comment]
Ok.  Action item from this ticket is to clarify `dill.pickles` so that there's an option for testing against a class definition that has changed where the pickle 'succeeds'.

**Comment by mmckerns** [comment]
Options for this corner case are to check class name or to check repr.  I chose the latter. 6aa62df669d11fea8775a6ef1770069e9b1ecabf
