### ISSUE TITLE
can't pickle using dill for pyutilib.workflow objects

### ISSUE THREAD

**Issue by cogu6651** [uqfoundation/dill#87]
I'm trying to pickle (using the dill extension) a workflow object from pyutilib.workflow like so using python 2.7. The end objective here is to be able to insert these workflow objects into a MongoDB database and pulled out on the other end when needed:

    from pyutilib import workflow
    import testworkflow
    from bson.binary import Binary
    import pickle
    import dill
    import weakref

    A = testworkflow.testTask()
    w = workflow.Workflow()
    w.add(A)

    with open('w.dill', 'wb') as f:
        scriptbytes = dill.dump(w, f)
    script.close()

testworkflow.py only contains testTask(), which is written as follows:

    import pyutilib.workflow

    class testTask(pyutilib.workflow.Task):

    def __init__(self, *args, **kwds):
        pyutilib.workflow.Task.__init__(self, *args, **kwds)
        self.inputs.declare('x')
        self.inputs.declare('y')
        self.outputs.declare('z')

    def execute(self):
        self.z = self.x + self.y
But when I attempt to execute it to serialize the workflow object, I get a massive traceback list from the pickle.py file, at the very bottom of which is simply "AssertionError".

It seems to have troubles with things like:

  File "/usr/lib/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib/python2.7/pickle.py", line 681, in _batch_setitems
    save(v)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 905, in save_weakref
    pickler.save_reduce(_create_weakref, (refobj,), obj=obj)
  File "/usr/lib/python2.7/pickle.py", line 405, in save_reduce
    self.memoize(obj)
  File "/usr/lib/python2.7/pickle.py", line 244, in memoize
    assert id(obj) not in self.memo

The above chunk of traceback is, seriously, about 1% of the total list. Several tracebacks are to the same line of code, so is it a circular reference problem? I'm absolutely new to this type of project and I've searched all over for other related questions but none really seem to be quite relevant enough.

Am I missing some newer libraries? Is there a better way to do this?

EDIT: as per Martijn Pieters' helpful comment

> Pickling is a recursive process, which is why you see certain lines repeated. The process ends up back at an object that was pickled before (id(obj) in self.memo is true only if the object was already processed).

So how can I stop this condition from being triggered? Why can't pickling automatically ignore already-serialized chunks as a base case in recursion?

**Comment by mmckerns** [comment]
`dill` won't likely directly support those objects -- however, we might be able to help you support them.  I see that you've also posted on SO (http://stackoverflow.com/questions/29331295/using-dill-to-pickle-worfklow-objects), that's probably the better place for the first discussion for this particular issue… and we should later continue here if we find that it's something that `dill` should take on as a new bit of functionality.

**Comment by mmckerns** [comment]
Which `dill` version are you using? The recent release or the github trunk? It seems like it's something that is an object that `dill` does not know how to serialize. There are different ways to help `dill` learn how to handle the object… so post the relevant part of the traceback with `dill.detect(True)`.

**Comment by cogu6651** [comment]
Dill 0.2.2 I believe. adding 'dill.detect(True)', compiling and running didn't yield anything new other than the traceback. Is there a better way to do this? Is there a way to hack dill and utilize iteration instead of recursion? May sound dumb but I'm not intimately familiar with dill's internal workings

**Comment by mmckerns** [comment]
I don't see anything that's a standard object that `dill` is currently supposed to be working on that it's not in this case.  I'm closing this, as `dill` will not likely support these objects explicitly.  Let's continue on SO to try to help you out per your special case.
