### ISSUE TITLE
dill.dumps(atexit) in a virtualenv returns different value than with python 2.7.6 alone

### ISSUE THREAD

**Issue by lebedov** [uqfoundation/dill#91]
If I unpack the dill 0.2.2 tarball, cd to the unpacked directory, import it directly into a python 2.7.6 session started via /usr/bin/python on Ubuntu 14.04, and try importing atexit and serializing it with dill.dumps, I get something like
```
'\x80\x02cdill.dill\n_import_module\nq\x00U\x06atexitq\x01\x85q\x02Rq\x03.'
```
If, however, I create a virtualenv using the stock python-virtualenv 1.11.4 package on Ubuntu, import dill directly from the unpacked tarball and try serializing the imported atexit module, I get a different value:
```
'\x80\x02cdill.dill\n_import_module\nq\x00U\x06atexitq\x01\x85q\x02Rq\x03}q\x04(U\r_exithandlersq\x05]q\x06clogging\nshutdown\nq\x07)}q\x08\x87q\taU\x07__all__q\n]q\x0bU\x08registerq\x0caU\x08__file__q\rU\x1d/usr/lib/python2.7/atexit.pycq\x0eh\x0ccatexit\nregister\nq\x0fU\x0b__package__q\x10NU\x03sysq\x11h\x00U\x03sysq\x12\x85q\x13Rq\x14U\x0e_run_exitfuncsq\x15catexit\n_run_exitfuncs\nq\x16U\x08__name__q\x17h\x01U\x07__doc__q\x18U\x9c\natexit.py - allow programmer to define multiple exit functions to be executed\nupon normal program termination.\n\nOne public function, register, is defined.\nq\x19ub.'
```
Any idea why this might be happening? I ask because the presence of an unserializable function in
atexit._exithandlers causes dill.dumps(atexit) to raise an exception with virtualenv but not with python alone. 

Here is a full list of the commands and outputs illustrating the above:
```
$ tar zxf dill-0.2.2.tgz 
$ cd dill-0.2.2
$ /usr/bin/python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import atexit, dill
>>> dill.dumps(atexit)
'\x80\x02cdill.dill\n_import_module\nq\x00U\x06atexitq\x01\x85q\x02Rq\x03.'
>>> exit()
$ cd ..
$ /usr/bin/virtualenv ZZZ
New python executable in ZZZ/bin/python
Installing setuptools, pip...done.
$ cd dill-0.2.2
$ ~/ZZZ/bin/python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import atexit, dill
>>> dill.dumps(atexit)
'\x80\x02cdill.dill\n_import_module\nq\x00U\x06atexitq\x01\x85q\x02Rq\x03}q\x04(U\r_exithandlersq\x05]q\x06clogging\nshutdown\nq\x07)}q\x08\x87q\taU\x07__all__q\n]q\x0bU\x08registerq\x0caU\x08__file__q\rU\x1d/usr/lib/python2.7/atexit.pycq\x0eh\x0ccatexit\nregister\nq\x0fU\x0b__package__q\x10NU\x03sysq\x11h\x00U\x03sysq\x12\x85q\x13Rq\x14U\x0e_run_exitfuncsq\x15catexit\n_run_exitfuncs\nq\x16U\x08__name__q\x17h\x01U\x07__doc__q\x18U\x9c\natexit.py - allow programmer to define multiple exit functions to be executed\nupon normal program termination.\n\nOne public function, register, is defined.\nq\x19ub.'
>>> exit()
```

**Comment by matsjoyce** [comment]
Ah, I've just figured it out. Its because if the module name does not start with `sys.base_prefix` it gets fully serialised. Otherwise a ref is pickled. When using python, atexit is at the base_prefix, using virtualenv is isn't. @mmckerns For python 3.4 we could check against `sys.prefix`, but I'm not sure how to fix for python 2.7.

**Comment by lebedov** [comment]
@matsjoyce `sys.prefix` appears to be available in the virtualenv I created using 1.11.4 with Python 2.7.6.

**Comment by matsjoyce** [comment]
@lebedov Yes, but does it point to your virtualenv location or the system python location? In python 3 it points to the virtualenv, and `sys.base_prefix` points to the system. I'm not sure how python 2 does it.

**Comment by lebedov** [comment]
Judging from the virtualenv 1.11.4 code, it seems that if neither `sys.real_prefix` nor `sys.base_prefix` are available, it will only attempt to match the beginning of the name with `sys.prefix`.

**Comment by lebedov** [comment]
On my system, `sys.prefix` points to the virtualenv base directory in a Python 2.7 virtualenv.

**Comment by matsjoyce** [comment]
Yup, that's just the problem:
```py
[matthew@matthew-laptop TMP]$ bin/python2.7                                                                               
Python 2.7.9 (default, Dec 11 2014, 04:42:00) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.prefix
'/home/matthew/TMP'
>>> import atexit
>>> atexit.__file__
'/usr/lib64/python2.7/atexit.pyc'
```
Since `atexit` is not moved to the virtualenv, dill decides its a "user" package, and so pickles it. We could also check against `sys.realprefix`. Currently dill looks for base_prefix, then uses prefix. I could make it look for real_prefix first. I'll see if I can patch it.

**Comment by lebedov** [comment]
Relatedly, do you think `atexit` ought to be moved or copied by `virtualenv`? Other Python environment managers (e.g., conda) seem to do so. We could submit an issue and see what the `virtualenv` developers have to say.

**Comment by matsjoyce** [comment]
Well, its weird, because some files are moved, and some aren't. There may be some clever logic to which are copied and which aren't so ... I don't know. Might be interesting to investigate.

**Comment by lebedov** [comment]
Well, it can't hurt to see what they say.

**Comment by matsjoyce** [comment]
:smile:

**Comment by lebedov** [comment]
#92 seems to fix the problem.

**Comment by lebedov** [comment]
#92 also works with Python 3.4.

**Comment by mmckerns** [comment]
Looks good.  Thanks @matsjoyce, nice patch.  Thanks @lebedov for the ticket and follow-up.

**Comment by lebedov** [comment]
Thanks, guys - much appreciated.
