### ISSUE TITLE
Serialize lambdas in test files

### ISSUE THREAD

**Issue by mrocklin** [uqfoundation/dill#97]
Is it posible that dill fails to properly serialize a lambda created in a test file?

A test file is a strange place, it's not interactive but it also doesn't have proper module status.  

On some systems some of my distributed processing tests fail saying things like `No module named test_foo` which I suspect come from failed remote dill deserialization.

**Comment by mmckerns** [comment]
I see, this in with regard to: https://github.com/ContinuumIO/dask/issues/206.  Can you give me an example you are seeing?

**Comment by mmckerns** [comment]
This should also be fixed by #86.

**Comment by mmckerns** [comment]
as of fadbffc2b688aa99d3ba29015c4cdbef463bf565, this should work if you set your pickler to have `recurse=True`.

**Comment by mrocklin** [comment]
Awesome.  Can I set `recurse=True` globally within dill?  In what cases would I not want to do this?

**Comment by mmckerns** [comment]
you can set it on the `Pickler` as `Pickler._recurse`.   There are some corner cases that fail that need to be handled before it gets turned on by default.

**Comment by mmckerns** [comment]
added global setting `dill.settings['recurse']`
